### Jeremy Bradford Apri 18 - June 17 2016

In [1]:
import json
import pandas as pd
import os
import glob
from tqdm import tqdm
import re
from pandas.io.json import json_normalize
from datetime import datetime
import numpy as np

In [2]:
json_ll = glob.glob("/Users/snowr/ds_python1/running-America/vru_retry/Jeremy_json_files/jb_latlng/*.json")
json_as = glob.glob("/Users/snowr/ds_python1/running-America/vru_retry/Jeremy_json_files/jb_activity_stats/*.json")

assert(len(json_ll) == len(json_as))

for_df = []

keys = [re.findall(r'\d{5,}' , x.split("/")[-1])[0] for x in json_ll]

# goal: join the files based on their id

def get_my_dict_from_the_file(the_file_path):
    # returns a dictionary
    with open(the_file_path, 'r') as f:
        data = eval(f.read())
        return data

# below will give a list of dicts within for_df (list). I'll need to concat them all using pd.concat(axis=1?)

for key in tqdm(keys):
    # get the matching ll file
    # get the matching activity file
    # get the date later!
    matching_ll_file = [x for x in json_ll if key in x][0]
    matching_as_file = [x for x in json_as if key in x][0]
    #print(key, matching_ll_file, matching_as_file)
    ll_dict = get_my_dict_from_the_file(matching_ll_file)
    activity_dict = get_my_dict_from_the_file(matching_as_file)
    merged_dict = {**ll_dict, **activity_dict}
    merged_dict['activity_id'] = key
    print(merged_dict.keys())
    for_df.append(merged_dict)
    
    
pd.DataFrame.from_records(merged_dict).shape

  0%|                                                                                           | 0/73 [00:00<?, ?it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'grade_smooth', 'grade_adjusted_distance', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

  3%|██▎                                                                                | 2/73 [00:00<00:06, 11.27it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

  5%|████▌                                                                              | 4/73 [00:00<00:05, 12.07it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 10%|███████▉                                                                           | 7/73 [00:00<00:04, 13.77it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 14%|███████████▏                                                                      | 10/73 [00:00<00:03, 15.94it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 16%|█████████████▍                                                                    | 12/73 [00:00<00:03, 16.84it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 19%|███████████████▋                                                                  | 14/73 [00:00<00:03, 15.42it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 22%|█████████████████▉                                                                | 16/73 [00:00<00:03, 14.42it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 26%|█████████████████████▎                                                            | 19/73 [00:01<00:03, 15.36it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 29%|███████████████████████▌                                                          | 21/73 [00:01<00:03, 13.25it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 32%|█████████████████████████▊                                                        | 23/73 [00:01<00:03, 13.02it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 34%|████████████████████████████                                                      | 25/73 [00:01<00:03, 13.51it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 37%|██████████████████████████████▎                                                   | 27/73 [00:01<00:03, 12.22it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 40%|████████████████████████████████▌                                                 | 29/73 [00:01<00:03, 13.21it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 42%|██████████████████████████████████▊                                               | 31/73 [00:02<00:03, 12.53it/s]

dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 45%|█████████████████████████████████████                                             | 33/73 [00:02<00:03, 12.46it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 48%|███████████████████████████████████████▎                                          | 35/73 [00:02<00:03, 11.85it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 51%|█████████████████████████████████████████▌                                        | 37/73 [00:02<00:03, 11.82it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 53%|███████████████████████████████████████████▊                                      | 39/73 [00:02<00:02, 11.77it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 56%|██████████████████████████████████████████████                                    | 41/73 [00:03<00:02, 11.56it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 59%|████████████████████████████████████████████████▎                                 | 43/73 [00:03<00:02, 11.75it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 62%|██████████████████████████████████████████████████▌                               | 45/73 [00:03<00:02, 10.94it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 64%|████████████████████████████████████████████████████▊                             | 47/73 [00:03<00:02, 11.59it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 67%|███████████████████████████████████████████████████████                           | 49/73 [00:03<00:02, 11.87it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 70%|█████████████████████████████████████████████████████████▎                        | 51/73 [00:03<00:01, 12.35it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 73%|███████████████████████████████████████████████████████████▌                      | 53/73 [00:03<00:01, 13.65it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 78%|████████████████████████████████████████████████████████████████                  | 57/73 [00:04<00:01, 15.95it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 82%|███████████████████████████████████████████████████████████████████▍              | 60/73 [00:04<00:00, 17.47it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 85%|█████████████████████████████████████████████████████████████████████▋            | 62/73 [00:04<00:00, 15.30it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 88%|███████████████████████████████████████████████████████████████████████▉          | 64/73 [00:04<00:00, 13.68it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 90%|██████████████████████████████████████████████████████████████████████████▏       | 66/73 [00:04<00:00, 11.39it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 93%|████████████████████████████████████████████████████████████████████████████▍     | 68/73 [00:05<00:00, 10.92it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 96%|██████████████████████████████████████████████████████████████████████████████▋   | 70/73 [00:05<00:00, 11.24it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 99%|████████████████████████████████████████████████████████████████████████████████▉ | 72/73 [00:05<00:00, 11.54it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

100%|██████████████████████████████████████████████████████████████████████████████████| 73/73 [00:05<00:00, 13.38it/s]

(3440, 8)

In [3]:
out = pd.concat([pd.DataFrame.from_records(x) for x in for_df], axis=0)
out

,activity_id,altitude,cadence,distance,grade_adjusted_distance,grade_smooth,latlng,time,timer_time
0,136176596,3029.7,NaN,0.0,0.0,10.8,"[39.238152, -106.304127]",0,NaN
1,136176596,3029.8,NaN,0.8,2.7,33.2,"[39.23815, -106.304122]",2,NaN
2,136176596,3031.6,NaN,17.6,63.0,35.5,"[39.237999, -106.304083]",10,NaN
3,136176596,3039.6,NaN,29.8,107.4,36.3,"[39.237888, -106.30408]",18,NaN
4,136176596,3043.3,NaN,38.3,146.3,48.5,"[39.237812, -106.304076]",26,NaN
5,136176596,3046.2,NaN,46.0,174.8,37.1,"[39.237743, -106.304073]",34,NaN
6,136176596,3048.2,NaN,51.8,192.1,27.9,"[39.23769, -106.304073]",41,NaN
7,136176596,3050.0,NaN,57.8,205.4,19.2,"[39.237637, -106.304073]",48,NaN
8,136176596,3050.8,NaN,65.2,217.9,13.0,"[39.237571, -106.304065]",57,NaN
9,136176596,3051.8,NaN,75.2,231.7,8.7,"[39.237481, -106.304066]",66,NaN
10,136176596,3052.9,NaN,87.9,248.6,7.9,"[39.237369, -106.304038]",74,NaN
11,136176596,3053.9,NaN,102.4,266.9,6.7,"[39.237244, -106.303991]",81,NaN
12,136176596,3055.1,NaN,119.5,286.6,4.4,"[39.237095, -106.303944]",88,NaN
13,136176596,3055.8,NaN,135.0,303.2,2.4,"[39.23697, -106.304007]",94,NaN
14,136176596,3055.6,NaN,149.0,317.3,0.4,"[39.23692, -106.304154]",98,NaN
15,136176596,3055.4,NaN,164.7,332.9,-0.7,"[39.236807, -106.304258]",102,NaN
16,136176596,3055.4,NaN,191.6,358.4,-2.5,"[39.236567, -106.30428]",108,NaN
17,136176596,3055.3,NaN,205.8,371.0,-6.0,"[39.236439, -106.304282]",111,NaN
18,136176596,3053.6,NaN,228.4,390.8,-9.1,"[39.236252, -106.304385]",116,NaN
19,136176596,3050.1,NaN,252.5,411.9,-10.7,"[39.236108, -106.304579]",121,NaN
20,136176596,3049.0,NaN,262.2,420.4,-10.3,"[39.236085, -106.304694]",123,NaN
21,136176596,3047.8,NaN,275.7,433.3,-2.3,"[39.236071, -106.304848]",125,NaN
22,136176596,3047.5,NaN,287.7,445.9,1.9,"[39.236073, -106.304988]",127,NaN
23,136176596,3048.7,NaN,314.5,477.3,4.8,"[39.236063, -106.305299]",132,NaN
24,136176596,3050.4,NaN,334.8,502.5,6.3,"[39.235983, -106.305505]",137,NaN
25,136176596,3051.2,NaN,347.0,518.0,6.9,"[39.235881, -106.305554]",141,NaN
26,136176596,3052.4,NaN,365.6,540.5,5.6,"[39.235719, -106.305503]",147,NaN
27,136176596,3053.7,NaN,387.4,567.0,5.7,"[39.235552, -106.305377]",154,NaN
28,136176596,3054.8,NaN,412.8,596.6,4.7,"[39.235374, -106.305194]",161,NaN
29,136176596,3055.9,NaN,429.3,614.8,3.3,"[39.235228, -106.305184]",165,NaN
...,...,...,...,...,...,...,...,...,...
3410,611601462,30.2,0.0,50299.9,50536.5,2.8,"[40.714136, -74.006251]",28148,NaN
3411,611601462,30.4,60.0,50303.2,50540.2,2.6,"[40.714154, -74.006219]",28172,NaN
3412,611601462,31.2,55.0,50323.1,50561.7,1.9,"[40.714002, -74.006343]",28196,NaN
3413,611601462,31.4,57.0,50343.3,50582.9,1.2,"[40.713833, -74.006431]",28205,NaN
3414,611601462,31.4,78.0,50363.8,50603.9,0.5,"[40.713674, -74.006552]",28214,NaN
3415,611601462,31.4,60.0,50384.0,50624.7,0.8,"[40.713517, -74.006673]",28225,NaN
3416,611601462,31.6,60.0,50399.0,50640.2,0.8,"[40.713404, -74.006771]",28236,NaN
3417,611601462,32.0,60.0,50419.9,50661.5,0.5,"[40.713246, -74.006903]",28247,NaN
3418,611601462,32.0,60.0,50442.1,50684.3,0.6,"[40.713094, -74.007074]",28263,NaN
3419,611601462,31.8,60.0,50462.3,50705.1,0.8,"[40.712931, -74.00718]",28276,NaN
3420,611601462,32.0,0.0,50468.9,50711.6,-0.6,"[40.712884, -74.007227]",28281,NaN
3421,611601462,32.4,56.0,50472.4,50714.9,-1.1,"[40.712912, -74.007246]",28285,NaN
3422,611601462,31.8,0.0,50478.4,50720.9,0.0,"[40.712892, -74.007312]",28292,NaN
3423,611601462,31.6,0.0,50480.6,50722.9,-1.9,"[40.712884, -74.007336]",28294,NaN
3424,611601462,32.0,58.0,50501.7,50743.1,-1.1,"[40.712787, -74.007551]",28309,NaN
3425,611601462,31.4,58.0,50525.6,50766.7,-0.4,"[40.712575, -74.007592]",28323,NaN
3426,611601462,31.2,57.0,50532.8,50773.4,-1.8,"[40.71254, -74.007664]",28331,NaN
3427,611601462,31.4,57.0,50534.0,50774.6,0.0,"[40.712546, -74.007677]",28334,NaN
3428,611601462,31.4,57.0,50535.1,50775.8,2.8,"[40.712552, -74.007667]",28336,NaN
3429,611601462,31.4,57.0,50539.6,50780.6,1.4,"[40.712522, -74.007631]",28340,NaN
3430,611601462,32.0,0.0,50561.8,50803.8,1.1,"[40.71238, -74.007447]",28355,NaN
3431,611601462,32.0,54.0,50577.8,50820.6,1.2,"[40.712304, -74.007286]",28366,NaN
3432,611601462,32.0,0.0,50589.0,50831.8,0.0,"[40.712332, -74.007159]",28388,NaN
3433,611601462,32.0,0.0,50591.7,50834.5,0.5,"[40.712325, -74.007128]",28390,NaN
3434,611601462,32.0,0.0,50594.5,50837.5,1.9,"[40.712329, -74.007095]",28392,NaN
3435,611601462,32.2,60.0,50614.6,50859.0,1.7,"[40.712381, -74.006867]",28408,NaN
3436,611601462,32.6,54.0,50620.4,50865.3,1.9,"[40.712397, -74.006801]",28413,NaN
3437,611601462,32.6,60.0,50627.8,50874.2,4.5,"[40.712401, -74.006714]",28419,NaN
3438,611601462,32.8,0.0,50636.8,50884.7,3.7,"[40.712367, -74.006617]",28430,NaN
3439,611601462,33.2,0.0,50636.8,50884.7,6.7,"[40.712367, -74.006617]",28435,NaN

In [4]:
out.activity_id.value_counts()

607762635    6345
574423784    6329
550942056    6094
606536940    5882
575257198    5799
605395148    5787
603407452    5446
604472947    5404
601072566    5366
570285554    5335
558878122    5313
568999093    5255
611147383    5250
596576931    5083
581877347    5049
572270368    5033
567833618    5019
577594163    4933
586047337    4926
602281049    4892
581751057    4892
585089233    4857
576362440    4831
609381310    4816
600083459    4808
562722612    4798
573327768    4786
591427762    4784
583789604    4768
571264489    4745
             ...
594821322    4212
587163607    4071
557928992    4053
560475412    3971
592587643    3606
559710993    3509
554167393    3502
136176596    3453
611601462    3440
589663516    3389
555495997    3326
552058888    2933
553170911    2867
557061192    2854
566836128    2811
598092243    2721
556779379    2238
565769460    2058
594163078    1984
570286219    1884
552824937    1785
553717558    1528
595736312    1512
554870221    1236
574003838    1043
595736062     929
595735969     899
549839170     881
598090369     631
560501079     372
Name: activity_id, Length: 73, dtype: int64

In [5]:
#add date
import numpy as np
with open('/Users/snowr/ds_python1/running-America/vru_retry/Jeremy_json_files/jb_date.json', encoding="utf8") as f:
    data = json.load(f)
    
df_date = pd.DataFrame.from_dict(json_normalize(data), orient='columns')
df_date = df_date.T

#save to csv, flatten, reload
# df_date.to_csv("jb_date_activity.csv")

df_date = pd.read_csv("/Users/snowr/ds_python1/running-America/vru_retry/Jeremy_json_files/jb_date_activity.csv", parse_dates=True)

df_date

    activity_id       date
0     136176596  7/16/2011
1     549746013  4/18/2016
2     549839170  4/18/2016
3     550942056  4/19/2016
4     552058888  4/20/2016
5     552824937  4/21/2016
6     553170911  4/21/2016
7     553717558  4/22/2016
8     554167393  4/22/2016
9     554870221  4/23/2016
10    555495997  4/23/2016
11    556779379  4/25/2016
12    557061192  4/25/2016
13    557928992  4/26/2016
14    558878122  4/27/2016
15    559710993  4/28/2016
16    560475412  4/29/2016
17    560501079  4/29/2016
18    561565208  4/30/2016
19    562722612   5/1/2016
20    563664765   5/2/2016
21    564713272   5/3/2016
22    565769460   5/4/2016
23    566836128   5/5/2016
24    567833618   5/6/2016
25    568999093   5/7/2016
26    570285554   5/8/2016
27    570286219   5/4/2016
28    571264489   5/9/2016
29    572270368  5/10/2016
..          ...        ...
43    586047337  5/23/2016
44    587163607  5/24/2016
45    588272584  5/25/2016
46    589663516  5/26/2016
47    590278070  5/27/2016
48    591427762  5/28/2016
49    592587643  5/29/2016
50    593574086  5/30/2016
51    594163078  5/31/2016
52    594821322  5/31/2016
53    595735969   6/1/2016
54    595736062   6/1/2016
55    595736312   6/1/2016
56    596576931   6/2/2016
57    598090369   6/3/2016
58    598092243   6/3/2016
59    598810928   6/4/2016
60    600083459   6/5/2016
61    601072566   6/6/2016
62    602281049   6/7/2016
63    603407452   6/8/2016
64    604472947   6/9/2016
65    605395148  6/10/2016
66    606536940  6/11/2016
67    607762635  6/12/2016
68    608637718  6/13/2016
69    609381310  6/14/2016
70    610226724  6/14/2016
71    611147383  6/15/2016
72    611601462  6/16/2016

[73 rows x 2 columns]

In [6]:
#checks variable type of activity_id, changes to integer if needed
out['activity_id'] = out.activity_id.apply(lambda x: x if isinstance(x, int) else eval(x))

In [7]:
#check unique values in each
unique_out = out.activity_id.unique()
df_unique = df_date.activity_id.unique()
[x for x in df_unique if x in unique_out]

[136176596,
 549746013,
 549839170,
 550942056,
 552058888,
 552824937,
 553170911,
 553717558,
 554167393,
 554870221,
 555495997,
 556779379,
 557061192,
 557928992,
 558878122,
 559710993,
 560475412,
 560501079,
 561565208,
 562722612,
 563664765,
 564713272,
 565769460,
 566836128,
 567833618,
 568999093,
 570285554,
 570286219,
 571264489,
 572270368,
 573327768,
 574003838,
 574423784,
 575257198,
 576362440,
 577594163,
 578630766,
 579697044,
 581751057,
 581877347,
 582668939,
 583789604,
 585089233,
 586047337,
 587163607,
 588272584,
 589663516,
 590278070,
 591427762,
 592587643,
 593574086,
 594163078,
 594821322,
 595735969,
 595736062,
 595736312,
 596576931,
 598090369,
 598092243,
 598810928,
 600083459,
 601072566,
 602281049,
 603407452,
 604472947,
 605395148,
 606536940,
 607762635,
 608637718,
 609381310,
 610226724,
 611147383,
 611601462]

In [8]:
stats_date_jb = pd.merge(out, df_date, on="activity_id", how='inner') 
# stats_date_jb.drop('activity', axis=1)
stats_date_jb

,activity_id,altitude,cadence,distance,grade_adjusted_distance,grade_smooth,latlng,time,timer_time,date
0,136176596,3029.7,NaN,0.0,0.0,10.8,"[39.238152, -106.304127]",0,NaN,7/16/2011
1,136176596,3029.8,NaN,0.8,2.7,33.2,"[39.23815, -106.304122]",2,NaN,7/16/2011
2,136176596,3031.6,NaN,17.6,63.0,35.5,"[39.237999, -106.304083]",10,NaN,7/16/2011
3,136176596,3039.6,NaN,29.8,107.4,36.3,"[39.237888, -106.30408]",18,NaN,7/16/2011
4,136176596,3043.3,NaN,38.3,146.3,48.5,"[39.237812, -106.304076]",26,NaN,7/16/2011
5,136176596,3046.2,NaN,46.0,174.8,37.1,"[39.237743, -106.304073]",34,NaN,7/16/2011
6,136176596,3048.2,NaN,51.8,192.1,27.9,"[39.23769, -106.304073]",41,NaN,7/16/2011
7,136176596,3050.0,NaN,57.8,205.4,19.2,"[39.237637, -106.304073]",48,NaN,7/16/2011
8,136176596,3050.8,NaN,65.2,217.9,13.0,"[39.237571, -106.304065]",57,NaN,7/16/2011
9,136176596,3051.8,NaN,75.2,231.7,8.7,"[39.237481, -106.304066]",66,NaN,7/16/2011
10,136176596,3052.9,NaN,87.9,248.6,7.9,"[39.237369, -106.304038]",74,NaN,7/16/2011
11,136176596,3053.9,NaN,102.4,266.9,6.7,"[39.237244, -106.303991]",81,NaN,7/16/2011
12,136176596,3055.1,NaN,119.5,286.6,4.4,"[39.237095, -106.303944]",88,NaN,7/16/2011
13,136176596,3055.8,NaN,135.0,303.2,2.4,"[39.23697, -106.304007]",94,NaN,7/16/2011
14,136176596,3055.6,NaN,149.0,317.3,0.4,"[39.23692, -106.304154]",98,NaN,7/16/2011
15,136176596,3055.4,NaN,164.7,332.9,-0.7,"[39.236807, -106.304258]",102,NaN,7/16/2011
16,136176596,3055.4,NaN,191.6,358.4,-2.5,"[39.236567, -106.30428]",108,NaN,7/16/2011
17,136176596,3055.3,NaN,205.8,371.0,-6.0,"[39.236439, -106.304282]",111,NaN,7/16/2011
18,136176596,3053.6,NaN,228.4,390.8,-9.1,"[39.236252, -106.304385]",116,NaN,7/16/2011
19,136176596,3050.1,NaN,252.5,411.9,-10.7,"[39.236108, -106.304579]",121,NaN,7/16/2011
20,136176596,3049.0,NaN,262.2,420.4,-10.3,"[39.236085, -106.304694]",123,NaN,7/16/2011
21,136176596,3047.8,NaN,275.7,433.3,-2.3,"[39.236071, -106.304848]",125,NaN,7/16/2011
22,136176596,3047.5,NaN,287.7,445.9,1.9,"[39.236073, -106.304988]",127,NaN,7/16/2011
23,136176596,3048.7,NaN,314.5,477.3,4.8,"[39.236063, -106.305299]",132,NaN,7/16/2011
24,136176596,3050.4,NaN,334.8,502.5,6.3,"[39.235983, -106.305505]",137,NaN,7/16/2011
25,136176596,3051.2,NaN,347.0,518.0,6.9,"[39.235881, -106.305554]",141,NaN,7/16/2011
26,136176596,3052.4,NaN,365.6,540.5,5.6,"[39.235719, -106.305503]",147,NaN,7/16/2011
27,136176596,3053.7,NaN,387.4,567.0,5.7,"[39.235552, -106.305377]",154,NaN,7/16/2011
28,136176596,3054.8,NaN,412.8,596.6,4.7,"[39.235374, -106.305194]",161,NaN,7/16/2011
29,136176596,3055.9,NaN,429.3,614.8,3.3,"[39.235228, -106.305184]",165,NaN,7/16/2011
...,...,...,...,...,...,...,...,...,...,...
289341,611601462,30.2,0.0,50299.9,50536.5,2.8,"[40.714136, -74.006251]",28148,NaN,6/16/2016
289342,611601462,30.4,60.0,50303.2,50540.2,2.6,"[40.714154, -74.006219]",28172,NaN,6/16/2016
289343,611601462,31.2,55.0,50323.1,50561.7,1.9,"[40.714002, -74.006343]",28196,NaN,6/16/2016
289344,611601462,31.4,57.0,50343.3,50582.9,1.2,"[40.713833, -74.006431]",28205,NaN,6/16/2016
289345,611601462,31.4,78.0,50363.8,50603.9,0.5,"[40.713674, -74.006552]",28214,NaN,6/16/2016
289346,611601462,31.4,60.0,50384.0,50624.7,0.8,"[40.713517, -74.006673]",28225,NaN,6/16/2016
289347,611601462,31.6,60.0,50399.0,50640.2,0.8,"[40.713404, -74.006771]",28236,NaN,6/16/2016
289348,611601462,32.0,60.0,50419.9,50661.5,0.5,"[40.713246, -74.006903]",28247,NaN,6/16/2016
289349,611601462,32.0,60.0,50442.1,50684.3,0.6,"[40.713094, -74.007074]",28263,NaN,6/16/2016
289350,611601462,31.8,60.0,50462.3,50705.1,0.8,"[40.712931, -74.00718]",28276,NaN,6/16/2016
289351,611601462,32.0,0.0,50468.9,50711.6,-0.6,"[40.712884, -74.007227]",28281,NaN,6/16/2016
289352,611601462,32.4,56.0,50472.4,50714.9,-1.1,"[40.712912, -74.007246]",28285,NaN,6/16/2016
289353,611601462,31.8,0.0,50478.4,50720.9,0.0,"[40.712892, -74.007312]",28292,NaN,6/16/2016
289354,611601462,31.6,0.0,50480.6,50722.9,-1.9,"[40.712884, -74.007336]",28294,NaN,6/16/2016
289355,611601462,32.0,58.0,50501.7,50743.1,-1.1,"[40.712787, -74.007551]",28309,NaN,6/16/2016
289356,611601462,31.4,58.0,50525.6,50766.7,-0.4,"[40.712575, -74.007592]",28323,NaN,6/16/2016
289357,611601462,31.2,57.0,50532.8,50773.4,-1.8,"[40.71254, -74.007664]",28331,NaN,6/16/2016
289358,611601462,31.4,57.0,50534.0,50774.6,0.0,"[40.712546, -74.007677]",28334,NaN,6/16/2016
289359,611601462,31.4,57.0,50535.1,50775.8,2.8,"[40.712552, -74.007667]",28336,NaN,6/16/2016
289360,611601462,31.4,57.0,50539.6,50780.6,1.4,"[40.712522, -74.007631]",28340,NaN,6/16/2016
289361,611601462,32.0,0.0,50561.8,50803.8,1.1,"[40.71238, -74.007447]",28355,NaN,6/16/2016
289362,611601462,32.0,54.0,50577.8,50820.6,1.2,"[40.712304, -74.007286]",28366,NaN,6/16/2016
289363,611601462,32.0,0.0,50589.0,50831.8,0.0,"[40.712332, -74.007159]",28388,NaN,6/16/2016
289364,611601462,32.0,0.0,50591.7,50834.5,0.5,"[40.712325, -74.007128]",28390,NaN,6/16/2016
289365,611601462,32.0,0.0,50594.5,50837.5,1.9,"[40.712329, -74.007095]",28392,NaN,6/16/2016
289366,611601462,32.2,60.0,50614.6,50859.0,1.7,"[40.712381, -74.006867]",28408,NaN,6/16/2016
289367,611601462,32.6,54.0,50620.4,50865.3,1.9,"[40.712397, -74.006801]",28413,NaN,6/16/2016
289368,611601462,32.6,60.0,50627.8,50874.2,4.5,"[40.712401, -74.006714]",28419,NaN,6/16/2016
289369,611601462,32.8,0.0,50636.8,50884.7,3.7,"[40.712367, -74.006617]",28430,NaN,6/16/2016
289370,611601462,33.2,0.0,50636.8,50884.7,6.7,"[40.712367, -74.006617]",28435,NaN,6/16/2016

In [23]:
#convert to dattime object
stats_date_jb['date'] =pd.to_datetime(stats_date_jb['date'], errors='coerce')
stats_date_jb

,activity_id,altitude,cadence,distance,grade_adjusted_distance,grade_smooth,latlng,time,timer_time,date
0,136176596,3029.7,NaN,0.0,0.0,10.8,"[39.238152, -106.304127]",0,NaN,2011-07-16
1,136176596,3029.8,NaN,0.8,2.7,33.2,"[39.23815, -106.304122]",2,NaN,2011-07-16
2,136176596,3031.6,NaN,17.6,63.0,35.5,"[39.237999, -106.304083]",10,NaN,2011-07-16
3,136176596,3039.6,NaN,29.8,107.4,36.3,"[39.237888, -106.30408]",18,NaN,2011-07-16
4,136176596,3043.3,NaN,38.3,146.3,48.5,"[39.237812, -106.304076]",26,NaN,2011-07-16
5,136176596,3046.2,NaN,46.0,174.8,37.1,"[39.237743, -106.304073]",34,NaN,2011-07-16
6,136176596,3048.2,NaN,51.8,192.1,27.9,"[39.23769, -106.304073]",41,NaN,2011-07-16
7,136176596,3050.0,NaN,57.8,205.4,19.2,"[39.237637, -106.304073]",48,NaN,2011-07-16
8,136176596,3050.8,NaN,65.2,217.9,13.0,"[39.237571, -106.304065]",57,NaN,2011-07-16
9,136176596,3051.8,NaN,75.2,231.7,8.7,"[39.237481, -106.304066]",66,NaN,2011-07-16
10,136176596,3052.9,NaN,87.9,248.6,7.9,"[39.237369, -106.304038]",74,NaN,2011-07-16
11,136176596,3053.9,NaN,102.4,266.9,6.7,"[39.237244, -106.303991]",81,NaN,2011-07-16
12,136176596,3055.1,NaN,119.5,286.6,4.4,"[39.237095, -106.303944]",88,NaN,2011-07-16
13,136176596,3055.8,NaN,135.0,303.2,2.4,"[39.23697, -106.304007]",94,NaN,2011-07-16
14,136176596,3055.6,NaN,149.0,317.3,0.4,"[39.23692, -106.304154]",98,NaN,2011-07-16
15,136176596,3055.4,NaN,164.7,332.9,-0.7,"[39.236807, -106.304258]",102,NaN,2011-07-16
16,136176596,3055.4,NaN,191.6,358.4,-2.5,"[39.236567, -106.30428]",108,NaN,2011-07-16
17,136176596,3055.3,NaN,205.8,371.0,-6.0,"[39.236439, -106.304282]",111,NaN,2011-07-16
18,136176596,3053.6,NaN,228.4,390.8,-9.1,"[39.236252, -106.304385]",116,NaN,2011-07-16
19,136176596,3050.1,NaN,252.5,411.9,-10.7,"[39.236108, -106.304579]",121,NaN,2011-07-16
20,136176596,3049.0,NaN,262.2,420.4,-10.3,"[39.236085, -106.304694]",123,NaN,2011-07-16
21,136176596,3047.8,NaN,275.7,433.3,-2.3,"[39.236071, -106.304848]",125,NaN,2011-07-16
22,136176596,3047.5,NaN,287.7,445.9,1.9,"[39.236073, -106.304988]",127,NaN,2011-07-16
23,136176596,3048.7,NaN,314.5,477.3,4.8,"[39.236063, -106.305299]",132,NaN,2011-07-16
24,136176596,3050.4,NaN,334.8,502.5,6.3,"[39.235983, -106.305505]",137,NaN,2011-07-16
25,136176596,3051.2,NaN,347.0,518.0,6.9,"[39.235881, -106.305554]",141,NaN,2011-07-16
26,136176596,3052.4,NaN,365.6,540.5,5.6,"[39.235719, -106.305503]",147,NaN,2011-07-16
27,136176596,3053.7,NaN,387.4,567.0,5.7,"[39.235552, -106.305377]",154,NaN,2011-07-16
28,136176596,3054.8,NaN,412.8,596.6,4.7,"[39.235374, -106.305194]",161,NaN,2011-07-16
29,136176596,3055.9,NaN,429.3,614.8,3.3,"[39.235228, -106.305184]",165,NaN,2011-07-16
...,...,...,...,...,...,...,...,...,...,...
289341,611601462,30.2,0.0,50299.9,50536.5,2.8,"[40.714136, -74.006251]",28148,NaN,2016-06-16
289342,611601462,30.4,60.0,50303.2,50540.2,2.6,"[40.714154, -74.006219]",28172,NaN,2016-06-16
289343,611601462,31.2,55.0,50323.1,50561.7,1.9,"[40.714002, -74.006343]",28196,NaN,2016-06-16
289344,611601462,31.4,57.0,50343.3,50582.9,1.2,"[40.713833, -74.006431]",28205,NaN,2016-06-16
289345,611601462,31.4,78.0,50363.8,50603.9,0.5,"[40.713674, -74.006552]",28214,NaN,2016-06-16
289346,611601462,31.4,60.0,50384.0,50624.7,0.8,"[40.713517, -74.006673]",28225,NaN,2016-06-16
289347,611601462,31.6,60.0,50399.0,50640.2,0.8,"[40.713404, -74.006771]",28236,NaN,2016-06-16
289348,611601462,32.0,60.0,50419.9,50661.5,0.5,"[40.713246, -74.006903]",28247,NaN,2016-06-16
289349,611601462,32.0,60.0,50442.1,50684.3,0.6,"[40.713094, -74.007074]",28263,NaN,2016-06-16
289350,611601462,31.8,60.0,50462.3,50705.1,0.8,"[40.712931, -74.00718]",28276,NaN,2016-06-16
289351,611601462,32.0,0.0,50468.9,50711.6,-0.6,"[40.712884, -74.007227]",28281,NaN,2016-06-16
289352,611601462,32.4,56.0,50472.4,50714.9,-1.1,"[40.712912, -74.007246]",28285,NaN,2016-06-16
289353,611601462,31.8,0.0,50478.4,50720.9,0.0,"[40.712892, -74.007312]",28292,NaN,2016-06-16
289354,611601462,31.6,0.0,50480.6,50722.9,-1.9,"[40.712884, -74.007336]",28294,NaN,2016-06-16
289355,611601462,32.0,58.0,50501.7,50743.1,-1.1,"[40.712787, -74.007551]",28309,NaN,2016-06-16
289356,611601462,31.4,58.0,50525.6,50766.7,-0.4,"[40.712575, -74.007592]",28323,NaN,2016-06-16
289357,611601462,31.2,57.0,50532.8,50773.4,-1.8,"[40.71254, -74.007664]",28331,NaN,2016-06-16
289358,611601462,31.4,57.0,50534.0,50774.6,0.0,"[40.712546, -74.007677]",28334,NaN,2016-06-16
289359,611601462,31.4,57.0,50535.1,50775.8,2.8,"[40.712552, -74.007667]",28336,NaN,2016-06-16
289360,611601462,31.4,57.0,50539.6,50780.6,1.4,"[40.712522, -74.007631]",28340,NaN,2016-06-16
289361,611601462,32.0,0.0,50561.8,50803.8,1.1,"[40.71238, -74.007447]",28355,NaN,2016-06-16
289362,611601462,32.0,54.0,50577.8,50820.6,1.2,"[40.712304, -74.007286]",28366,NaN,2016-06-16
289363,611601462,32.0,0.0,50589.0,50831.8,0.0,"[40.712332, -74.007159]",28388,NaN,2016-06-16
289364,611601462,32.0,0.0,50591.7,50834.5,0.5,"[40.712325, -74.007128]",28390,NaN,2016-06-16
289365,611601462,32.0,0.0,50594.5,50837.5,1.9,"[40.712329, -74.007095]",28392,NaN,2016-06-16
289366,611601462,32.2,60.0,50614.6,50859.0,1.7,"[40.712381, -74.006867]",28408,NaN,2016-06-16
289367,611601462,32.6,54.0,50620.4,50865.3,1.9,"[40.712397, -74.006801]",28413,NaN,2016-06-16
289368,611601462,32.6,60.0,50627.8,50874.2,4.5,"[40.712401, -74.006714]",28419,NaN,2016-06-16
289369,611601462,32.8,0.0,50636.8,50884.7,3.7,"[40.712367, -74.006617]",28430,NaN,2016-06-16
289370,611601462,33.2,0.0,50636.8,50884.7,6.7,"[40.712367, -74.006617]",28435,NaN,2016-06-16

In [24]:
#filter the data for run dates
jeremy_run = stats_date_jb[(stats_date_jb['date'] > '2016-04-16') & (stats_date_jb['date'] < '2016-06-18')]
jeremy_run

,activity_id,altitude,cadence,distance,grade_adjusted_distance,grade_smooth,latlng,time,timer_time,date
3453,549746013,10.2,0.0,0.0,0.0,-0.7,"[34.007696, -118.499512]",0,NaN,2016-04-18
3454,549746013,9.6,0.0,4.8,4.8,0.0,"[34.007726, -118.499474]",3,NaN,2016-04-18
3455,549746013,10.0,80.0,26.7,26.7,0.0,"[34.007877, -118.499323]",11,NaN,2016-04-18
3456,549746013,10.2,78.0,47.8,48.6,0.9,"[34.008013, -118.499163]",19,NaN,2016-04-18
3457,549746013,10.2,79.0,69.7,70.7,0.2,"[34.008149, -118.498991]",27,NaN,2016-04-18
3458,549746013,10.4,80.0,91.7,93.1,0.4,"[34.008288, -118.498822]",35,NaN,2016-04-18
3459,549746013,10.2,79.0,114.5,116.1,0.2,"[34.008432, -118.498647]",43,NaN,2016-04-18
3460,549746013,10.6,79.0,137.2,138.8,0.0,"[34.008581, -118.498479]",51,NaN,2016-04-18
3461,549746013,10.4,80.0,159.3,160.9,0.0,"[34.008714, -118.498301]",59,NaN,2016-04-18
3462,549746013,10.4,79.0,181.9,182.9,-0.7,"[34.008851, -118.49812]",67,NaN,2016-04-18
3463,549746013,10.2,79.0,202.7,203.3,-0.5,"[34.008985, -118.497963]",75,NaN,2016-04-18
3464,549746013,10.0,78.0,225.0,225.4,-0.2,"[34.009124, -118.497788]",83,NaN,2016-04-18
3465,549746013,10.0,79.0,247.0,247.4,0.0,"[34.009263, -118.497619]",91,NaN,2016-04-18
3466,549746013,10.2,79.0,267.2,266.7,-1.1,"[34.0094, -118.497476]",98,NaN,2016-04-18
3467,549746013,10.2,78.0,288.5,284.3,-4.9,"[34.009546, -118.497326]",106,NaN,2016-04-18
3468,549746013,9.2,60.0,296.8,290.7,-6.8,"[34.009618, -118.497302]",123,NaN,2016-04-18
3469,549746013,7.4,60.0,299.6,292.6,-10.9,"[34.009639, -118.497319]",126,NaN,2016-04-18
3470,549746013,6.6,80.0,320.3,309.8,-4.7,"[34.009598, -118.497538]",136,NaN,2016-04-18
3471,549746013,6.4,79.0,323.5,313.0,-0.3,"[34.00958, -118.497564]",137,NaN,2016-04-18
3472,549746013,7.0,78.0,343.9,333.6,0.3,"[34.009468, -118.49774]",145,NaN,2016-04-18
3473,549746013,7.2,80.0,366.1,356.3,0.5,"[34.009349, -118.497932]",153,NaN,2016-04-18
3474,549746013,6.8,80.0,387.1,376.0,-1.5,"[34.009224, -118.498103]",161,NaN,2016-04-18
3475,549746013,6.8,80.0,408.7,395.1,-3.1,"[34.009098, -118.498281]",170,NaN,2016-04-18
3476,549746013,5.8,70.0,423.9,409.0,-2.3,"[34.009025, -118.49842]",180,NaN,2016-04-18
3477,549746013,5.4,70.0,424.9,410.0,-0.9,"[34.009033, -118.498426]",184,NaN,2016-04-18
3478,549746013,5.8,0.0,430.8,416.5,2.6,"[34.009085, -118.498436]",237,NaN,2016-04-18
3479,549746013,6.4,80.0,451.9,439.4,2.0,"[34.009189, -118.498245]",249,NaN,2016-04-18
3480,549746013,6.6,80.0,454.8,442.4,0.9,"[34.009204, -118.498219]",250,NaN,2016-04-18
3481,549746013,6.4,80.0,475.1,463.2,0.6,"[34.009305, -118.498036]",258,NaN,2016-04-18
3482,549746013,6.4,81.0,496.2,484.3,0.0,"[34.009402, -118.497839]",266,NaN,2016-04-18
...,...,...,...,...,...,...,...,...,...,...
289341,611601462,30.2,0.0,50299.9,50536.5,2.8,"[40.714136, -74.006251]",28148,NaN,2016-06-16
289342,611601462,30.4,60.0,50303.2,50540.2,2.6,"[40.714154, -74.006219]",28172,NaN,2016-06-16
289343,611601462,31.2,55.0,50323.1,50561.7,1.9,"[40.714002, -74.006343]",28196,NaN,2016-06-16
289344,611601462,31.4,57.0,50343.3,50582.9,1.2,"[40.713833, -74.006431]",28205,NaN,2016-06-16
289345,611601462,31.4,78.0,50363.8,50603.9,0.5,"[40.713674, -74.006552]",28214,NaN,2016-06-16
289346,611601462,31.4,60.0,50384.0,50624.7,0.8,"[40.713517, -74.006673]",28225,NaN,2016-06-16
289347,611601462,31.6,60.0,50399.0,50640.2,0.8,"[40.713404, -74.006771]",28236,NaN,2016-06-16
289348,611601462,32.0,60.0,50419.9,50661.5,0.5,"[40.713246, -74.006903]",28247,NaN,2016-06-16
289349,611601462,32.0,60.0,50442.1,50684.3,0.6,"[40.713094, -74.007074]",28263,NaN,2016-06-16
289350,611601462,31.8,60.0,50462.3,50705.1,0.8,"[40.712931, -74.00718]",28276,NaN,2016-06-16
289351,611601462,32.0,0.0,50468.9,50711.6,-0.6,"[40.712884, -74.007227]",28281,NaN,2016-06-16
289352,611601462,32.4,56.0,50472.4,50714.9,-1.1,"[40.712912, -74.007246]",28285,NaN,2016-06-16
289353,611601462,31.8,0.0,50478.4,50720.9,0.0,"[40.712892, -74.007312]",28292,NaN,2016-06-16
289354,611601462,31.6,0.0,50480.6,50722.9,-1.9,"[40.712884, -74.007336]",28294,NaN,2016-06-16
289355,611601462,32.0,58.0,50501.7,50743.1,-1.1,"[40.712787, -74.007551]",28309,NaN,2016-06-16
289356,611601462,31.4,58.0,50525.6,50766.7,-0.4,"[40.712575, -74.007592]",28323,NaN,2016-06-16
289357,611601462,31.2,57.0,50532.8,50773.4,-1.8,"[40.71254, -74.007664]",28331,NaN,2016-06-16
289358,611601462,31.4,57.0,50534.0,50774.6,0.0,"[40.712546, -74.007677]",28334,NaN,2016-06-16
289359,611601462,31.4,57.0,50535.1,50775.8,2.8,"[40.712552, -74.007667]",28336,NaN,2016-06-16
289360,611601462,31.4,57.0,50539.6,50780.6,1.4,"[40.712522, -74.007631]",28340,NaN,2016-06-16
289361,611601462,32.0,0.0,50561.8,50803.8,1.1,"[40.71238, -74.007447]",28355,NaN,2016-06-16
289362,611601462,32.0,54.0,50577.8,50820.6,1.2,"[40.712304, -74.007286]",28366,NaN,2016-06-16
289363,611601462,32.0,0.0,50589.0,50831.8,0.0,"[40.712332, -74.007159]",28388,NaN,2016-06-16
289364,611601462,32.0,0.0,50591.7,50834.5,0.5,"[40.712325, -74.007128]",28390,NaN,2016-06-16
289365,611601462,32.0,0.0,50594.5,50837.5,1.9,"[40.712329, -74.007095]",28392,NaN,2016-06-16
289366,611601462,32.2,60.0,50614.6,50859.0,1.7,"[40.712381, -74.006867]",28408,NaN,2016-06-16
289367,611601462,32.6,54.0,50620.4,50865.3,1.9,"[40.712397, -74.006801]",28413,NaN,2016-06-16
289368,611601462,32.6,60.0,50627.8,50874.2,4.5,"[40.712401, -74.006714]",28419,NaN,2016-06-16
289369,611601462,32.8,0.0,50636.8,50884.7,3.7,"[40.712367, -74.006617]",28430,NaN,2016-06-16
289370,611601462,33.2,0.0,50636.8,50884.7,6.7,"[40.712367, -74.006617]",28435,NaN,2016-06-16

In [25]:
jeremy_run['lat'] = jeremy_run['latlng'].apply(lambda x: x[0])
jeremy_run['long'] = jeremy_run['latlng'].apply(lambda x: x[1])
jeremy_run

C:\Users\snowr\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\snowr\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,activity_id,altitude,cadence,distance,grade_adjusted_distance,grade_smooth,latlng,time,timer_time,date,lat,long
3453,549746013,10.2,0.0,0.0,0.0,-0.7,"[34.007696, -118.499512]",0,NaN,2016-04-18,34.007696,-118.499512
3454,549746013,9.6,0.0,4.8,4.8,0.0,"[34.007726, -118.499474]",3,NaN,2016-04-18,34.007726,-118.499474
3455,549746013,10.0,80.0,26.7,26.7,0.0,"[34.007877, -118.499323]",11,NaN,2016-04-18,34.007877,-118.499323
3456,549746013,10.2,78.0,47.8,48.6,0.9,"[34.008013, -118.499163]",19,NaN,2016-04-18,34.008013,-118.499163
3457,549746013,10.2,79.0,69.7,70.7,0.2,"[34.008149, -118.498991]",27,NaN,2016-04-18,34.008149,-118.498991
3458,549746013,10.4,80.0,91.7,93.1,0.4,"[34.008288, -118.498822]",35,NaN,2016-04-18,34.008288,-118.498822
3459,549746013,10.2,79.0,114.5,116.1,0.2,"[34.008432, -118.498647]",43,NaN,2016-04-18,34.008432,-118.498647
3460,549746013,10.6,79.0,137.2,138.8,0.0,"[34.008581, -118.498479]",51,NaN,2016-04-18,34.008581,-118.498479
3461,549746013,10.4,80.0,159.3,160.9,0.0,"[34.008714, -118.498301]",59,NaN,2016-04-18,34.008714,-118.498301
3462,549746013,10.4,79.0,181.9,182.9,-0.7,"[34.008851, -118.49812]",67,NaN,2016-04-18,34.008851,-118.498120
3463,549746013,10.2,79.0,202.7,203.3,-0.5,"[34.008985, -118.497963]",75,NaN,2016-04-18,34.008985,-118.497963
3464,549746013,10.0,78.0,225.0,225.4,-0.2,"[34.009124, -118.497788]",83,NaN,2016-04-18,34.009124,-118.497788
3465,549746013,10.0,79.0,247.0,247.4,0.0,"[34.009263, -118.497619]",91,NaN,2016-04-18,34.009263,-118.497619
3466,549746013,10.2,79.0,267.2,266.7,-1.1,"[34.0094, -118.497476]",98,NaN,2016-04-18,34.009400,-118.497476
3467,549746013,10.2,78.0,288.5,284.3,-4.9,"[34.009546, -118.497326]",106,NaN,2016-04-18,34.009546,-118.497326
3468,549746013,9.2,60.0,296.8,290.7,-6.8,"[34.009618, -118.497302]",123,NaN,2016-04-18,34.009618,-118.497302
3469,549746013,7.4,60.0,299.6,292.6,-10.9,"[34.009639, -118.497319]",126,NaN,2016-04-18,34.009639,-118.497319
3470,549746013,6.6,80.0,320.3,309.8,-4.7,"[34.009598, -118.497538]",136,NaN,2016-04-18,34.009598,-118.497538
3471,549746013,6.4,79.0,323.5,313.0,-0.3,"[34.00958, -118.497564]",137,NaN,2016-04-18,34.009580,-118.497564
3472,549746013,7.0,78.0,343.9,333.6,0.3,"[34.009468, -118.49774]",145,NaN,2016-04-18,34.009468,-118.497740
3473,549746013,7.2,80.0,366.1,356.3,0.5,"[34.009349, -118.497932]",153,NaN,2016-04-18,34.009349,-118.497932
3474,549746013,6.8,80.0,387.1,376.0,-1.5,"[34.009224, -118.498103]",161,NaN,2016-04-18,34.009224,-118.498103
3475,549746013,6.8,80.0,408.7,395.1,-3.1,"[34.009098, -118.498281]",170,NaN,2016-04-18,34.009098,-118.498281
3476,549746013,5.8,70.0,423.9,409.0,-2.3,"[34.009025, -118.49842]",180,NaN,2016-04-18,34.009025,-118.498420
3477,549746013,5.4,70.0,424.9,410.0,-0.9,"[34.009033, -118.498426]",184,NaN,2016-04-18,34.009033,-118.498426
3478,549746013,5.8,0.0,430.8,416.5,2.6,"[34.009085, -118.498436]",237,NaN,2016-04-18,34.009085,-118.498436
3479,549746013,6.4,80.0,451.9,439.4,2.0,"[34.009189, -118.498245]",249,NaN,2016-04-18,34.009189,-118.498245
3480,549746013,6.6,80.0,454.8,442.4,0.9,"[34.009204, -118.498219]",250,NaN,2016-04-18,34.009204,-118.498219
3481,549746013,6.4,80.0,475.1,463.2,0.6,"[34.009305, -118.498036]",258,NaN,2016-04-18,34.009305,-118.498036
3482,549746013,6.4,81.0,496.2,484.3,0.0,"[34.009402, -118.497839]",266,NaN,2016-04-18,34.009402,-118.497839
...,...,...,...,...,...,...,...,...,...,...,...,...
289341,611601462,30.2,0.0,50299.9,50536.5,2.8,"[40.714136, -74.006251]",28148,NaN,2016-06-16,40.714136,-74.006251
289342,611601462,30.4,60.0,50303.2,50540.2,2.6,"[40.714154, -74.006219]",28172,NaN,2016-06-16,40.714154,-74.006219
289343,611601462,31.2,55.0,50323.1,50561.7,1.9,"[40.714002, -74.006343]",28196,NaN,2016-06-16,40.714002,-74.006343
289344,611601462,31.4,57.0,50343.3,50582.9,1.2,"[40.713833, -74.006431]",28205,NaN,2016-06-16,40.713833,-74.006431
289345,611601462,31.4,78.0,50363.8,50603.9,0.5,"[40.713674, -74.006552]",28214,NaN,2016-06-16,40.713674,-74.006552
289346,611601462,31.4,60.0,50384.0,50624.7,0.8,"[40.713517, -74.006673]",28225,NaN,2016-06-16,40.713517,-74.006673
289347,611601462,31.6,60.0,50399.0,50640.2,0.8,"[40.713404, -74.006771]",28236,NaN,2016-06-16,40.713404,-74.006771
289348,611601462,32.0,60.0,50419.9,50661.5,0.5,"[40.713246, -74.006903]",28247,NaN,2016-06-16,40.713246,-74.006903
289349,611601462,32.0,60.0,50442.1,50684.3,0.6,"[40.713094, -74.007074]",28263,NaN,2016-06-16,40.713094,-74.007074
289350,611601462,31.8,60.0,50462.3,50705.1,0.8,"[40.712931, -74.00718]",28276,NaN,2016-06-16,40.712931,-74.007180
289351,611601462,32.0,0.0,50468.9,50711.6,-0.6,"[40.712884, -74.007227]",28281,NaN,2016-06-16,40.712884,-74.007227
289352,611601462,32.4,56.0,50472.4,50714.9,-1.1,"[40.712912, -74.007246]",28285,NaN,2016-06-16,40.712912,-74.007246
289353,611601462,31.8,0.0,50478.4,50720.9,0.0,"[40.712892, -74.007312]",28292,NaN,2016-06-16,40.712892,-74.007312
289354,611601462,31.6,0.0,50480.6,50722.9,-1.9,"[40.712884, -74.007336]",28294,NaN,2016-06-16,40.712884,-74.007336
289355,611601462,32.0,58.0,50501.7,50743.1,-1.1,"[40.712787, -74.007551]",28309,NaN,2016-06-16,40.712787,-74.007551
289356,611601462,31.4,58.0,50525.6,50766.7,-0.4,"[40.712575, -74.007592]",28323,NaN,2016-06-16,40.712575,-74.007592
289357,611601462,31.2,57.0,50532.8,50773.4,-1.8,"[40.71254, -74.007664]",28331,NaN,2016-06-16,40.712540,-74.007664
289358,611601462,31.4,57.0,50534.0,50774.6,0.0,"[40.712546, -74.007677]",28334,NaN,2016-06-16,40.712546,-74.007677
289359,611601462,31.4,57.0,50535.1,50775.8,2.8,"[40.712552, -74.007667]",28336,NaN,2016-06-16,40.712552,-74.007667
289360,611601462,31.4,57.0,50539.6,50780.6,1.4,"[40.712522, -74.007631]",28340,NaN,2016-06-16,40.712522,-74.007631
289361,611601462,32.0,0.0,50561.8,50803.8,1.1,"[40.71238, -74.007447]",28355,NaN,2016-06-16,40.712380,-74.007447
289362,611601462,32.0,54.0,50577.8,50820.6,1.2,"[40.712304, -74.007286]",28366,NaN,2016-06-16,40.712304,-74.007286
289363,611601462,32.0,0.0,50589.0,50831.8,0.0,"[40.712332, -74.007159]",28388,NaN,2016-06-16,40.712332,-74.007159
289364,611601462,32.0,0.0,50591.7,50834.5,0.5,"[40.712325, -74.007128]",28390,NaN,2016-06-16,40.712325,-74.007128
289365,611601462,32.0,0.0,50594.5,50837.5,1.9,"[40.712329, -74.007095]",28392,NaN,2016-06-16,40.712329,-74.007095
289366,611601462,32.2,60.0,50614.6,50859.0,1.7,"[40.712381, -74.006867]",28408,NaN,2016-06-16,40.712381,-74.006867
289367,611601462,32.6,54.0,50620.4,50865.3,1.9,"[40.712397, -74.006801]",28413,NaN,2016-06-16,40.712397,-74.006801
289368,611601462,32.6,60.0,50627.8,50874.2,4.5,"[40.712401, -74.006714]",28419,NaN,2016-06-16,40.712401,-74.006714
289369,611601462,32.8,0.0,50636.8,50884.7,3.7,"[40.712367, -74.006617]",28430,NaN,2016-06-16,40.712367,-74.006617
289370,611601462,33.2,0.0,50636.8,50884.7,6.7,"[40.712367, -74.006617]",28435,NaN,2016-06-16,40.712367,-74.006617

In [26]:
jeremy_run = jeremy_run.drop('latlng', axis =1)
jeremy_run

,activity_id,altitude,cadence,distance,grade_adjusted_distance,grade_smooth,time,timer_time,date,lat,long
3453,549746013,10.2,0.0,0.0,0.0,-0.7,0,NaN,2016-04-18,34.007696,-118.499512
3454,549746013,9.6,0.0,4.8,4.8,0.0,3,NaN,2016-04-18,34.007726,-118.499474
3455,549746013,10.0,80.0,26.7,26.7,0.0,11,NaN,2016-04-18,34.007877,-118.499323
3456,549746013,10.2,78.0,47.8,48.6,0.9,19,NaN,2016-04-18,34.008013,-118.499163
3457,549746013,10.2,79.0,69.7,70.7,0.2,27,NaN,2016-04-18,34.008149,-118.498991
3458,549746013,10.4,80.0,91.7,93.1,0.4,35,NaN,2016-04-18,34.008288,-118.498822
3459,549746013,10.2,79.0,114.5,116.1,0.2,43,NaN,2016-04-18,34.008432,-118.498647
3460,549746013,10.6,79.0,137.2,138.8,0.0,51,NaN,2016-04-18,34.008581,-118.498479
3461,549746013,10.4,80.0,159.3,160.9,0.0,59,NaN,2016-04-18,34.008714,-118.498301
3462,549746013,10.4,79.0,181.9,182.9,-0.7,67,NaN,2016-04-18,34.008851,-118.498120
3463,549746013,10.2,79.0,202.7,203.3,-0.5,75,NaN,2016-04-18,34.008985,-118.497963
3464,549746013,10.0,78.0,225.0,225.4,-0.2,83,NaN,2016-04-18,34.009124,-118.497788
3465,549746013,10.0,79.0,247.0,247.4,0.0,91,NaN,2016-04-18,34.009263,-118.497619
3466,549746013,10.2,79.0,267.2,266.7,-1.1,98,NaN,2016-04-18,34.009400,-118.497476
3467,549746013,10.2,78.0,288.5,284.3,-4.9,106,NaN,2016-04-18,34.009546,-118.497326
3468,549746013,9.2,60.0,296.8,290.7,-6.8,123,NaN,2016-04-18,34.009618,-118.497302
3469,549746013,7.4,60.0,299.6,292.6,-10.9,126,NaN,2016-04-18,34.009639,-118.497319
3470,549746013,6.6,80.0,320.3,309.8,-4.7,136,NaN,2016-04-18,34.009598,-118.497538
3471,549746013,6.4,79.0,323.5,313.0,-0.3,137,NaN,2016-04-18,34.009580,-118.497564
3472,549746013,7.0,78.0,343.9,333.6,0.3,145,NaN,2016-04-18,34.009468,-118.497740
3473,549746013,7.2,80.0,366.1,356.3,0.5,153,NaN,2016-04-18,34.009349,-118.497932
3474,549746013,6.8,80.0,387.1,376.0,-1.5,161,NaN,2016-04-18,34.009224,-118.498103
3475,549746013,6.8,80.0,408.7,395.1,-3.1,170,NaN,2016-04-18,34.009098,-118.498281
3476,549746013,5.8,70.0,423.9,409.0,-2.3,180,NaN,2016-04-18,34.009025,-118.498420
3477,549746013,5.4,70.0,424.9,410.0,-0.9,184,NaN,2016-04-18,34.009033,-118.498426
3478,549746013,5.8,0.0,430.8,416.5,2.6,237,NaN,2016-04-18,34.009085,-118.498436
3479,549746013,6.4,80.0,451.9,439.4,2.0,249,NaN,2016-04-18,34.009189,-118.498245
3480,549746013,6.6,80.0,454.8,442.4,0.9,250,NaN,2016-04-18,34.009204,-118.498219
3481,549746013,6.4,80.0,475.1,463.2,0.6,258,NaN,2016-04-18,34.009305,-118.498036
3482,549746013,6.4,81.0,496.2,484.3,0.0,266,NaN,2016-04-18,34.009402,-118.497839
...,...,...,...,...,...,...,...,...,...,...,...
289341,611601462,30.2,0.0,50299.9,50536.5,2.8,28148,NaN,2016-06-16,40.714136,-74.006251
289342,611601462,30.4,60.0,50303.2,50540.2,2.6,28172,NaN,2016-06-16,40.714154,-74.006219
289343,611601462,31.2,55.0,50323.1,50561.7,1.9,28196,NaN,2016-06-16,40.714002,-74.006343
289344,611601462,31.4,57.0,50343.3,50582.9,1.2,28205,NaN,2016-06-16,40.713833,-74.006431
289345,611601462,31.4,78.0,50363.8,50603.9,0.5,28214,NaN,2016-06-16,40.713674,-74.006552
289346,611601462,31.4,60.0,50384.0,50624.7,0.8,28225,NaN,2016-06-16,40.713517,-74.006673
289347,611601462,31.6,60.0,50399.0,50640.2,0.8,28236,NaN,2016-06-16,40.713404,-74.006771
289348,611601462,32.0,60.0,50419.9,50661.5,0.5,28247,NaN,2016-06-16,40.713246,-74.006903
289349,611601462,32.0,60.0,50442.1,50684.3,0.6,28263,NaN,2016-06-16,40.713094,-74.007074
289350,611601462,31.8,60.0,50462.3,50705.1,0.8,28276,NaN,2016-06-16,40.712931,-74.007180
289351,611601462,32.0,0.0,50468.9,50711.6,-0.6,28281,NaN,2016-06-16,40.712884,-74.007227
289352,611601462,32.4,56.0,50472.4,50714.9,-1.1,28285,NaN,2016-06-16,40.712912,-74.007246
289353,611601462,31.8,0.0,50478.4,50720.9,0.0,28292,NaN,2016-06-16,40.712892,-74.007312
289354,611601462,31.6,0.0,50480.6,50722.9,-1.9,28294,NaN,2016-06-16,40.712884,-74.007336
289355,611601462,32.0,58.0,50501.7,50743.1,-1.1,28309,NaN,2016-06-16,40.712787,-74.007551
289356,611601462,31.4,58.0,50525.6,50766.7,-0.4,28323,NaN,2016-06-16,40.712575,-74.007592
289357,611601462,31.2,57.0,50532.8,50773.4,-1.8,28331,NaN,2016-06-16,40.712540,-74.007664
289358,611601462,31.4,57.0,50534.0,50774.6,0.0,28334,NaN,2016-06-16,40.712546,-74.007677
289359,611601462,31.4,57.0,50535.1,50775.8,2.8,28336,NaN,2016-06-16,40.712552,-74.007667
289360,611601462,31.4,57.0,50539.6,50780.6,1.4,28340,NaN,2016-06-16,40.712522,-74.007631
289361,611601462,32.0,0.0,50561.8,50803.8,1.1,28355,NaN,2016-06-16,40.712380,-74.007447
289362,611601462,32.0,54.0,50577.8,50820.6,1.2,28366,NaN,2016-06-16,40.712304,-74.007286
289363,611601462,32.0,0.0,50589.0,50831.8,0.0,28388,NaN,2016-06-16,40.712332,-74.007159
289364,611601462,32.0,0.0,50591.7,50834.5,0.5,28390,NaN,2016-06-16,40.712325,-74.007128
289365,611601462,32.0,0.0,50594.5,50837.5,1.9,28392,NaN,2016-06-16,40.712329,-74.007095
289366,611601462,32.2,60.0,50614.6,50859.0,1.7,28408,NaN,2016-06-16,40.712381,-74.006867
289367,611601462,32.6,54.0,50620.4,50865.3,1.9,28413,NaN,2016-06-16,40.712397,-74.006801
289368,611601462,32.6,60.0,50627.8,50874.2,4.5,28419,NaN,2016-06-16,40.712401,-74.006714
289369,611601462,32.8,0.0,50636.8,50884.7,3.7,28430,NaN,2016-06-16,40.712367,-74.006617
289370,611601462,33.2,0.0,50636.8,50884.7,6.7,28435,NaN,2016-06-16,40.712367,-74.006617

In [27]:
jeremy_run['runner'] = 'jeremy'
jeremy_run

,activity_id,altitude,cadence,distance,grade_adjusted_distance,grade_smooth,time,timer_time,date,lat,long,runner
3453,549746013,10.2,0.0,0.0,0.0,-0.7,0,NaN,2016-04-18,34.007696,-118.499512,jeremy
3454,549746013,9.6,0.0,4.8,4.8,0.0,3,NaN,2016-04-18,34.007726,-118.499474,jeremy
3455,549746013,10.0,80.0,26.7,26.7,0.0,11,NaN,2016-04-18,34.007877,-118.499323,jeremy
3456,549746013,10.2,78.0,47.8,48.6,0.9,19,NaN,2016-04-18,34.008013,-118.499163,jeremy
3457,549746013,10.2,79.0,69.7,70.7,0.2,27,NaN,2016-04-18,34.008149,-118.498991,jeremy
3458,549746013,10.4,80.0,91.7,93.1,0.4,35,NaN,2016-04-18,34.008288,-118.498822,jeremy
3459,549746013,10.2,79.0,114.5,116.1,0.2,43,NaN,2016-04-18,34.008432,-118.498647,jeremy
3460,549746013,10.6,79.0,137.2,138.8,0.0,51,NaN,2016-04-18,34.008581,-118.498479,jeremy
3461,549746013,10.4,80.0,159.3,160.9,0.0,59,NaN,2016-04-18,34.008714,-118.498301,jeremy
3462,549746013,10.4,79.0,181.9,182.9,-0.7,67,NaN,2016-04-18,34.008851,-118.498120,jeremy
3463,549746013,10.2,79.0,202.7,203.3,-0.5,75,NaN,2016-04-18,34.008985,-118.497963,jeremy
3464,549746013,10.0,78.0,225.0,225.4,-0.2,83,NaN,2016-04-18,34.009124,-118.497788,jeremy
3465,549746013,10.0,79.0,247.0,247.4,0.0,91,NaN,2016-04-18,34.009263,-118.497619,jeremy
3466,549746013,10.2,79.0,267.2,266.7,-1.1,98,NaN,2016-04-18,34.009400,-118.497476,jeremy
3467,549746013,10.2,78.0,288.5,284.3,-4.9,106,NaN,2016-04-18,34.009546,-118.497326,jeremy
3468,549746013,9.2,60.0,296.8,290.7,-6.8,123,NaN,2016-04-18,34.009618,-118.497302,jeremy
3469,549746013,7.4,60.0,299.6,292.6,-10.9,126,NaN,2016-04-18,34.009639,-118.497319,jeremy
3470,549746013,6.6,80.0,320.3,309.8,-4.7,136,NaN,2016-04-18,34.009598,-118.497538,jeremy
3471,549746013,6.4,79.0,323.5,313.0,-0.3,137,NaN,2016-04-18,34.009580,-118.497564,jeremy
3472,549746013,7.0,78.0,343.9,333.6,0.3,145,NaN,2016-04-18,34.009468,-118.497740,jeremy
3473,549746013,7.2,80.0,366.1,356.3,0.5,153,NaN,2016-04-18,34.009349,-118.497932,jeremy
3474,549746013,6.8,80.0,387.1,376.0,-1.5,161,NaN,2016-04-18,34.009224,-118.498103,jeremy
3475,549746013,6.8,80.0,408.7,395.1,-3.1,170,NaN,2016-04-18,34.009098,-118.498281,jeremy
3476,549746013,5.8,70.0,423.9,409.0,-2.3,180,NaN,2016-04-18,34.009025,-118.498420,jeremy
3477,549746013,5.4,70.0,424.9,410.0,-0.9,184,NaN,2016-04-18,34.009033,-118.498426,jeremy
3478,549746013,5.8,0.0,430.8,416.5,2.6,237,NaN,2016-04-18,34.009085,-118.498436,jeremy
3479,549746013,6.4,80.0,451.9,439.4,2.0,249,NaN,2016-04-18,34.009189,-118.498245,jeremy
3480,549746013,6.6,80.0,454.8,442.4,0.9,250,NaN,2016-04-18,34.009204,-118.498219,jeremy
3481,549746013,6.4,80.0,475.1,463.2,0.6,258,NaN,2016-04-18,34.009305,-118.498036,jeremy
3482,549746013,6.4,81.0,496.2,484.3,0.0,266,NaN,2016-04-18,34.009402,-118.497839,jeremy
...,...,...,...,...,...,...,...,...,...,...,...,...
289341,611601462,30.2,0.0,50299.9,50536.5,2.8,28148,NaN,2016-06-16,40.714136,-74.006251,jeremy
289342,611601462,30.4,60.0,50303.2,50540.2,2.6,28172,NaN,2016-06-16,40.714154,-74.006219,jeremy
289343,611601462,31.2,55.0,50323.1,50561.7,1.9,28196,NaN,2016-06-16,40.714002,-74.006343,jeremy
289344,611601462,31.4,57.0,50343.3,50582.9,1.2,28205,NaN,2016-06-16,40.713833,-74.006431,jeremy
289345,611601462,31.4,78.0,50363.8,50603.9,0.5,28214,NaN,2016-06-16,40.713674,-74.006552,jeremy
289346,611601462,31.4,60.0,50384.0,50624.7,0.8,28225,NaN,2016-06-16,40.713517,-74.006673,jeremy
289347,611601462,31.6,60.0,50399.0,50640.2,0.8,28236,NaN,2016-06-16,40.713404,-74.006771,jeremy
289348,611601462,32.0,60.0,50419.9,50661.5,0.5,28247,NaN,2016-06-16,40.713246,-74.006903,jeremy
289349,611601462,32.0,60.0,50442.1,50684.3,0.6,28263,NaN,2016-06-16,40.713094,-74.007074,jeremy
289350,611601462,31.8,60.0,50462.3,50705.1,0.8,28276,NaN,2016-06-16,40.712931,-74.007180,jeremy
289351,611601462,32.0,0.0,50468.9,50711.6,-0.6,28281,NaN,2016-06-16,40.712884,-74.007227,jeremy
289352,611601462,32.4,56.0,50472.4,50714.9,-1.1,28285,NaN,2016-06-16,40.712912,-74.007246,jeremy
289353,611601462,31.8,0.0,50478.4,50720.9,0.0,28292,NaN,2016-06-16,40.712892,-74.007312,jeremy
289354,611601462,31.6,0.0,50480.6,50722.9,-1.9,28294,NaN,2016-06-16,40.712884,-74.007336,jeremy
289355,611601462,32.0,58.0,50501.7,50743.1,-1.1,28309,NaN,2016-06-16,40.712787,-74.007551,jeremy
289356,611601462,31.4,58.0,50525.6,50766.7,-0.4,28323,NaN,2016-06-16,40.712575,-74.007592,jeremy
289357,611601462,31.2,57.0,50532.8,50773.4,-1.8,28331,NaN,2016-06-16,40.712540,-74.007664,jeremy
289358,611601462,31.4,57.0,50534.0,50774.6,0.0,28334,NaN,2016-06-16,40.712546,-74.007677,jeremy
289359,611601462,31.4,57.0,50535.1,50775.8,2.8,28336,NaN,2016-06-16,40.712552,-74.007667,jeremy
289360,611601462,31.4,57.0,50539.6,50780.6,1.4,28340,NaN,2016-06-16,40.712522,-74.007631,jeremy
289361,611601462,32.0,0.0,50561.8,50803.8,1.1,28355,NaN,2016-06-16,40.712380,-74.007447,jeremy
289362,611601462,32.0,54.0,50577.8,50820.6,1.2,28366,NaN,2016-06-16,40.712304,-74.007286,jeremy
289363,611601462,32.0,0.0,50589.0,50831.8,0.0,28388,NaN,2016-06-16,40.712332,-74.007159,jeremy
289364,611601462,32.0,0.0,50591.7,50834.5,0.5,28390,NaN,2016-06-16,40.712325,-74.007128,jeremy
289365,611601462,32.0,0.0,50594.5,50837.5,1.9,28392,NaN,2016-06-16,40.712329,-74.007095,jeremy
289366,611601462,32.2,60.0,50614.6,50859.0,1.7,28408,NaN,2016-06-16,40.712381,-74.006867,jeremy
289367,611601462,32.6,54.0,50620.4,50865.3,1.9,28413,NaN,2016-06-16,40.712397,-74.006801,jeremy
289368,611601462,32.6,60.0,50627.8,50874.2,4.5,28419,NaN,2016-06-16,40.712401,-74.006714,jeremy
289369,611601462,32.8,0.0,50636.8,50884.7,3.7,28430,NaN,2016-06-16,40.712367,-74.006617,jeremy
289370,611601462,33.2,0.0,50636.8,50884.7,6.7,28435,NaN,2016-06-16,40.712367,-74.006617,jeremy

In [28]:
jeremy_run['distance'] = jeremy_run['distance'].map(lambda x: (x/1609.344))
jeremy_run['time'] = jeremy_run['time'].map(lambda x: (x/60))
jeremy_run.head(500)

,activity_id,altitude,cadence,distance,grade_adjusted_distance,grade_smooth,time,timer_time,date,lat,long,runner
3453,549746013,10.2,0.0,0.000000,0.0,-0.7,0.000000,NaN,2016-04-18,34.007696,-118.499512,jeremy
3454,549746013,9.6,0.0,0.002983,4.8,0.0,0.050000,NaN,2016-04-18,34.007726,-118.499474,jeremy
3455,549746013,10.0,80.0,0.016591,26.7,0.0,0.183333,NaN,2016-04-18,34.007877,-118.499323,jeremy
3456,549746013,10.2,78.0,0.029702,48.6,0.9,0.316667,NaN,2016-04-18,34.008013,-118.499163,jeremy
3457,549746013,10.2,79.0,0.043310,70.7,0.2,0.450000,NaN,2016-04-18,34.008149,-118.498991,jeremy
3458,549746013,10.4,80.0,0.056980,93.1,0.4,0.583333,NaN,2016-04-18,34.008288,-118.498822,jeremy
3459,549746013,10.2,79.0,0.071147,116.1,0.2,0.716667,NaN,2016-04-18,34.008432,-118.498647,jeremy
3460,549746013,10.6,79.0,0.085252,138.8,0.0,0.850000,NaN,2016-04-18,34.008581,-118.498479,jeremy
3461,549746013,10.4,80.0,0.098984,160.9,0.0,0.983333,NaN,2016-04-18,34.008714,-118.498301,jeremy
3462,549746013,10.4,79.0,0.113027,182.9,-0.7,1.116667,NaN,2016-04-18,34.008851,-118.498120,jeremy
3463,549746013,10.2,79.0,0.125952,203.3,-0.5,1.250000,NaN,2016-04-18,34.008985,-118.497963,jeremy
3464,549746013,10.0,78.0,0.139809,225.4,-0.2,1.383333,NaN,2016-04-18,34.009124,-118.497788,jeremy
3465,549746013,10.0,79.0,0.153479,247.4,0.0,1.516667,NaN,2016-04-18,34.009263,-118.497619,jeremy
3466,549746013,10.2,79.0,0.166030,266.7,-1.1,1.633333,NaN,2016-04-18,34.009400,-118.497476,jeremy
3467,549746013,10.2,78.0,0.179266,284.3,-4.9,1.766667,NaN,2016-04-18,34.009546,-118.497326,jeremy
3468,549746013,9.2,60.0,0.184423,290.7,-6.8,2.050000,NaN,2016-04-18,34.009618,-118.497302,jeremy
3469,549746013,7.4,60.0,0.186163,292.6,-10.9,2.100000,NaN,2016-04-18,34.009639,-118.497319,jeremy
3470,549746013,6.6,80.0,0.199025,309.8,-4.7,2.266667,NaN,2016-04-18,34.009598,-118.497538,jeremy
3471,549746013,6.4,79.0,0.201014,313.0,-0.3,2.283333,NaN,2016-04-18,34.009580,-118.497564,jeremy
3472,549746013,7.0,78.0,0.213690,333.6,0.3,2.416667,NaN,2016-04-18,34.009468,-118.497740,jeremy
3473,549746013,7.2,80.0,0.227484,356.3,0.5,2.550000,NaN,2016-04-18,34.009349,-118.497932,jeremy
3474,549746013,6.8,80.0,0.240533,376.0,-1.5,2.683333,NaN,2016-04-18,34.009224,-118.498103,jeremy
3475,549746013,6.8,80.0,0.253954,395.1,-3.1,2.833333,NaN,2016-04-18,34.009098,-118.498281,jeremy
3476,549746013,5.8,70.0,0.263399,409.0,-2.3,3.000000,NaN,2016-04-18,34.009025,-118.498420,jeremy
3477,549746013,5.4,70.0,0.264021,410.0,-0.9,3.066667,NaN,2016-04-18,34.009033,-118.498426,jeremy
3478,549746013,5.8,0.0,0.267687,416.5,2.6,3.950000,NaN,2016-04-18,34.009085,-118.498436,jeremy
3479,549746013,6.4,80.0,0.280798,439.4,2.0,4.150000,NaN,2016-04-18,34.009189,-118.498245,jeremy
3480,549746013,6.6,80.0,0.282600,442.4,0.9,4.166667,NaN,2016-04-18,34.009204,-118.498219,jeremy
3481,549746013,6.4,80.0,0.295213,463.2,0.6,4.300000,NaN,2016-04-18,34.009305,-118.498036,jeremy
3482,549746013,6.4,81.0,0.308324,484.3,0.0,4.433333,NaN,2016-04-18,34.009402,-118.497839,jeremy
...,...,...,...,...,...,...,...,...,...,...,...,...
3923,549746013,54.0,81.0,5.362309,8843.4,-0.9,60.333333,NaN,2016-04-18,34.041532,-118.426189,jeremy
3924,549746013,54.0,82.0,5.375358,8863.7,-0.9,60.450000,NaN,2016-04-18,34.041607,-118.425980,jeremy
3925,549746013,53.8,81.0,5.389898,8887.1,0.0,60.583333,NaN,2016-04-18,34.041712,-118.425760,jeremy
3926,549746013,53.8,80.0,5.402947,8907.7,-0.5,60.700000,NaN,2016-04-18,34.041762,-118.425541,jeremy
3927,549746013,54.0,82.0,5.416741,8929.4,-0.6,60.850000,NaN,2016-04-18,34.041847,-118.425323,jeremy
3928,549746013,53.6,81.0,5.429479,8949.6,-0.3,60.983333,NaN,2016-04-18,34.041963,-118.425150,jeremy
3929,549746013,53.4,82.0,5.433518,8956.4,0.8,61.016667,NaN,2016-04-18,34.041981,-118.425083,jeremy
3930,549746013,53.6,83.0,5.446691,8979.3,2.0,61.116667,NaN,2016-04-18,34.042068,-118.424879,jeremy
3931,549746013,54.6,81.0,5.460796,9004.3,2.3,61.233333,NaN,2016-04-18,34.042170,-118.424665,jeremy
3932,549746013,55.0,80.0,5.473721,9027.4,2.6,61.366667,NaN,2016-04-18,34.042274,-118.424478,jeremy
3933,549746013,55.4,81.0,5.487515,9050.8,1.3,61.516667,NaN,2016-04-18,34.042397,-118.424288,jeremy
3934,549746013,55.6,80.0,5.494599,9062.9,1.3,61.583333,NaN,2016-04-18,34.042466,-118.424197,jeremy
3935,549746013,55.6,82.0,5.507772,9085.0,1.1,61.700000,NaN,2016-04-18,34.042590,-118.424022,jeremy
3936,549746013,56.0,80.0,5.520634,9106.9,1.3,61.816667,NaN,2016-04-18,34.042703,-118.423844,jeremy
3937,549746013,56.2,80.0,5.533870,9129.9,1.9,61.950000,NaN,2016-04-18,34.042819,-118.423661,jeremy
3938,549746013,56.6,80.0,5.540767,9141.7,1.6,62.016667,NaN,2016-04-18,34.042868,-118.423556,jeremy
3939,549746013,57.0,81.0,5.554437,9165.2,1.6,62.150000,NaN,2016-04-18,34.042973,-118.423354,jeremy
3940,549746013,57.2,81.0,5.567299,9187.3,1.6,62.283333,NaN,2016-04-18,34.043069,-118.423162,jeremy
3941,549746013,57.4,80.0,5.580721,9210.6,1.9,62.416667,NaN,2016-04-18,34.043162,-118.422956,jeremy
3942,549746013,58.0,80.0,5.594329,9234.6,2.2,62.550000,NaN,2016-04-18,34.043285,-118.422771,jeremy
3943,549746013,58.6,82.0,5.606819,9256.3,2.0,62.666667,NaN,2016-04-18,34.043393,-118.422596,jeremy
3944,549746013,58.8,82.0,5.612660,9266.6,2.0,62.716667,NaN,2016-04-18,34.043436,-118.422508,jeremy
3945,549746013,58.8,82.0,5.625273,9288.1,1.4,62.833333,NaN,2016-04-18,34.043533,-118.422322,jeremy
3946,549746013,59.4,81.0,5.637701,9309.2,1.4,62.950000,NaN,2016-04-18,34.043631,-118.422140,jeremy
3947,549746013,59.6,81.0,5.650190,9331.0,1.9,63.066667,NaN,2016-04-18,34.043742,-118.421968,jeremy
3948,549746013,59.8,80.0,5.657025,9342.7,1.6,63.116667,NaN,2016-04-18,34.043791,-118.421865,jeremy
3949,549746013,60.2,82.0,5.670261,9365.0,1.1,63.266667,NaN,2016-04-18,34.043905,-118.421679,jeremy
3950,549746013,60.6,81.0,5.683620,9387.7,1.4,63.400000,NaN,2016-04-18,34.044007,-118.421481,jeremy
3951,549746013,60.4,81.0,5.697415,9410.8,0.9,63.550000,NaN,2016-04-18,34.044131,-118.421292,jeremy
3952,549746013,61.0,82.0,5.710215,9432.0,0.7,63.666667,NaN,2016-04-18,34.044220,-118.421096,jeremy

In [29]:
jeremy_run.to_csv("jeremy_run.csv")