In [1]:
import requests
from lxml import html
import pandas as pd
from bs4 import BeautifulSoup
import re
import sys
from datetime import datetime
import time
import numpy as np
import json
from config import *

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException


import time
import json
import re
from tqdm import tqdm

In [ ]:
#strava

# stats= https://www.strava.com/activities/586018101/streams?stream_types%5B%5D=timer_time&stream_types%5B%5D=altitude&stream_types%5B%5D=heartrate&stream_types%5B%5D=cadence&stream_types%5B%5D=temp&stream_types%5B%5D=distance&stream_types%5B%5D=grade_smooth&stream_types%5B%5D=time&stream_types%5B%5D=grade_adjusted_distance&_=1537842990620
# latlng = https://www.strava.com/activities/586018101/streams?stream_types%5B%5D=timer_time&stream_types%5B%5D=latlng&_=1537842990619

pete = "https://www.strava.com/athletes/16102568/training/log?feature=sidebar-progress-goals-v2"
adam= "https://www.strava.com/pros/11620352#interval?interval=201607&interval_type=week&chart_type=miles&year_offset=2"
jermey = "https://www.strava.com/athletes/1150260#graph_date_range?chart_type=miles&interval_type=week&interval=201640&year_offset=2"
jason = "https://www.strava.com/athletes/13823509#interval?interval=201621&interval_type=week&chart_type=miles&year_offset=2"

In [2]:
#pull date, distance, time, pace
## April

activities = []
links = []
dates = []
html_text = []

        #load webpage
browser = webdriver.Chrome() 
browser.get("https://www.strava.com/login") #navigate to the page
browser.implicitly_wait(5)

            # login = browser.find_element_by_xpath('//*[@id="global-nav"]/div/ul/li[5]/a').click()

#sign-in
username = browser.find_element_by_id('email')
username.clear()
username.send_keys(username_c)

password = browser.find_element_by_id('password')
password.clear()
password.send_keys(strava_pw)

browser.find_element_by_id("login-button").click()

#search
browser.find_element_by_xpath('//*[@id="global-search-field"]').send_keys('adam kimble')
browser.implicitly_wait(2)
browser.find_element_by_xpath('//*[@id="global-search-button"]').click()
browser.implicitly_wait(2)
browser.find_element_by_xpath('/html/body/div[1]/div[3]/div/ul/li[1]/div[1]/div[2]/h4/a').click()


#change year of data
browser.get('https://www.strava.com/pros/11620352#interval_type?chart_type=miles&interval_type=month&interval=201610&year_offset=2')
time.sleep(2)
# browser.find_element_by_xpath('//*[@id="interval-graph-controls"]/ul/li[2]/ul/li[2]/a').click()

#get stats per month
for x in range(2,5):
    time.sleep(2)
# browser.find_element_by_xpath('//*[@id="interval-201603"]/div/a').click()
    browser.find_element_by_xpath(f'//*[@id="interval-20160{str(x)}"]/div/a').click()

    #activity links
    time.sleep(4)

    feed = browser.find_element_by_class_name('feed')
    webdriver.ActionChains(browser).move_to_element(feed)

    html = feed.get_attribute('innerHTML')
    
    html_text.append(html)

In [ ]:
html_text

In [3]:
#pull name, date, activity stats for each entry on page
#skip if all values aren't present

activity_details = []

for html in html_text:
    bs = BeautifulSoup(html, 'html.parser')
    container = bs.find_all('div', attrs={"class":"entry-container"})
    for a in container:
        try:
            name = a.find_all('a', attrs={'class':"entry-athlete"})[0].get_text().strip('\n').split('\n')[0]
            date = a.find_all('time', attrs={'class':"timestamp"})[0].get_text().strip('\n')
            dist = a.find_all('li', attrs={'title':"Distance"})[0].get_text()
            pace = a.find_all('li', attrs={'title':"Pace"})[0].get_text()
            dur = a.find_all('li', attrs={'title':"Time"})[0].get_text()
            activity_details.append([name, date, dist, pace, dur])
        except:
            pass
activity_details

[['Adam Kimble',
  'February 29, 2016 at 4:03 AM',
  '47.39 mi',
  '13:44 /mi',
  '10h 51m'],
 ['Adam Kimble',
  'February 28, 2016 at 4:25 AM',
  '38.32 mi',
  '15:36 /mi',
  '9h 57m'],
 ['Adam Kimble',
  'February 27, 2016 at 4:04 AM',
  '50.09 mi',
  '15:26 /mi',
  '12h 52m'],
 ['Adam Kimble',
  'February 26, 2016 at 4:01 AM',
  '41.20 mi',
  '14:43 /mi',
  '10h 6m'],
 ['Adam Kimble',
  'February 22, 2016 at 4:01 AM',
  '39.77 mi',
  '16:50 /mi',
  '11h 9m'],
 ['Adam Kimble',
  'February 21, 2016 at 6:35 PM',
  '6.94 mi',
  '16:42 /mi',
  '1h 56m'],
 ['Adam Kimble',
  'February 21, 2016 at 4:14 AM',
  '23.11 mi',
  '19:03 /mi',
  '7h 20m'],
 ['Adam Kimble',
  'February 20, 2016 at 2:59 PM',
  '15.62 mi',
  '17:22 /mi',
  '4h 31m'],
 ['Adam Kimble',
  'February 20, 2016 at 4:07 AM',
  '24.55 mi',
  '18:41 /mi',
  '7h 38m'],
 ['Adam Kimble',
  'February 19, 2016 at 5:46 PM',
  '7.15 mi',
  '23:11 /mi',
  '2h 45m'],
 ['Adam Kimble',
  'February 19, 2016 at 4:16 AM',
  '41.47 mi',
  '14:29 /mi',
  '10h 0m'],
 ['Adam Kimble',
  'February 18, 2016 at 4:20 AM',
  '36.26 mi',
  '15:25 /mi',
  '9h 18m'],
 ['Adam Kimble',
  'February 17, 2016 at 2:26 PM',
  '22.23 mi',
  '15:26 /mi',
  '5h 43m'],
 ['Adam Kimble',
  'February 17, 2016 at 4:06 AM',
  '36.34 mi',
  '12:23 /mi',
  '7h 30m'],
 ['Adam Kimble',
  'February 16, 2016 at 12:48 PM',
  '17.51 mi',
  '17:47 /mi',
  '5h 11m'],
 ['Adam Kimble',
  'February 16, 2016 at 12:14 PM',
  '1.62 mi',
  '14:55 /mi',
  '24m 17s'],
 ['Adam Kimble',
  'February 15, 2016 at 4:00 AM',
  '55.62 mi',
  '14:13 /mi',
  '13h 10m'],
 ['Adam Kimble',
  'February 11, 2016 at 9:32 AM',
  '2.21 mi',
  '8:42 /mi',
  '19m 15s'],
 ['Adam Kimble',
  'February 8, 2016 at 6:36 AM',
  '2.77 mi',
  '9:47 /mi',
  '27m 6s'],
 ['Adam Kimble',
  'February 6, 2016 at 12:18 PM',
  '10.25 mi',
  '8:18 /mi',
  '1h 25m'],
 ['Adam Kimble',
  'February 5, 2016 at 9:23 AM',
  '3.38 mi',
  '8:44 /mi',
  '29m 36s'],
 ['Adam Kimble',
  'February 4, 2016 at 6:57 PM',
  '4.08 mi',
  '8:45 /mi',
  '35m 44s'],
 ['Adam Kimble',
  'February 3, 2016 at 4:25 PM',
  '8.19 mi',
  '8:18 /mi',
  '1h 8m'],
 ['Adam Kimble',
  'February 2, 2016 at 7:30 AM',
  '2.05 mi',
  '9:17 /mi',
  '19m 1s'],
 ['Adam Kimble',
  'March 31, 2016 at 12:28 PM',
  '35.47 mi',
  '14:10 /mi',
  '8h 22m'],
 ['Adam Kimble',
  'March 31, 2016 at 5:10 AM',
  '16.13 mi',
  '20:18 /mi',
  '5h 27m'],
 ['Adam Kimble',
  'March 30, 2016 at 10:59 PM',
  '0.80 mi',
  '16:52 /mi',
  '13m 29s'],
 ['Adam Kimble',
  'March 30, 2016 at 10:25 PM',
  '2.00 mi',
  '16:46 /mi',
  '33m 36s'],
 ['Adam Kimble',
  'March 30, 2016 at 11:40 AM',
  '30.74 mi',
  '20:57 /mi',
  '10h 44m'],
 ['Adam Kimble',
  'March 30, 2016 at 5:08 AM',
  '17.24 mi',
  '16:28 /mi',
  '4h 43m'],
 ['Adam Kimble',
  'March 29, 2016 at 5:05 AM',
  '46.56 mi',
  '17:04 /mi',
  '13h 14m'],
 ['Adam Kimble',
  'March 28, 2016 at 5:52 PM',
  '5.90 mi',
  '17:18 /mi',
  '1h 42m'],
 ['Adam Kimble',
  'March 28, 2016 at 5:11 AM',
  '22.76 mi',
  '17:03 /mi',
  '6h 28m'],
 ['Adam Kimble',
  'March 27, 2016 at 11:33 AM',
  '33.60 mi',
  '16:34 /mi',
  '9h 16m'],
 ['Adam Kimble',
  'March 27, 2016 at 5:15 AM',
  '11.44 mi',
  '16:39 /mi',
  '3h 10m'],
 ['Adam Kimble',
  'March 26, 2016 at 5:21 AM',
  '41.08 mi',
  '17:02 /mi',
  '11h 39m'],
 ['Adam Kimble',
  'March 25, 2016 at 2:01 PM',
  '10.56 mi',
  '17:14 /mi',
  '3h 2m'],
 ['Adam Kimble',
  'March 25, 2016 at 5:18 AM',
  '15.45 mi',
  '18:35 /mi',
  '4h 47m'],
 ['Adam Kimble',
  'March 24, 2016 at 5:17 AM',
  '43.53 mi',
  '16:16 /mi',
  '11h 48m'],
 ['Adam Kimble',
  'March 23, 2016 at 5:17 AM',
  '55.06 mi',
  '12:28 /mi',
  '11h 26m'],
 ['Adam Kimble',
  'March 22, 2016 at 5:06 AM',
  '51.51 mi',
  '11:45 /mi',
  '10h 5m'],
 ['Adam Kimble',
  'March 21, 2016 at 5:17 AM',
  '48.55 mi',
  '11:52 /mi',
  '9h 35m'],
 ['Adam Kimble',
  'March 20, 2016 at 1:05 PM',
  '23.39 mi',
  '11:58 /mi',
  '4h 39m'],
 ['Adam Kimble',
  'March 20, 2016 at 9:41 AM',
  '10.97 mi',
  '12:20 /mi',
  '2h 15m'],
 ['Adam Kimble',
  'March 20, 2016 at 5:11 AM',
  '9.93 mi',
  '14:25 /mi',
  '2h 23m'],
 ['Adam Kimble',
  'March 19, 2016 at 5:25 AM',
  '50.14 mi',
  '14:28 /mi',
  '12h 5m'],
 ['Adam Kimble',
  'March 18, 2016 at 5:13 AM',
  '50.11 mi',
  '12:54 /mi',
  '10h 46m'],
 ['Adam Kimble',
  'March 17, 2016 at 5:11 AM',
  '50.41 mi',
  '12:35 /mi',
  '10h 34m'],
 ['Adam Kimble',
  'March 16, 2016 at 5:13 AM',
  '50.30 mi',
  '13:33 /mi',
  '11h 21m'],
 ['Adam Kimble',
  'March 15, 2016 at 5:10 AM',
  '50.19 mi',
  '13:48 /mi',
  '11h 32m'],
 ['Adam Kimble',
  'March 14, 2016 at 2:12 PM',
  '15.61 mi',
  '16:12 /mi',
  '4h 13m'],
 ['Adam Kimble',
  'March 14, 2016 at 4:06 AM',
  '9.07 mi',
  '19:06 /mi',
  '2h 53m'],
 ['Adam Kimble',
  'March 13, 2016 at 5:07 AM',
  '45.07 mi',
  '19:35 /mi',
  '14h 43m'],
 ['Adam Kimble',
  'March 12, 2016 at 4:10 AM',
  '42.23 mi',
  '16:58 /mi',
  '11h 56m'],
 ['Adam Kimble',
  'March 11, 2016 at 4:13 AM',
  '42.86 mi',
  '15:00 /mi',
  '10h 43m'],
 ['Adam Kimble',
  'March 10, 2016 at 4:06 AM',
  '38.22 mi',
  '16:32 /mi',
  '10h 32m'],
 ['Adam Kimble',
  'March 9, 2016 at 4:07 AM',
  '43.32 mi',
  '13:54 /mi',
  '10h 2m'],
 ['Adam Kimble',
  'March 7, 2016 at 4:06 AM',
  '41.62 mi',
  '14:48 /mi',
  '10h 15m'],
 ['Adam Kimble',
  'March 6, 2016 at 8:20 AM',
  '25.57 mi',
  '17:10 /mi',
  '7h 19m'],
 ['Adam Kimble',
  'March 6, 2016 at 4:12 AM',
  '10.49 mi',
  '19:25 /mi',
  '3h 23m'],
 ['Adam Kimble',
  'March 5, 2016 at 4:05 AM',
  '39.44 mi',
  '16:52 /mi',
  '11h 5m'],
 ['Adam Kimble',
  'March 4, 2016 at 4:07 AM',
  '45.68 mi',
  '21:09 /mi',
  '16h 6m'],
 ['Adam Kimble',
  'March 3, 2016 at 4:08 AM',
  '43.12 mi',
  '13:16 /mi',
  '9h 32m'],
 ['Adam Kimble',
  'March 2, 2016 at 4:04 AM',
  '47.02 mi',
  '13:46 /mi',
  '10h 47m'],
 ['Adam Kimble',
  'March 1, 2016 at 4:05 AM',
  '50.07 mi',
  '12:04 /mi',
  '10h 3m'],
 ['Adam Kimble',
  'April 14, 2016 at 1:40 AM',
  '35.16 mi',
  '11:16 /mi',
  '6h 36m'],
 ['Adam Kimble',
  'April 13, 2016 at 8:25 AM',
  '49.52 mi',
  '11:41 /mi',
  '9h 38m'],
 ['Adam Kimble',
  'April 12, 2016 at 3:12 PM',
  '38.24 mi',
  '11:29 /mi',
  '7h 19m'],
 ['Adam Kimble',
  'April 12, 2016 at 12:31 PM',
  '10.00 mi',
  '15:58 /mi',
  '2h 39m'],
 ['Adam Kimble',
  'April 12, 2016 at 5:25 AM',
  '16.87 mi',
  '20:37 /mi',
  '5h 47m'],
 ['Adam Kimble',
  'April 12, 2016 at 12:10 AM',
  '5.52 mi',
  '17:56 /mi',
  '1h 39m'],
 ['Adam Kimble',
  'April 11, 2016 at 5:15 AM',
  '37.84 mi',
  '16:42 /mi',
  '10h 32m'],
 ['Adam Kimble',
  'April 10, 2016 at 10:15 PM',
  '3.09 mi',
  '16:23 /mi',
  '50m 40s'],
 ['Adam Kimble',
  'April 10, 2016 at 7:08 PM',
  '5.65 mi',
  '15:15 /mi',
  '1h 26m'],
 ['Adam Kimble',
  'April 10, 2016 at 10:54 AM',
  '13.00 mi',
  '21:28 /mi',
  '4h 39m'],
 ['Adam Kimble',
  'April 8, 2016 at 1:30 AM',
  '23.81 mi',
  '12:08 /mi',
  '4h 48m'],
 ['Adam Kimble',
  'April 7, 2016 at 2:13 PM',
  '36.33 mi',
  '16:30 /mi',
  '9h 59m'],
 ['Adam Kimble',
  'April 7, 2016 at 3:10 AM',
  '16.08 mi',
  '25:46 /mi',
  '6h 54m'],
 ['Adam Kimble', 'April 6, 2016 at 6:33 PM', '10.86 mi', '16:51 /mi', '3h 2m'],
 ['Adam Kimble',
  'April 6, 2016 at 5:15 AM',
  '33.00 mi',
  '24:10 /mi',
  '13h 17m'],
 ['Adam Kimble',
  'April 5, 2016 at 5:14 AM',
  '40.35 mi',
  '16:34 /mi',
  '11h 8m'],
 ['Adam Kimble',
  'April 4, 2016 at 5:35 PM',
  '15.51 mi',
  '12:50 /mi',
  '3h 19m'],
 ['Adam Kimble',
  'April 4, 2016 at 5:33 AM',
  '26.26 mi',
  '13:28 /mi',
  '5h 53m'],
 ['Adam Kimble',
  'April 3, 2016 at 5:20 AM',
  '55.96 mi',
  '13:01 /mi',
  '12h 8m'],
 ['Adam Kimble', 'April 2, 2016 at 9:56 PM', '5.19 mi', '13:01 /mi', '1h 7m'],
 ['Adam Kimble',
  'April 2, 2016 at 5:16 AM',
  '54.82 mi',
  '12:29 /mi',
  '11h 24m'],
 ['Adam Kimble',
  'April 1, 2016 at 1:48 PM',
  '33.44 mi',
  '12:56 /mi',
  '7h 12m'],
 ['Adam Kimble',
  'April 1, 2016 at 12:04 PM',
  '6.33 mi',
  '15:42 /mi',
  '1h 39m'],
 ['Adam Kimble',
  'April 1, 2016 at 5:38 AM',
  '13.65 mi',
  '16:33 /mi',
  '3h 45m']]

In [4]:
#convert to dataframe and name columns
adam_df = pd.DataFrame(activity_details, columns=['name', 'date', 'distance', 'pace', 'duration'])
adam_df

           name                           date  distance       pace duration
0   Adam Kimble   February 29, 2016 at 4:03 AM  47.39 mi  13:44 /mi  10h 51m
1   Adam Kimble   February 28, 2016 at 4:25 AM  38.32 mi  15:36 /mi   9h 57m
2   Adam Kimble   February 27, 2016 at 4:04 AM  50.09 mi  15:26 /mi  12h 52m
3   Adam Kimble   February 26, 2016 at 4:01 AM  41.20 mi  14:43 /mi   10h 6m
4   Adam Kimble   February 22, 2016 at 4:01 AM  39.77 mi  16:50 /mi   11h 9m
5   Adam Kimble   February 21, 2016 at 6:35 PM   6.94 mi  16:42 /mi   1h 56m
6   Adam Kimble   February 21, 2016 at 4:14 AM  23.11 mi  19:03 /mi   7h 20m
7   Adam Kimble   February 20, 2016 at 2:59 PM  15.62 mi  17:22 /mi   4h 31m
8   Adam Kimble   February 20, 2016 at 4:07 AM  24.55 mi  18:41 /mi   7h 38m
9   Adam Kimble   February 19, 2016 at 5:46 PM   7.15 mi  23:11 /mi   2h 45m
10  Adam Kimble   February 19, 2016 at 4:16 AM  41.47 mi  14:29 /mi   10h 0m
11  Adam Kimble   February 18, 2016 at 4:20 AM  36.26 mi  15:25 /mi   9h 18m
12  Adam Kimble   February 17, 2016 at 2:26 PM  22.23 mi  15:26 /mi   5h 43m
13  Adam Kimble   February 17, 2016 at 4:06 AM  36.34 mi  12:23 /mi   7h 30m
14  Adam Kimble  February 16, 2016 at 12:48 PM  17.51 mi  17:47 /mi   5h 11m
15  Adam Kimble  February 16, 2016 at 12:14 PM   1.62 mi  14:55 /mi  24m 17s
16  Adam Kimble   February 15, 2016 at 4:00 AM  55.62 mi  14:13 /mi  13h 10m
17  Adam Kimble   February 11, 2016 at 9:32 AM   2.21 mi   8:42 /mi  19m 15s
18  Adam Kimble    February 8, 2016 at 6:36 AM   2.77 mi   9:47 /mi   27m 6s
19  Adam Kimble   February 6, 2016 at 12:18 PM  10.25 mi   8:18 /mi   1h 25m
20  Adam Kimble    February 5, 2016 at 9:23 AM   3.38 mi   8:44 /mi  29m 36s
21  Adam Kimble    February 4, 2016 at 6:57 PM   4.08 mi   8:45 /mi  35m 44s
22  Adam Kimble    February 3, 2016 at 4:25 PM   8.19 mi   8:18 /mi    1h 8m
23  Adam Kimble    February 2, 2016 at 7:30 AM   2.05 mi   9:17 /mi   19m 1s
24  Adam Kimble     March 31, 2016 at 12:28 PM  35.47 mi  14:10 /mi   8h 22m
25  Adam Kimble      March 31, 2016 at 5:10 AM  16.13 mi  20:18 /mi   5h 27m
26  Adam Kimble     March 30, 2016 at 10:59 PM   0.80 mi  16:52 /mi  13m 29s
27  Adam Kimble     March 30, 2016 at 10:25 PM   2.00 mi  16:46 /mi  33m 36s
28  Adam Kimble     March 30, 2016 at 11:40 AM  30.74 mi  20:57 /mi  10h 44m
29  Adam Kimble      March 30, 2016 at 5:08 AM  17.24 mi  16:28 /mi   4h 43m
..          ...                            ...       ...        ...      ...
59  Adam Kimble       March 6, 2016 at 4:12 AM  10.49 mi  19:25 /mi   3h 23m
60  Adam Kimble       March 5, 2016 at 4:05 AM  39.44 mi  16:52 /mi   11h 5m
61  Adam Kimble       March 4, 2016 at 4:07 AM  45.68 mi  21:09 /mi   16h 6m
62  Adam Kimble       March 3, 2016 at 4:08 AM  43.12 mi  13:16 /mi   9h 32m
63  Adam Kimble       March 2, 2016 at 4:04 AM  47.02 mi  13:46 /mi  10h 47m
64  Adam Kimble       March 1, 2016 at 4:05 AM  50.07 mi  12:04 /mi   10h 3m
65  Adam Kimble      April 14, 2016 at 1:40 AM  35.16 mi  11:16 /mi   6h 36m
66  Adam Kimble      April 13, 2016 at 8:25 AM  49.52 mi  11:41 /mi   9h 38m
67  Adam Kimble      April 12, 2016 at 3:12 PM  38.24 mi  11:29 /mi   7h 19m
68  Adam Kimble     April 12, 2016 at 12:31 PM  10.00 mi  15:58 /mi   2h 39m
69  Adam Kimble      April 12, 2016 at 5:25 AM  16.87 mi  20:37 /mi   5h 47m
70  Adam Kimble     April 12, 2016 at 12:10 AM   5.52 mi  17:56 /mi   1h 39m
71  Adam Kimble      April 11, 2016 at 5:15 AM  37.84 mi  16:42 /mi  10h 32m
72  Adam Kimble     April 10, 2016 at 10:15 PM   3.09 mi  16:23 /mi  50m 40s
73  Adam Kimble      April 10, 2016 at 7:08 PM   5.65 mi  15:15 /mi   1h 26m
74  Adam Kimble     April 10, 2016 at 10:54 AM  13.00 mi  21:28 /mi   4h 39m
75  Adam Kimble       April 8, 2016 at 1:30 AM  23.81 mi  12:08 /mi   4h 48m
76  Adam Kimble       April 7, 2016 at 2:13 PM  36.33 mi  16:30 /mi   9h 59m
77  Adam Kimble       April 7, 2016 at 3:10 AM  16.08 mi  25:46 /mi   6h 54m
78  Adam Kimble       April 6, 2016 at 6:33 PM  10.86 mi  16:51 /mi    3h 2m
79  Adam Kimble       April 6, 2016 at 5:15 AM  33.00 mi  24:10 /mi  13h 17m
80  Adam Kimble       April 5, 2016 at 5:14 AM  40.35 mi  16:34 /mi   11h 8m
81  Adam Kimble       April 4, 2016 at 5:35 PM  15.51 mi  12:50 /mi   3h 19m
82  Adam Kimble       April 4, 2016 at 5:33 AM  26.26 mi  13:28 /mi   5h 53m
83  Adam Kimble       April 3, 2016 at 5:20 AM  55.96 mi  13:01 /mi   12h 8m
84  Adam Kimble       April 2, 2016 at 9:56 PM   5.19 mi  13:01 /mi    1h 7m
85  Adam Kimble       April 2, 2016 at 5:16 AM  54.82 mi  12:29 /mi  11h 24m
86  Adam Kimble       April 1, 2016 at 1:48 PM  33.44 mi  12:56 /mi   7h 12m
87  Adam Kimble      April 1, 2016 at 12:04 PM   6.33 mi  15:42 /mi   1h 39m
88  Adam Kimble       April 1, 2016 at 5:38 AM  13.65 mi  16:33 /mi   3h 45m

[89 rows x 5 columns]

In [5]:
#convert date to datetime object
adam_df['date'] = adam_df['date'].str.replace('at', '')

adam_df.date=pd.to_datetime(adam_df.date)
adam_df

           name                date  distance       pace duration
0   Adam Kimble 2016-02-29 04:03:00  47.39 mi  13:44 /mi  10h 51m
1   Adam Kimble 2016-02-28 04:25:00  38.32 mi  15:36 /mi   9h 57m
2   Adam Kimble 2016-02-27 04:04:00  50.09 mi  15:26 /mi  12h 52m
3   Adam Kimble 2016-02-26 04:01:00  41.20 mi  14:43 /mi   10h 6m
4   Adam Kimble 2016-02-22 04:01:00  39.77 mi  16:50 /mi   11h 9m
5   Adam Kimble 2016-02-21 18:35:00   6.94 mi  16:42 /mi   1h 56m
6   Adam Kimble 2016-02-21 04:14:00  23.11 mi  19:03 /mi   7h 20m
7   Adam Kimble 2016-02-20 14:59:00  15.62 mi  17:22 /mi   4h 31m
8   Adam Kimble 2016-02-20 04:07:00  24.55 mi  18:41 /mi   7h 38m
9   Adam Kimble 2016-02-19 17:46:00   7.15 mi  23:11 /mi   2h 45m
10  Adam Kimble 2016-02-19 04:16:00  41.47 mi  14:29 /mi   10h 0m
11  Adam Kimble 2016-02-18 04:20:00  36.26 mi  15:25 /mi   9h 18m
12  Adam Kimble 2016-02-17 14:26:00  22.23 mi  15:26 /mi   5h 43m
13  Adam Kimble 2016-02-17 04:06:00  36.34 mi  12:23 /mi   7h 30m
14  Adam Kimble 2016-02-16 12:48:00  17.51 mi  17:47 /mi   5h 11m
15  Adam Kimble 2016-02-16 12:14:00   1.62 mi  14:55 /mi  24m 17s
16  Adam Kimble 2016-02-15 04:00:00  55.62 mi  14:13 /mi  13h 10m
17  Adam Kimble 2016-02-11 09:32:00   2.21 mi   8:42 /mi  19m 15s
18  Adam Kimble 2016-02-08 06:36:00   2.77 mi   9:47 /mi   27m 6s
19  Adam Kimble 2016-02-06 12:18:00  10.25 mi   8:18 /mi   1h 25m
20  Adam Kimble 2016-02-05 09:23:00   3.38 mi   8:44 /mi  29m 36s
21  Adam Kimble 2016-02-04 18:57:00   4.08 mi   8:45 /mi  35m 44s
22  Adam Kimble 2016-02-03 16:25:00   8.19 mi   8:18 /mi    1h 8m
23  Adam Kimble 2016-02-02 07:30:00   2.05 mi   9:17 /mi   19m 1s
24  Adam Kimble 2016-03-31 12:28:00  35.47 mi  14:10 /mi   8h 22m
25  Adam Kimble 2016-03-31 05:10:00  16.13 mi  20:18 /mi   5h 27m
26  Adam Kimble 2016-03-30 22:59:00   0.80 mi  16:52 /mi  13m 29s
27  Adam Kimble 2016-03-30 22:25:00   2.00 mi  16:46 /mi  33m 36s
28  Adam Kimble 2016-03-30 11:40:00  30.74 mi  20:57 /mi  10h 44m
29  Adam Kimble 2016-03-30 05:08:00  17.24 mi  16:28 /mi   4h 43m
..          ...                 ...       ...        ...      ...
59  Adam Kimble 2016-03-06 04:12:00  10.49 mi  19:25 /mi   3h 23m
60  Adam Kimble 2016-03-05 04:05:00  39.44 mi  16:52 /mi   11h 5m
61  Adam Kimble 2016-03-04 04:07:00  45.68 mi  21:09 /mi   16h 6m
62  Adam Kimble 2016-03-03 04:08:00  43.12 mi  13:16 /mi   9h 32m
63  Adam Kimble 2016-03-02 04:04:00  47.02 mi  13:46 /mi  10h 47m
64  Adam Kimble 2016-03-01 04:05:00  50.07 mi  12:04 /mi   10h 3m
65  Adam Kimble 2016-04-14 01:40:00  35.16 mi  11:16 /mi   6h 36m
66  Adam Kimble 2016-04-13 08:25:00  49.52 mi  11:41 /mi   9h 38m
67  Adam Kimble 2016-04-12 15:12:00  38.24 mi  11:29 /mi   7h 19m
68  Adam Kimble 2016-04-12 12:31:00  10.00 mi  15:58 /mi   2h 39m
69  Adam Kimble 2016-04-12 05:25:00  16.87 mi  20:37 /mi   5h 47m
70  Adam Kimble 2016-04-12 00:10:00   5.52 mi  17:56 /mi   1h 39m
71  Adam Kimble 2016-04-11 05:15:00  37.84 mi  16:42 /mi  10h 32m
72  Adam Kimble 2016-04-10 22:15:00   3.09 mi  16:23 /mi  50m 40s
73  Adam Kimble 2016-04-10 19:08:00   5.65 mi  15:15 /mi   1h 26m
74  Adam Kimble 2016-04-10 10:54:00  13.00 mi  21:28 /mi   4h 39m
75  Adam Kimble 2016-04-08 01:30:00  23.81 mi  12:08 /mi   4h 48m
76  Adam Kimble 2016-04-07 14:13:00  36.33 mi  16:30 /mi   9h 59m
77  Adam Kimble 2016-04-07 03:10:00  16.08 mi  25:46 /mi   6h 54m
78  Adam Kimble 2016-04-06 18:33:00  10.86 mi  16:51 /mi    3h 2m
79  Adam Kimble 2016-04-06 05:15:00  33.00 mi  24:10 /mi  13h 17m
80  Adam Kimble 2016-04-05 05:14:00  40.35 mi  16:34 /mi   11h 8m
81  Adam Kimble 2016-04-04 17:35:00  15.51 mi  12:50 /mi   3h 19m
82  Adam Kimble 2016-04-04 05:33:00  26.26 mi  13:28 /mi   5h 53m
83  Adam Kimble 2016-04-03 05:20:00  55.96 mi  13:01 /mi   12h 8m
84  Adam Kimble 2016-04-02 21:56:00   5.19 mi  13:01 /mi    1h 7m
85  Adam Kimble 2016-04-02 05:16:00  54.82 mi  12:29 /mi  11h 24m
86  Adam Kimble 2016-04-01 13:48:00  33.44 mi  12:56 /mi   7h 12m
87  Adam Kimble 2016-04-01 12:04:00   6.33 mi  15:42 /mi   1h 39m
88  Adam Kimble 2016-04-01 05:38:00  13.65 mi  16:33 /mi   3h 45m

[89 rows x 5 columns]

In [6]:
adam_df['duration_sum'] =adam_df['duration'].str.split(' ')
adam_df

           name                date  distance       pace duration duration_sum
0   Adam Kimble 2016-02-29 04:03:00  47.39 mi  13:44 /mi  10h 51m   [10h, 51m]
1   Adam Kimble 2016-02-28 04:25:00  38.32 mi  15:36 /mi   9h 57m    [9h, 57m]
2   Adam Kimble 2016-02-27 04:04:00  50.09 mi  15:26 /mi  12h 52m   [12h, 52m]
3   Adam Kimble 2016-02-26 04:01:00  41.20 mi  14:43 /mi   10h 6m    [10h, 6m]
4   Adam Kimble 2016-02-22 04:01:00  39.77 mi  16:50 /mi   11h 9m    [11h, 9m]
5   Adam Kimble 2016-02-21 18:35:00   6.94 mi  16:42 /mi   1h 56m    [1h, 56m]
6   Adam Kimble 2016-02-21 04:14:00  23.11 mi  19:03 /mi   7h 20m    [7h, 20m]
7   Adam Kimble 2016-02-20 14:59:00  15.62 mi  17:22 /mi   4h 31m    [4h, 31m]
8   Adam Kimble 2016-02-20 04:07:00  24.55 mi  18:41 /mi   7h 38m    [7h, 38m]
9   Adam Kimble 2016-02-19 17:46:00   7.15 mi  23:11 /mi   2h 45m    [2h, 45m]
10  Adam Kimble 2016-02-19 04:16:00  41.47 mi  14:29 /mi   10h 0m    [10h, 0m]
11  Adam Kimble 2016-02-18 04:20:00  36.26 mi  15:25 /mi   9h 18m    [9h, 18m]
12  Adam Kimble 2016-02-17 14:26:00  22.23 mi  15:26 /mi   5h 43m    [5h, 43m]
13  Adam Kimble 2016-02-17 04:06:00  36.34 mi  12:23 /mi   7h 30m    [7h, 30m]
14  Adam Kimble 2016-02-16 12:48:00  17.51 mi  17:47 /mi   5h 11m    [5h, 11m]
15  Adam Kimble 2016-02-16 12:14:00   1.62 mi  14:55 /mi  24m 17s   [24m, 17s]
16  Adam Kimble 2016-02-15 04:00:00  55.62 mi  14:13 /mi  13h 10m   [13h, 10m]
17  Adam Kimble 2016-02-11 09:32:00   2.21 mi   8:42 /mi  19m 15s   [19m, 15s]
18  Adam Kimble 2016-02-08 06:36:00   2.77 mi   9:47 /mi   27m 6s    [27m, 6s]
19  Adam Kimble 2016-02-06 12:18:00  10.25 mi   8:18 /mi   1h 25m    [1h, 25m]
20  Adam Kimble 2016-02-05 09:23:00   3.38 mi   8:44 /mi  29m 36s   [29m, 36s]
21  Adam Kimble 2016-02-04 18:57:00   4.08 mi   8:45 /mi  35m 44s   [35m, 44s]
22  Adam Kimble 2016-02-03 16:25:00   8.19 mi   8:18 /mi    1h 8m     [1h, 8m]
23  Adam Kimble 2016-02-02 07:30:00   2.05 mi   9:17 /mi   19m 1s    [19m, 1s]
24  Adam Kimble 2016-03-31 12:28:00  35.47 mi  14:10 /mi   8h 22m    [8h, 22m]
25  Adam Kimble 2016-03-31 05:10:00  16.13 mi  20:18 /mi   5h 27m    [5h, 27m]
26  Adam Kimble 2016-03-30 22:59:00   0.80 mi  16:52 /mi  13m 29s   [13m, 29s]
27  Adam Kimble 2016-03-30 22:25:00   2.00 mi  16:46 /mi  33m 36s   [33m, 36s]
28  Adam Kimble 2016-03-30 11:40:00  30.74 mi  20:57 /mi  10h 44m   [10h, 44m]
29  Adam Kimble 2016-03-30 05:08:00  17.24 mi  16:28 /mi   4h 43m    [4h, 43m]
..          ...                 ...       ...        ...      ...          ...
59  Adam Kimble 2016-03-06 04:12:00  10.49 mi  19:25 /mi   3h 23m    [3h, 23m]
60  Adam Kimble 2016-03-05 04:05:00  39.44 mi  16:52 /mi   11h 5m    [11h, 5m]
61  Adam Kimble 2016-03-04 04:07:00  45.68 mi  21:09 /mi   16h 6m    [16h, 6m]
62  Adam Kimble 2016-03-03 04:08:00  43.12 mi  13:16 /mi   9h 32m    [9h, 32m]
63  Adam Kimble 2016-03-02 04:04:00  47.02 mi  13:46 /mi  10h 47m   [10h, 47m]
64  Adam Kimble 2016-03-01 04:05:00  50.07 mi  12:04 /mi   10h 3m    [10h, 3m]
65  Adam Kimble 2016-04-14 01:40:00  35.16 mi  11:16 /mi   6h 36m    [6h, 36m]
66  Adam Kimble 2016-04-13 08:25:00  49.52 mi  11:41 /mi   9h 38m    [9h, 38m]
67  Adam Kimble 2016-04-12 15:12:00  38.24 mi  11:29 /mi   7h 19m    [7h, 19m]
68  Adam Kimble 2016-04-12 12:31:00  10.00 mi  15:58 /mi   2h 39m    [2h, 39m]
69  Adam Kimble 2016-04-12 05:25:00  16.87 mi  20:37 /mi   5h 47m    [5h, 47m]
70  Adam Kimble 2016-04-12 00:10:00   5.52 mi  17:56 /mi   1h 39m    [1h, 39m]
71  Adam Kimble 2016-04-11 05:15:00  37.84 mi  16:42 /mi  10h 32m   [10h, 32m]
72  Adam Kimble 2016-04-10 22:15:00   3.09 mi  16:23 /mi  50m 40s   [50m, 40s]
73  Adam Kimble 2016-04-10 19:08:00   5.65 mi  15:15 /mi   1h 26m    [1h, 26m]
74  Adam Kimble 2016-04-10 10:54:00  13.00 mi  21:28 /mi   4h 39m    [4h, 39m]
75  Adam Kimble 2016-04-08 01:30:00  23.81 mi  12:08 /mi   4h 48m    [4h, 48m]
76  Adam Kimble 2016-04-07 14:13:00  36.33 mi  16:30 /mi   9h 59m    [9h, 59m]
77  Adam Kimble 2016-04-07 03:10:00  16.08 mi  25:46 /mi   6h 54m    [6h, 54m]
78  Adam Kimble 2016-04-06 18:33:00  10.86 mi  16:51 /mi    3h 2m     [3h, 2m]
79  Adam Kimble 2016-04-06 05:15:00  33.00 mi  24:10 /mi  13h 17m   [13h, 17m]
80  Adam Kimble 2016-04-05 05:14:00  40.35 mi  16:34 /mi   11h 8m    [11h, 8m]
81  Adam Kimble 2016-04-04 17:35:00  15.51 mi  12:50 /mi   3h 19m    [3h, 19m]
82  Adam Kimble 2016-04-04 05:33:00  26.26 mi  13:28 /mi   5h 53m    [5h, 53m]
83  Adam Kimble 2016-04-03 05:20:00  55.96 mi  13:01 /mi   12h 8m    [12h, 8m]
84  Adam Kimble 2016-04-02 21:56:00   5.19 mi  13:01 /mi    1h 7m     [1h, 7m]
85  Adam Kimble 2016-04-02 05:16:00  54.82 mi  12:29 /mi  11h 24m   [11h, 24m]
86  Adam Kimble 2016-04-01 13:48:00  33.44 mi  12:56 /mi   7h 12m    [7h, 12m]
87  Adam Kimble 2016-04-01 12:04:00   6.33 mi  15:42 /mi   1h 39m    [1h, 39m]
88  Adam Kimble 2016-04-01 05:38:00  13.65 mi  16:33 /mi   3h 45m    [3h, 45m]

[89 rows x 6 columns]

In [7]:
#create column for duration in minutes
def total_duration(x):
    min_sum = 0
    for item in x:
        min_sum += convert_to_minutes(item)
    return min_sum

def convert_to_minutes(time):
    time_type = time[-1];
    if time_type == "h":
        return int(time[0:-1]) * 60
    if time_type =="m":
        return int(time[0:-1])
    else:
        return 0


adam_df['duration_sum']=adam_df['duration_sum'].map(total_duration)
adam_df

,name,date,distance,pace,duration,duration_sum
0,Adam Kimble,2016-02-29 04:03:00,47.39 mi,13:44 /mi,10h 51m,651
1,Adam Kimble,2016-02-28 04:25:00,38.32 mi,15:36 /mi,9h 57m,597
2,Adam Kimble,2016-02-27 04:04:00,50.09 mi,15:26 /mi,12h 52m,772
3,Adam Kimble,2016-02-26 04:01:00,41.20 mi,14:43 /mi,10h 6m,606
4,Adam Kimble,2016-02-22 04:01:00,39.77 mi,16:50 /mi,11h 9m,669
5,Adam Kimble,2016-02-21 18:35:00,6.94 mi,16:42 /mi,1h 56m,116
6,Adam Kimble,2016-02-21 04:14:00,23.11 mi,19:03 /mi,7h 20m,440
7,Adam Kimble,2016-02-20 14:59:00,15.62 mi,17:22 /mi,4h 31m,271
8,Adam Kimble,2016-02-20 04:07:00,24.55 mi,18:41 /mi,7h 38m,458
9,Adam Kimble,2016-02-19 17:46:00,7.15 mi,23:11 /mi,2h 45m,165
10,Adam Kimble,2016-02-19 04:16:00,41.47 mi,14:29 /mi,10h 0m,600
11,Adam Kimble,2016-02-18 04:20:00,36.26 mi,15:25 /mi,9h 18m,558
12,Adam Kimble,2016-02-17 14:26:00,22.23 mi,15:26 /mi,5h 43m,343
13,Adam Kimble,2016-02-17 04:06:00,36.34 mi,12:23 /mi,7h 30m,450
14,Adam Kimble,2016-02-16 12:48:00,17.51 mi,17:47 /mi,5h 11m,311
15,Adam Kimble,2016-02-16 12:14:00,1.62 mi,14:55 /mi,24m 17s,24
16,Adam Kimble,2016-02-15 04:00:00,55.62 mi,14:13 /mi,13h 10m,790
17,Adam Kimble,2016-02-11 09:32:00,2.21 mi,8:42 /mi,19m 15s,19
18,Adam Kimble,2016-02-08 06:36:00,2.77 mi,9:47 /mi,27m 6s,27
19,Adam Kimble,2016-02-06 12:18:00,10.25 mi,8:18 /mi,1h 25m,85
20,Adam Kimble,2016-02-05 09:23:00,3.38 mi,8:44 /mi,29m 36s,29
21,Adam Kimble,2016-02-04 18:57:00,4.08 mi,8:45 /mi,35m 44s,35
22,Adam Kimble,2016-02-03 16:25:00,8.19 mi,8:18 /mi,1h 8m,68
23,Adam Kimble,2016-02-02 07:30:00,2.05 mi,9:17 /mi,19m 1s,19
24,Adam Kimble,2016-03-31 12:28:00,35.47 mi,14:10 /mi,8h 22m,502
25,Adam Kimble,2016-03-31 05:10:00,16.13 mi,20:18 /mi,5h 27m,327
26,Adam Kimble,2016-03-30 22:59:00,0.80 mi,16:52 /mi,13m 29s,13
27,Adam Kimble,2016-03-30 22:25:00,2.00 mi,16:46 /mi,33m 36s,33
28,Adam Kimble,2016-03-30 11:40:00,30.74 mi,20:57 /mi,10h 44m,644
29,Adam Kimble,2016-03-30 05:08:00,17.24 mi,16:28 /mi,4h 43m,283
...,...,...,...,...,...,...
59,Adam Kimble,2016-03-06 04:12:00,10.49 mi,19:25 /mi,3h 23m,203
60,Adam Kimble,2016-03-05 04:05:00,39.44 mi,16:52 /mi,11h 5m,665
61,Adam Kimble,2016-03-04 04:07:00,45.68 mi,21:09 /mi,16h 6m,966
62,Adam Kimble,2016-03-03 04:08:00,43.12 mi,13:16 /mi,9h 32m,572
63,Adam Kimble,2016-03-02 04:04:00,47.02 mi,13:46 /mi,10h 47m,647
64,Adam Kimble,2016-03-01 04:05:00,50.07 mi,12:04 /mi,10h 3m,603
65,Adam Kimble,2016-04-14 01:40:00,35.16 mi,11:16 /mi,6h 36m,396
66,Adam Kimble,2016-04-13 08:25:00,49.52 mi,11:41 /mi,9h 38m,578
67,Adam Kimble,2016-04-12 15:12:00,38.24 mi,11:29 /mi,7h 19m,439
68,Adam Kimble,2016-04-12 12:31:00,10.00 mi,15:58 /mi,2h 39m,159
69,Adam Kimble,2016-04-12 05:25:00,16.87 mi,20:37 /mi,5h 47m,347
70,Adam Kimble,2016-04-12 00:10:00,5.52 mi,17:56 /mi,1h 39m,99
71,Adam Kimble,2016-04-11 05:15:00,37.84 mi,16:42 /mi,10h 32m,632
72,Adam Kimble,2016-04-10 22:15:00,3.09 mi,16:23 /mi,50m 40s,50
73,Adam Kimble,2016-04-10 19:08:00,5.65 mi,15:15 /mi,1h 26m,86
74,Adam Kimble,2016-04-10 10:54:00,13.00 mi,21:28 /mi,4h 39m,279
75,Adam Kimble,2016-04-08 01:30:00,23.81 mi,12:08 /mi,4h 48m,288
76,Adam Kimble,2016-04-07 14:13:00,36.33 mi,16:30 /mi,9h 59m,599
77,Adam Kimble,2016-04-07 03:10:00,16.08 mi,25:46 /mi,6h 54m,414
78,Adam Kimble,2016-04-06 18:33:00,10.86 mi,16:51 /mi,3h 2m,182
79,Adam Kimble,2016-04-06 05:15:00,33.00 mi,24:10 /mi,13h 17m,797
80,Adam Kimble,2016-04-05 05:14:00,40.35 mi,16:34 /mi,11h 8m,668
81,Adam Kimble,2016-04-04 17:35:00,15.51 mi,12:50 /mi,3h 19m,199
82,Adam Kimble,2016-04-04 05:33:00,26.26 mi,13:28 /mi,5h 53m,353
83,Adam Kimble,2016-04-03 05:20:00,55.96 mi,13:01 /mi,12h 8m,728
84,Adam Kimble,2016-04-02 21:56:00,5.19 mi,13:01 /mi,1h 7m,67
85,Adam Kimble,2016-04-02 05:16:00,54.82 mi,12:29 /mi,11h 24m,684
86,Adam Kimble,2016-04-01 13:48:00,33.44 mi,12:56 /mi,7h 12m,432
87,Adam Kimble,2016-04-01 12:04:00,6.33 mi,15:42 /mi,1h 39m,99
88,Adam Kimble,2016-04-01 05:38:00,13.65 mi,16:33 /mi,3h 45m,225

In [8]:
#remove /mi from pace and convert to fraction
adam_df['pace'] =adam_df['pace'].str.replace('/mi', '')
def express_pace_decimal(row):
    try:
        minutes_part = float(row.split(":")[0])
        seconds_part = float(row.split(":")[1])
        minute_fraction = seconds_part / 60
        return (minutes_part +  minute_fraction)
    except:
        return '0'
adam_df['pace_fraction'] = adam_df['pace'].map(express_pace_decimal) 
adam_df

,name,date,distance,pace,duration,duration_sum,pace_fraction
0,Adam Kimble,2016-02-29 04:03:00,47.39 mi,13:44,10h 51m,651,13.733333
1,Adam Kimble,2016-02-28 04:25:00,38.32 mi,15:36,9h 57m,597,15.600000
2,Adam Kimble,2016-02-27 04:04:00,50.09 mi,15:26,12h 52m,772,15.433333
3,Adam Kimble,2016-02-26 04:01:00,41.20 mi,14:43,10h 6m,606,14.716667
4,Adam Kimble,2016-02-22 04:01:00,39.77 mi,16:50,11h 9m,669,16.833333
5,Adam Kimble,2016-02-21 18:35:00,6.94 mi,16:42,1h 56m,116,16.700000
6,Adam Kimble,2016-02-21 04:14:00,23.11 mi,19:03,7h 20m,440,19.050000
7,Adam Kimble,2016-02-20 14:59:00,15.62 mi,17:22,4h 31m,271,17.366667
8,Adam Kimble,2016-02-20 04:07:00,24.55 mi,18:41,7h 38m,458,18.683333
9,Adam Kimble,2016-02-19 17:46:00,7.15 mi,23:11,2h 45m,165,23.183333
10,Adam Kimble,2016-02-19 04:16:00,41.47 mi,14:29,10h 0m,600,14.483333
11,Adam Kimble,2016-02-18 04:20:00,36.26 mi,15:25,9h 18m,558,15.416667
12,Adam Kimble,2016-02-17 14:26:00,22.23 mi,15:26,5h 43m,343,15.433333
13,Adam Kimble,2016-02-17 04:06:00,36.34 mi,12:23,7h 30m,450,12.383333
14,Adam Kimble,2016-02-16 12:48:00,17.51 mi,17:47,5h 11m,311,17.783333
15,Adam Kimble,2016-02-16 12:14:00,1.62 mi,14:55,24m 17s,24,14.916667
16,Adam Kimble,2016-02-15 04:00:00,55.62 mi,14:13,13h 10m,790,14.216667
17,Adam Kimble,2016-02-11 09:32:00,2.21 mi,8:42,19m 15s,19,8.700000
18,Adam Kimble,2016-02-08 06:36:00,2.77 mi,9:47,27m 6s,27,9.783333
19,Adam Kimble,2016-02-06 12:18:00,10.25 mi,8:18,1h 25m,85,8.300000
20,Adam Kimble,2016-02-05 09:23:00,3.38 mi,8:44,29m 36s,29,8.733333
21,Adam Kimble,2016-02-04 18:57:00,4.08 mi,8:45,35m 44s,35,8.750000
22,Adam Kimble,2016-02-03 16:25:00,8.19 mi,8:18,1h 8m,68,8.300000
23,Adam Kimble,2016-02-02 07:30:00,2.05 mi,9:17,19m 1s,19,9.283333
24,Adam Kimble,2016-03-31 12:28:00,35.47 mi,14:10,8h 22m,502,14.166667
25,Adam Kimble,2016-03-31 05:10:00,16.13 mi,20:18,5h 27m,327,20.300000
26,Adam Kimble,2016-03-30 22:59:00,0.80 mi,16:52,13m 29s,13,16.866667
27,Adam Kimble,2016-03-30 22:25:00,2.00 mi,16:46,33m 36s,33,16.766667
28,Adam Kimble,2016-03-30 11:40:00,30.74 mi,20:57,10h 44m,644,20.950000
29,Adam Kimble,2016-03-30 05:08:00,17.24 mi,16:28,4h 43m,283,16.466667
...,...,...,...,...,...,...,...
59,Adam Kimble,2016-03-06 04:12:00,10.49 mi,19:25,3h 23m,203,19.416667
60,Adam Kimble,2016-03-05 04:05:00,39.44 mi,16:52,11h 5m,665,16.866667
61,Adam Kimble,2016-03-04 04:07:00,45.68 mi,21:09,16h 6m,966,21.150000
62,Adam Kimble,2016-03-03 04:08:00,43.12 mi,13:16,9h 32m,572,13.266667
63,Adam Kimble,2016-03-02 04:04:00,47.02 mi,13:46,10h 47m,647,13.766667
64,Adam Kimble,2016-03-01 04:05:00,50.07 mi,12:04,10h 3m,603,12.066667
65,Adam Kimble,2016-04-14 01:40:00,35.16 mi,11:16,6h 36m,396,11.266667
66,Adam Kimble,2016-04-13 08:25:00,49.52 mi,11:41,9h 38m,578,11.683333
67,Adam Kimble,2016-04-12 15:12:00,38.24 mi,11:29,7h 19m,439,11.483333
68,Adam Kimble,2016-04-12 12:31:00,10.00 mi,15:58,2h 39m,159,15.966667
69,Adam Kimble,2016-04-12 05:25:00,16.87 mi,20:37,5h 47m,347,20.616667
70,Adam Kimble,2016-04-12 00:10:00,5.52 mi,17:56,1h 39m,99,17.933333
71,Adam Kimble,2016-04-11 05:15:00,37.84 mi,16:42,10h 32m,632,16.700000
72,Adam Kimble,2016-04-10 22:15:00,3.09 mi,16:23,50m 40s,50,16.383333
73,Adam Kimble,2016-04-10 19:08:00,5.65 mi,15:15,1h 26m,86,15.250000
74,Adam Kimble,2016-04-10 10:54:00,13.00 mi,21:28,4h 39m,279,21.466667
75,Adam Kimble,2016-04-08 01:30:00,23.81 mi,12:08,4h 48m,288,12.133333
76,Adam Kimble,2016-04-07 14:13:00,36.33 mi,16:30,9h 59m,599,16.500000
77,Adam Kimble,2016-04-07 03:10:00,16.08 mi,25:46,6h 54m,414,25.766667
78,Adam Kimble,2016-04-06 18:33:00,10.86 mi,16:51,3h 2m,182,16.850000
79,Adam Kimble,2016-04-06 05:15:00,33.00 mi,24:10,13h 17m,797,24.166667
80,Adam Kimble,2016-04-05 05:14:00,40.35 mi,16:34,11h 8m,668,16.566667
81,Adam Kimble,2016-04-04 17:35:00,15.51 mi,12:50,3h 19m,199,12.833333
82,Adam Kimble,2016-04-04 05:33:00,26.26 mi,13:28,5h 53m,353,13.466667
83,Adam Kimble,2016-04-03 05:20:00,55.96 mi,13:01,12h 8m,728,13.016667
84,Adam Kimble,2016-04-02 21:56:00,5.19 mi,13:01,1h 7m,67,13.016667
85,Adam Kimble,2016-04-02 05:16:00,54.82 mi,12:29,11h 24m,684,12.483333
86,Adam Kimble,2016-04-01 13:48:00,33.44 mi,12:56,7h 12m,432,12.933333
87,Adam Kimble,2016-04-01 12:04:00,6.33 mi,15:42,1h 39m,99,15.700000
88,Adam Kimble,2016-04-01 05:38:00,13.65 mi,16:33,3h 45m,225,16.550000

In [11]:
#filter the data for run dates
adam_summary = adam_df.sort_values(by=['date'])
adam_summary = adam_summary[(adam_df['date'] > '2016-02-11 09:32:00') & (adam_summary['date'] <= '2016-04-14 01:40:00')]

adam_summary

C:\Users\snowr\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  This is separate from the ipykernel package so we can avoid doing imports until

,name,date,distance,pace,duration,duration_sum,pace_fraction
16,Adam Kimble,2016-02-15 04:00:00,55.62 mi,14:13,13h 10m,790,14.216667
15,Adam Kimble,2016-02-16 12:14:00,1.62 mi,14:55,24m 17s,24,14.916667
14,Adam Kimble,2016-02-16 12:48:00,17.51 mi,17:47,5h 11m,311,17.783333
13,Adam Kimble,2016-02-17 04:06:00,36.34 mi,12:23,7h 30m,450,12.383333
12,Adam Kimble,2016-02-17 14:26:00,22.23 mi,15:26,5h 43m,343,15.433333
11,Adam Kimble,2016-02-18 04:20:00,36.26 mi,15:25,9h 18m,558,15.416667
10,Adam Kimble,2016-02-19 04:16:00,41.47 mi,14:29,10h 0m,600,14.483333
9,Adam Kimble,2016-02-19 17:46:00,7.15 mi,23:11,2h 45m,165,23.183333
8,Adam Kimble,2016-02-20 04:07:00,24.55 mi,18:41,7h 38m,458,18.683333
7,Adam Kimble,2016-02-20 14:59:00,15.62 mi,17:22,4h 31m,271,17.366667
6,Adam Kimble,2016-02-21 04:14:00,23.11 mi,19:03,7h 20m,440,19.050000
5,Adam Kimble,2016-02-21 18:35:00,6.94 mi,16:42,1h 56m,116,16.700000
4,Adam Kimble,2016-02-22 04:01:00,39.77 mi,16:50,11h 9m,669,16.833333
3,Adam Kimble,2016-02-26 04:01:00,41.20 mi,14:43,10h 6m,606,14.716667
2,Adam Kimble,2016-02-27 04:04:00,50.09 mi,15:26,12h 52m,772,15.433333
1,Adam Kimble,2016-02-28 04:25:00,38.32 mi,15:36,9h 57m,597,15.600000
0,Adam Kimble,2016-02-29 04:03:00,47.39 mi,13:44,10h 51m,651,13.733333
64,Adam Kimble,2016-03-01 04:05:00,50.07 mi,12:04,10h 3m,603,12.066667
63,Adam Kimble,2016-03-02 04:04:00,47.02 mi,13:46,10h 47m,647,13.766667
62,Adam Kimble,2016-03-03 04:08:00,43.12 mi,13:16,9h 32m,572,13.266667
61,Adam Kimble,2016-03-04 04:07:00,45.68 mi,21:09,16h 6m,966,21.150000
60,Adam Kimble,2016-03-05 04:05:00,39.44 mi,16:52,11h 5m,665,16.866667
59,Adam Kimble,2016-03-06 04:12:00,10.49 mi,19:25,3h 23m,203,19.416667
58,Adam Kimble,2016-03-06 08:20:00,25.57 mi,17:10,7h 19m,439,17.166667
57,Adam Kimble,2016-03-07 04:06:00,41.62 mi,14:48,10h 15m,615,14.800000
56,Adam Kimble,2016-03-09 04:07:00,43.32 mi,13:54,10h 2m,602,13.900000
55,Adam Kimble,2016-03-10 04:06:00,38.22 mi,16:32,10h 32m,632,16.533333
54,Adam Kimble,2016-03-11 04:13:00,42.86 mi,15:00,10h 43m,643,15.000000
53,Adam Kimble,2016-03-12 04:10:00,42.23 mi,16:58,11h 56m,716,16.966667
52,Adam Kimble,2016-03-13 05:07:00,45.07 mi,19:35,14h 43m,883,19.583333
...,...,...,...,...,...,...,...
29,Adam Kimble,2016-03-30 05:08:00,17.24 mi,16:28,4h 43m,283,16.466667
28,Adam Kimble,2016-03-30 11:40:00,30.74 mi,20:57,10h 44m,644,20.950000
27,Adam Kimble,2016-03-30 22:25:00,2.00 mi,16:46,33m 36s,33,16.766667
26,Adam Kimble,2016-03-30 22:59:00,0.80 mi,16:52,13m 29s,13,16.866667
25,Adam Kimble,2016-03-31 05:10:00,16.13 mi,20:18,5h 27m,327,20.300000
24,Adam Kimble,2016-03-31 12:28:00,35.47 mi,14:10,8h 22m,502,14.166667
88,Adam Kimble,2016-04-01 05:38:00,13.65 mi,16:33,3h 45m,225,16.550000
87,Adam Kimble,2016-04-01 12:04:00,6.33 mi,15:42,1h 39m,99,15.700000
86,Adam Kimble,2016-04-01 13:48:00,33.44 mi,12:56,7h 12m,432,12.933333
85,Adam Kimble,2016-04-02 05:16:00,54.82 mi,12:29,11h 24m,684,12.483333
84,Adam Kimble,2016-04-02 21:56:00,5.19 mi,13:01,1h 7m,67,13.016667
83,Adam Kimble,2016-04-03 05:20:00,55.96 mi,13:01,12h 8m,728,13.016667
82,Adam Kimble,2016-04-04 05:33:00,26.26 mi,13:28,5h 53m,353,13.466667
81,Adam Kimble,2016-04-04 17:35:00,15.51 mi,12:50,3h 19m,199,12.833333
80,Adam Kimble,2016-04-05 05:14:00,40.35 mi,16:34,11h 8m,668,16.566667
79,Adam Kimble,2016-04-06 05:15:00,33.00 mi,24:10,13h 17m,797,24.166667
78,Adam Kimble,2016-04-06 18:33:00,10.86 mi,16:51,3h 2m,182,16.850000
77,Adam Kimble,2016-04-07 03:10:00,16.08 mi,25:46,6h 54m,414,25.766667
76,Adam Kimble,2016-04-07 14:13:00,36.33 mi,16:30,9h 59m,599,16.500000
75,Adam Kimble,2016-04-08 01:30:00,23.81 mi,12:08,4h 48m,288,12.133333
74,Adam Kimble,2016-04-10 10:54:00,13.00 mi,21:28,4h 39m,279,21.466667
73,Adam Kimble,2016-04-10 19:08:00,5.65 mi,15:15,1h 26m,86,15.250000
72,Adam Kimble,2016-04-10 22:15:00,3.09 mi,16:23,50m 40s,50,16.383333
71,Adam Kimble,2016-04-11 05:15:00,37.84 mi,16:42,10h 32m,632,16.700000
70,Adam Kimble,2016-04-12 00:10:00,5.52 mi,17:56,1h 39m,99,17.933333
69,Adam Kimble,2016-04-12 05:25:00,16.87 mi,20:37,5h 47m,347,20.616667
68,Adam Kimble,2016-04-12 12:31:00,10.00 mi,15:58,2h 39m,159,15.966667
67,Adam Kimble,2016-04-12 15:12:00,38.24 mi,11:29,7h 19m,439,11.483333
66,Adam Kimble,2016-04-13 08:25:00,49.52 mi,11:41,9h 38m,578,11.683333
65,Adam Kimble,2016-04-14 01:40:00,35.16 mi,11:16,6h 36m,396,11.266667

In [12]:
adam_summary['distance'] = adam_summary['distance'].str.replace('mi', '')
adam_summary

,name,date,distance,pace,duration,duration_sum,pace_fraction
16,Adam Kimble,2016-02-15 04:00:00,55.62,14:13,13h 10m,790,14.216667
15,Adam Kimble,2016-02-16 12:14:00,1.62,14:55,24m 17s,24,14.916667
14,Adam Kimble,2016-02-16 12:48:00,17.51,17:47,5h 11m,311,17.783333
13,Adam Kimble,2016-02-17 04:06:00,36.34,12:23,7h 30m,450,12.383333
12,Adam Kimble,2016-02-17 14:26:00,22.23,15:26,5h 43m,343,15.433333
11,Adam Kimble,2016-02-18 04:20:00,36.26,15:25,9h 18m,558,15.416667
10,Adam Kimble,2016-02-19 04:16:00,41.47,14:29,10h 0m,600,14.483333
9,Adam Kimble,2016-02-19 17:46:00,7.15,23:11,2h 45m,165,23.183333
8,Adam Kimble,2016-02-20 04:07:00,24.55,18:41,7h 38m,458,18.683333
7,Adam Kimble,2016-02-20 14:59:00,15.62,17:22,4h 31m,271,17.366667
6,Adam Kimble,2016-02-21 04:14:00,23.11,19:03,7h 20m,440,19.050000
5,Adam Kimble,2016-02-21 18:35:00,6.94,16:42,1h 56m,116,16.700000
4,Adam Kimble,2016-02-22 04:01:00,39.77,16:50,11h 9m,669,16.833333
3,Adam Kimble,2016-02-26 04:01:00,41.20,14:43,10h 6m,606,14.716667
2,Adam Kimble,2016-02-27 04:04:00,50.09,15:26,12h 52m,772,15.433333
1,Adam Kimble,2016-02-28 04:25:00,38.32,15:36,9h 57m,597,15.600000
0,Adam Kimble,2016-02-29 04:03:00,47.39,13:44,10h 51m,651,13.733333
64,Adam Kimble,2016-03-01 04:05:00,50.07,12:04,10h 3m,603,12.066667
63,Adam Kimble,2016-03-02 04:04:00,47.02,13:46,10h 47m,647,13.766667
62,Adam Kimble,2016-03-03 04:08:00,43.12,13:16,9h 32m,572,13.266667
61,Adam Kimble,2016-03-04 04:07:00,45.68,21:09,16h 6m,966,21.150000
60,Adam Kimble,2016-03-05 04:05:00,39.44,16:52,11h 5m,665,16.866667
59,Adam Kimble,2016-03-06 04:12:00,10.49,19:25,3h 23m,203,19.416667
58,Adam Kimble,2016-03-06 08:20:00,25.57,17:10,7h 19m,439,17.166667
57,Adam Kimble,2016-03-07 04:06:00,41.62,14:48,10h 15m,615,14.800000
56,Adam Kimble,2016-03-09 04:07:00,43.32,13:54,10h 2m,602,13.900000
55,Adam Kimble,2016-03-10 04:06:00,38.22,16:32,10h 32m,632,16.533333
54,Adam Kimble,2016-03-11 04:13:00,42.86,15:00,10h 43m,643,15.000000
53,Adam Kimble,2016-03-12 04:10:00,42.23,16:58,11h 56m,716,16.966667
52,Adam Kimble,2016-03-13 05:07:00,45.07,19:35,14h 43m,883,19.583333
...,...,...,...,...,...,...,...
29,Adam Kimble,2016-03-30 05:08:00,17.24,16:28,4h 43m,283,16.466667
28,Adam Kimble,2016-03-30 11:40:00,30.74,20:57,10h 44m,644,20.950000
27,Adam Kimble,2016-03-30 22:25:00,2.00,16:46,33m 36s,33,16.766667
26,Adam Kimble,2016-03-30 22:59:00,0.80,16:52,13m 29s,13,16.866667
25,Adam Kimble,2016-03-31 05:10:00,16.13,20:18,5h 27m,327,20.300000
24,Adam Kimble,2016-03-31 12:28:00,35.47,14:10,8h 22m,502,14.166667
88,Adam Kimble,2016-04-01 05:38:00,13.65,16:33,3h 45m,225,16.550000
87,Adam Kimble,2016-04-01 12:04:00,6.33,15:42,1h 39m,99,15.700000
86,Adam Kimble,2016-04-01 13:48:00,33.44,12:56,7h 12m,432,12.933333
85,Adam Kimble,2016-04-02 05:16:00,54.82,12:29,11h 24m,684,12.483333
84,Adam Kimble,2016-04-02 21:56:00,5.19,13:01,1h 7m,67,13.016667
83,Adam Kimble,2016-04-03 05:20:00,55.96,13:01,12h 8m,728,13.016667
82,Adam Kimble,2016-04-04 05:33:00,26.26,13:28,5h 53m,353,13.466667
81,Adam Kimble,2016-04-04 17:35:00,15.51,12:50,3h 19m,199,12.833333
80,Adam Kimble,2016-04-05 05:14:00,40.35,16:34,11h 8m,668,16.566667
79,Adam Kimble,2016-04-06 05:15:00,33.00,24:10,13h 17m,797,24.166667
78,Adam Kimble,2016-04-06 18:33:00,10.86,16:51,3h 2m,182,16.850000
77,Adam Kimble,2016-04-07 03:10:00,16.08,25:46,6h 54m,414,25.766667
76,Adam Kimble,2016-04-07 14:13:00,36.33,16:30,9h 59m,599,16.500000
75,Adam Kimble,2016-04-08 01:30:00,23.81,12:08,4h 48m,288,12.133333
74,Adam Kimble,2016-04-10 10:54:00,13.00,21:28,4h 39m,279,21.466667
73,Adam Kimble,2016-04-10 19:08:00,5.65,15:15,1h 26m,86,15.250000
72,Adam Kimble,2016-04-10 22:15:00,3.09,16:23,50m 40s,50,16.383333
71,Adam Kimble,2016-04-11 05:15:00,37.84,16:42,10h 32m,632,16.700000
70,Adam Kimble,2016-04-12 00:10:00,5.52,17:56,1h 39m,99,17.933333
69,Adam Kimble,2016-04-12 05:25:00,16.87,20:37,5h 47m,347,20.616667
68,Adam Kimble,2016-04-12 12:31:00,10.00,15:58,2h 39m,159,15.966667
67,Adam Kimble,2016-04-12 15:12:00,38.24,11:29,7h 19m,439,11.483333
66,Adam Kimble,2016-04-13 08:25:00,49.52,11:41,9h 38m,578,11.683333
65,Adam Kimble,2016-04-14 01:40:00,35.16,11:16,6h 36m,396,11.266667

In [13]:
#split dattime into 2 columns so I can grouby day
adam_summary['day'] = [d.date() for d in adam_summary['date']]
adam_summary['time'] = [d.time() for d in adam_summary['date']]

#convert to distance to number
adam_summary['distance']= pd.to_numeric(adam_summary['distance'], errors='coerce')
new = adam_summary.groupby(['day', 'name']).agg(['sum', 'mean'])[['distance', 'pace_fraction', 'duration_sum']].reset_index()
new.columns = new.columns.map('_'.join)
new.drop(['distance_mean', 'pace_fraction_sum', 'duration_sum_mean'], axis =1, inplace=True)
# new = new['day_', 'name_', 'distance_sum', 'pace_fraction_mean', 'duration_sum_sum']
new.columns = ['day', 'name', 'total_distance', 'avg_pace', 'duration']
adam_run_summary = new
adam_run_summary

           day         name  total_distance   avg_pace  duration
0   2016-02-15  Adam Kimble           55.62  14.216667       790
1   2016-02-16  Adam Kimble           19.13  16.350000       335
2   2016-02-17  Adam Kimble           58.57  13.908333       793
3   2016-02-18  Adam Kimble           36.26  15.416667       558
4   2016-02-19  Adam Kimble           48.62  18.833333       765
5   2016-02-20  Adam Kimble           40.17  18.025000       729
6   2016-02-21  Adam Kimble           30.05  17.875000       556
7   2016-02-22  Adam Kimble           39.77  16.833333       669
8   2016-02-26  Adam Kimble           41.20  14.716667       606
9   2016-02-27  Adam Kimble           50.09  15.433333       772
10  2016-02-28  Adam Kimble           38.32  15.600000       597
11  2016-02-29  Adam Kimble           47.39  13.733333       651
12  2016-03-01  Adam Kimble           50.07  12.066667       603
13  2016-03-02  Adam Kimble           47.02  13.766667       647
14  2016-03-03  Adam Kimble           43.12  13.266667       572
15  2016-03-04  Adam Kimble           45.68  21.150000       966
16  2016-03-05  Adam Kimble           39.44  16.866667       665
17  2016-03-06  Adam Kimble           36.06  18.291667       642
18  2016-03-07  Adam Kimble           41.62  14.800000       615
19  2016-03-09  Adam Kimble           43.32  13.900000       602
20  2016-03-10  Adam Kimble           38.22  16.533333       632
21  2016-03-11  Adam Kimble           42.86  15.000000       643
22  2016-03-12  Adam Kimble           42.23  16.966667       716
23  2016-03-13  Adam Kimble           45.07  19.583333       883
24  2016-03-14  Adam Kimble           24.68  17.650000       426
25  2016-03-15  Adam Kimble           50.19  13.800000       692
26  2016-03-16  Adam Kimble           50.30  13.550000       681
27  2016-03-17  Adam Kimble           50.41  12.583333       634
28  2016-03-18  Adam Kimble           50.11  12.900000       646
29  2016-03-19  Adam Kimble           50.14  14.466667       725
30  2016-03-20  Adam Kimble           44.29  12.905556       557
31  2016-03-21  Adam Kimble           48.55  11.866667       575
32  2016-03-22  Adam Kimble           51.51  11.750000       605
33  2016-03-23  Adam Kimble           55.06  12.466667       686
34  2016-03-24  Adam Kimble           43.53  16.266667       708
35  2016-03-25  Adam Kimble           26.01  17.908333       469
36  2016-03-26  Adam Kimble           41.08  17.033333       699
37  2016-03-27  Adam Kimble           45.04  16.608333       746
38  2016-03-28  Adam Kimble           28.66  17.175000       490
39  2016-03-29  Adam Kimble           46.56  17.066667       794
40  2016-03-30  Adam Kimble           50.78  17.762500       973
41  2016-03-31  Adam Kimble           51.60  17.233333       829
42  2016-04-01  Adam Kimble           53.42  15.061111       756
43  2016-04-02  Adam Kimble           60.01  12.750000       751
44  2016-04-03  Adam Kimble           55.96  13.016667       728
45  2016-04-04  Adam Kimble           41.77  13.150000       552
46  2016-04-05  Adam Kimble           40.35  16.566667       668
47  2016-04-06  Adam Kimble           43.86  20.508333       979
48  2016-04-07  Adam Kimble           52.41  21.133333      1013
49  2016-04-08  Adam Kimble           23.81  12.133333       288
50  2016-04-10  Adam Kimble           21.74  17.700000       415
51  2016-04-11  Adam Kimble           37.84  16.700000       632
52  2016-04-12  Adam Kimble           70.63  16.500000      1044
53  2016-04-13  Adam Kimble           49.52  11.683333       578
54  2016-04-14  Adam Kimble           35.16  11.266667       396

In [14]:
adam_run_summary.to_csv("adam_summary.csv")