In [1]:
import pandas as pd
import re
from bs4 import BeautifulSoup
from collections import Counter, defaultdict
import datetime

In [2]:
with open('/Users/snowr/ds_python1/running-America/gpx/activity_1174331104.gpx') as fp:
    soup = BeautifulSoup(fp, "html.parser")

In [14]:
points = soup.find_all('trkpt')
points[0]

<trkpt lat="40.45447228476405" lon="-78.5684338118881">
<ele>697.5999755859375</ele>
<time>2016-05-18T10:36:16.000Z</time>
<extensions>
<gpxtpx:trackpointextension>
<gpxtpx:atemp>27.0</gpxtpx:atemp>
</gpxtpx:trackpointextension>
</extensions>
</trkpt>

In [15]:
dir(soup)

['ASCII_SPACES',
 'DEFAULT_BUILDER_FEATURES',
 'HTML_FORMATTERS',
 'NO_PARSER_SPECIFIED_WARNING',
 'ROOT_TAG_NAME',
 'XML_FORMATTERS',
 '__bool__',
 '__call__',
 '__class__',
 '__contains__',
 '__copy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__unicode__',
 '__weakref__',
 '_all_strings',
 '_attr_value_as_string',
 '_attribute_checker',
 '_check_markup_is_url',
 '_feed',
 '_find_all',
 '_find_one',
 '_formatter_for_name',
 '_is_xml',
 '_lastRecursiveChild',
 '_last_descendant',
 '_most_recent_element',
 '_popToTag',
 '_select_debug',
 '_selector_combinators',
 '_should_pretty_print',
 '_tag_name_matches_and',
 'append',
 'attribselect_re',
 'attrs',
 'builder',
 'can_be_empty_element',
 'childGenerator',
 'children',
 'clear',
 'contains_replacement_characters',
 'contents',
 'currentTag',
 'current_data',
 'declared_html_encoding',
 'decode',
 'decode_contents',
 'decompose',
 'descendants',
 'encode',
 'encode_contents',
 'endData',
 'extract',
 'fetchNextSiblings',
 'fetchParents',
 'fetchPrevious',
 'fetchPreviousSiblings',
 'find',
 'findAll',
 'findAllNext',
 'findAllPrevious',
 'findChild',
 'findChildren',
 'findNext',
 'findNextSibling',
 'findNextSiblings',
 'findParent',
 'findParents',
 'findPrevious',
 'findPreviousSibling',
 'findPreviousSiblings',
 'find_all',
 'find_all_next',
 'find_all_previous',
 'find_next',
 'find_next_sibling',
 'find_next_siblings',
 'find_parent',
 'find_parents',
 'find_previous',
 'find_previous_sibling',
 'find_previous_siblings',
 'format_string',
 'get',
 'getText',
 'get_attribute_list',
 'get_text',
 'handle_data',
 'handle_endtag',
 'handle_starttag',
 'has_attr',
 'has_key',
 'hidden',
 'index',
 'insert',
 'insert_after',
 'insert_before',
 'isSelfClosing',
 'is_empty_element',
 'is_xml',
 'known_xml',
 'markup',
 'name',
 'namespace',
 'new_string',
 'new_tag',
 'next',
 'nextGenerator',
 'nextSibling',
 'nextSiblingGenerator',
 'next_element',
 'next_elements',
 'next_sibling',
 'next_siblings',
 'object_was_parsed',
 'original_encoding',
 'parent',
 'parentGenerator',
 'parents',
 'parse_only',
 'parserClass',
 'parser_class',
 'popTag',
 'prefix',
 'preserve_whitespace_tag_stack',
 'preserve_whitespace_tags',
 'prettify',
 'previous',
 'previousGenerator',
 'previousSibling',
 'previousSiblingGenerator',
 'previous_element',
 'previous_elements',
 'previous_sibling',
 'previous_siblings',
 'pushTag',
 'quoted_colon',
 'recursiveChildGenerator',
 'renderContents',
 'replaceWith',
 'replaceWithChildren',
 'replace_with',
 'replace_with_children',
 'reset',
 'select',
 'select_one',
 'setup',
 'string',
 'strings',
 'stripped_strings',
 'tagStack',
 'tag_name_re',
 'text',
 'unwrap',
 'wrap']

In [18]:
[item.get_text() for item in points[0].findChildren()]

['697.5999755859375',
 '2016-05-18T10:36:16.000Z',
 '\n\n27.0\n\n',
 '\n27.0\n',
 '27.0']

In [31]:
elev = [float(x.get_text()) for x in soup.find_all('ele')]
time = [x.get_text() for x in soup.find_all('time')][1:]
ll = [x.attrs for x in soup.find_all('trkpt')]

In [45]:
elev_time = list(zip(elev, time))
etll = list(zip (elev_time, ll))

In [46]:
df1 = pd.DataFrame.from_records(etll)
df.columns= ['elev', 'time', 'lat', 'long']
df.head()

,elev,time,lat,long
0,"[697.5999755859375, 697.5999755859375, 697.599...","{'lon': '-78.5684338118881', 'lat': '40.454472...","{'lon': '-78.56844747439027', 'lat': '40.45446...","[2016-05-18T10:36:16.000Z, 2016-05-18T10:37:28..."
1,"[697.5999755859375, 697.5999755859375, 697.599...","{'lon': '-78.5684338118881', 'lat': '40.454472...","{'lon': '-78.56844747439027', 'lat': '40.45446...","[2016-05-18T10:36:16.000Z, 2016-05-18T10:37:28..."
2,"[697.5999755859375, 697.5999755859375, 697.599...","{'lon': '-78.5684338118881', 'lat': '40.454472...","{'lon': '-78.56844747439027', 'lat': '40.45446...","[2016-05-18T10:36:16.000Z, 2016-05-18T10:37:28..."
3,"[697.5999755859375, 697.5999755859375, 697.599...","{'lon': '-78.5684338118881', 'lat': '40.454472...","{'lon': '-78.56844747439027', 'lat': '40.45446...","[2016-05-18T10:36:16.000Z, 2016-05-18T10:37:28..."
4,"[697.5999755859375, 697.5999755859375, 697.599...","{'lon': '-78.5684338118881', 'lat': '40.454472...","{'lon': '-78.56844747439027', 'lat': '40.45446...","[2016-05-18T10:36:16.000Z, 2016-05-18T10:37:28..."

In [35]:
df = pd.DataFrame.from_records(for_df)
df.head()

,elev,lat,lng,time
0,"[697.5999755859375, 697.5999755859375, 697.599...","{'lon': '-78.5684338118881', 'lat': '40.454472...","{'lon': '-78.56844747439027', 'lat': '40.45446...","[2016-05-18T10:36:16.000Z, 2016-05-18T10:37:28..."
1,"[697.5999755859375, 697.5999755859375, 697.599...","{'lon': '-78.5684338118881', 'lat': '40.454472...","{'lon': '-78.56844747439027', 'lat': '40.45446...","[2016-05-18T10:36:16.000Z, 2016-05-18T10:37:28..."
2,"[697.5999755859375, 697.5999755859375, 697.599...","{'lon': '-78.5684338118881', 'lat': '40.454472...","{'lon': '-78.56844747439027', 'lat': '40.45446...","[2016-05-18T10:36:16.000Z, 2016-05-18T10:37:28..."
3,"[697.5999755859375, 697.5999755859375, 697.599...","{'lon': '-78.5684338118881', 'lat': '40.454472...","{'lon': '-78.56844747439027', 'lat': '40.45446...","[2016-05-18T10:36:16.000Z, 2016-05-18T10:37:28..."
4,"[697.5999755859375, 697.5999755859375, 697.599...","{'lon': '-78.5684338118881', 'lat': '40.454472...","{'lon': '-78.56844747439027', 'lat': '40.45446...","[2016-05-18T10:36:16.000Z, 2016-05-18T10:37:28..."