### Adam Kimble Feb 16 - April 14 2016

In [1]:
import json
import pandas as pd
import os
import glob
from tqdm import tqdm
import re
from pandas.io.json import json_normalize
from datetime import datetime
import numpy as np

In [2]:
json_ll = glob.glob("/Users/snowr/ds_python1/running-America/vru_retry/Adam_json_files/AK_latlng/*.json")
json_as = glob.glob("/Users/snowr/ds_python1/running-America/vru_retry/Adam_json_files/AK_stats/*.json")

assert(len(json_ll) == len(json_as))

for_df = []

keys = [re.findall(r'\d{5,}' , x.split("/")[-1])[0] for x in json_ll]

# goal: join the files based on their id

def get_my_dict_from_the_file(the_file_path):
    # returns a dictionary
    with open(the_file_path, 'r') as f:
        data = eval(f.read())
        return data

# below will give a list of dicts within for_df (list). I'll need to concat them all using pd.concat(axis=1?)

for key in tqdm(keys):
    # get the matching ll file
    # get the matching activity file
    # get the date later!
    
    matching_ll_file = [x for x in json_ll if key in x][0]
    matching_as_file = [x for x in json_as if key in x][0]
    
    #print(key, matching_ll_file, matching_as_file)
    ll_dict = get_my_dict_from_the_file(matching_ll_file)
    activity_dict = get_my_dict_from_the_file(matching_as_file)
    merged_dict = {**ll_dict, **activity_dict}
    merged_dict['activity_id'] = key
    print(merged_dict.keys())
    for_df.append(merged_dict)
    
    
pd.DataFrame.from_records(merged_dict).shape

  0%|                                                                                           | 0/88 [00:00<?, ?it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

  1%|▉                                                                                  | 1/88 [00:00<00:09,  9.12it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

  5%|███▊                                                                               | 4/88 [00:00<00:07, 10.95it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

  7%|█████▋                                                                             | 6/88 [00:00<00:06, 12.61it/s]

dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 10%|████████▍                                                                          | 9/88 [00:00<00:05, 14.91it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 12%|██████████▎                                                                       | 11/88 [00:00<00:04, 15.70it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 15%|████████████                                                                      | 13/88 [00:00<00:04, 16.71it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 17%|█████████████▉                                                                    | 15/88 [00:00<00:04, 14.63it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 19%|███████████████▊                                                                  | 17/88 [00:01<00:05, 13.71it/s]

dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 23%|██████████████████▋                                                               | 20/88 [00:01<00:04, 14.67it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 25%|████████████████████▌                                                             | 22/88 [00:01<00:04, 14.51it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 27%|██████████████████████▎                                                           | 24/88 [00:01<00:04, 14.78it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 31%|█████████████████████████▏                                                        | 27/88 [00:01<00:03, 15.36it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 33%|███████████████████████████                                                       | 29/88 [00:01<00:03, 14.99it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 35%|████████████████████████████▉                                                     | 31/88 [00:01<00:03, 14.78it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 39%|███████████████████████████████▋                                                  | 34/88 [00:02<00:03, 16.69it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 41%|█████████████████████████████████▌                                                | 36/88 [00:02<00:03, 15.00it/s]

dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 43%|███████████████████████████████████▍                                              | 38/88 [00:02<00:03, 13.86it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 45%|█████████████████████████████████████▎                                            | 40/88 [00:02<00:03, 13.83it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 48%|███████████████████████████████████████▏                                          | 42/88 [00:02<00:03, 15.11it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 50%|█████████████████████████████████████████                                         | 44/88 [00:02<00:02, 15.49it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 52%|██████████████████████████████████████████▊                                       | 46/88 [00:02<00:03, 13.94it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 55%|████████████████████████████████████████████▋                                     | 48/88 [00:03<00:02, 15.22it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 58%|███████████████████████████████████████████████▌                                  | 51/88 [00:03<00:02, 17.78it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 61%|██████████████████████████████████████████████████▎                               | 54/88 [00:03<00:01, 19.54it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 66%|██████████████████████████████████████████████████████                            | 58/88 [00:03<00:01, 23.07it/s]

dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 70%|█████████████████████████████████████████████████████████▊                        | 62/88 [00:03<00:01, 23.71it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 74%|████████████████████████████████████████████████████████████▌                     | 65/88 [00:03<00:01, 22.52it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 77%|███████████████████████████████████████████████████████████████▎                  | 68/88 [00:03<00:01, 19.66it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 81%|██████████████████████████████████████████████████████████████████▏               | 71/88 [00:04<00:00, 20.26it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 86%|██████████████████████████████████████████████████████████████████████▊           | 76/88 [00:04<00:00, 24.59it/s]

dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 90%|█████████████████████████████████████████████████████████████████████████▌        | 79/88 [00:04<00:00, 23.17it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'timer_time', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 94%|█████████████████████████████████████████████████████████████████████████████▎    | 83/88 [00:04<00:00, 25.17it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

 98%|████████████████████████████████████████████████████████████████████████████████▏ | 86/88 [00:04<00:00, 24.33it/s]

dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])
dict_keys(['latlng', 'time', 'distance', 'altitude', 'cadence', 'grade_adjusted_distance', 'grade_smooth', 'activity_id'])

100%|██████████████████████████████████████████████████████████████████████████████████| 88/88 [00:04<00:00, 19.38it/s]

(472, 8)

In [3]:
out = pd.concat([pd.DataFrame.from_records(x) for x in for_df], axis=0)
out

,activity_id,altitude,cadence,distance,grade_adjusted_distance,grade_smooth,latlng,time,timer_time
0,494499582,4.4,0,0.0,0.0,4.5,"[33.656636, -118.002546]",0,NaN
1,494499582,5.6,60,4.9,5.4,2.5,"[33.656671, -118.002513]",5,NaN
2,494499582,5.6,78,26.4,28.5,1.7,"[33.656823, -118.002371]",11,NaN
3,494499582,5.6,79,47.6,49.7,0.0,"[33.656978, -118.002238]",17,NaN
4,494499582,5.6,78,68.8,72.2,1.4,"[33.657159, -118.002165]",24,NaN
5,494499582,5.6,78,90.0,93.4,0.0,"[33.657331, -118.002078]",31,NaN
6,494499582,6.6,78,96.2,99.8,0.7,"[33.657381, -118.002109]",33,NaN
7,494499582,5.6,80,106.0,109.7,0.3,"[33.657441, -118.002186]",36,NaN
8,494499582,6.0,80,126.3,129.4,-0.8,"[33.65756, -118.002351]",43,NaN
9,494499582,5.8,81,147.4,150.9,0.5,"[33.65768, -118.002528]",50,NaN
10,494499582,6.0,81,169.8,173.5,0.2,"[33.657793, -118.002731]",57,NaN
11,494499582,6.0,80,191.1,195.0,0.2,"[33.657916, -118.002908]",64,NaN
12,494499582,6.2,81,211.3,215.4,0.2,"[33.658038, -118.003069]",71,NaN
13,494499582,6.0,81,231.5,235.6,0.0,"[33.658162, -118.003229]",78,NaN
14,494499582,6.2,80,252.6,256.5,-0.2,"[33.658295, -118.003392]",85,NaN
15,494499582,6.0,80,275.4,280.2,1.0,"[33.658472, -118.003353]",92,NaN
16,494499582,6.0,81,296.8,301.2,-0.5,"[33.658624, -118.003209]",99,NaN
17,494499582,6.8,80,313.7,318.1,0.0,"[33.65874, -118.003091]",105,NaN
18,494499582,5.8,79,332.7,337.1,0.0,"[33.658874, -118.002965]",112,NaN
19,494499582,6.0,79,355.4,358.5,-1.4,"[33.659037, -118.002815]",120,NaN
20,494499582,6.0,81,376.0,379.3,0.2,"[33.659179, -118.002671]",127,NaN
21,494499582,5.6,81,398.8,402.3,0.2,"[33.659328, -118.0025]",135,NaN
22,494499582,6.0,81,420.8,424.3,0.0,"[33.659481, -118.00235]",143,NaN
23,494499582,6.2,81,443.4,447.6,0.7,"[33.65963, -118.002185]",151,NaN
24,494499582,6.0,80,465.6,470.4,0.7,"[33.659782, -118.002028]",159,NaN
25,494499582,6.2,81,486.2,491.4,0.5,"[33.659919, -118.001878]",167,NaN
26,494499582,6.6,80,506.3,512.5,1.2,"[33.660063, -118.001746]",174,NaN
27,494499582,6.6,80,528.3,535.3,0.9,"[33.660219, -118.001599]",182,NaN
28,494499582,6.8,81,533.8,540.9,0.3,"[33.660257, -118.001563]",184,NaN
29,494499582,6.8,80,554.0,561.5,0.6,"[33.660409, -118.001442]",191,NaN
...,...,...,...,...,...,...,...,...,...
442,697225815,69.8,59,7793.1,7855.2,0.7,"[32.546299, -93.02803]",5134,NaN
443,697225815,70.0,59,7813.5,7875.9,0.4,"[32.546286, -93.027813]",5147,NaN
444,697225815,70.1,60,7834.8,7897.5,0.2,"[32.546272, -93.027588]",5160,NaN
445,697225815,70.2,59,7855.0,7917.6,-0.1,"[32.546267, -93.027374]",5173,NaN
446,697225815,70.0,59,7875.4,7937.9,-0.1,"[32.546273, -93.027157]",5186,NaN
447,697225815,69.9,59,7896.4,7958.8,-0.1,"[32.546281, -93.026935]",5199,NaN
448,697225815,70.0,60,7916.8,7979.3,0.1,"[32.546276, -93.026719]",5212,NaN
449,697225815,70.1,59,7937.8,8000.6,0.4,"[32.54627, -93.026496]",5225,NaN
450,697225815,70.1,59,7957.9,8020.9,0.3,"[32.546265, -93.026273]",5238,NaN
451,697225815,70.2,59,7974.7,8038.0,0.3,"[32.54626, -93.026094]",5249,NaN
452,697225815,70.2,59,7981.4,8044.8,0.5,"[32.546263, -93.026023]",5253,NaN
453,697225815,70.3,59,8001.6,8065.4,0.5,"[32.546252, -93.025809]",5266,NaN
454,697225815,70.4,62,8022.4,8086.6,0.5,"[32.546267, -93.025589]",5279,NaN
455,697225815,70.5,59,8039.6,8103.9,0.2,"[32.546254, -93.025404]",5290,NaN
456,697225815,70.5,59,8047.8,8112.3,0.6,"[32.546254, -93.025317]",5295,NaN
457,697225815,70.4,61,8051.4,8116.0,0.6,"[32.546255, -93.025279]",5297,NaN
458,697225815,70.7,59,8071.9,8137.1,0.8,"[32.54623, -93.025062]",5310,NaN
459,697225815,70.8,59,8093.0,8159.2,1.1,"[32.546248, -93.024839]",5323,NaN
460,697225815,71.0,59,8113.1,8180.0,0.8,"[32.546249, -93.024626]",5336,NaN
461,697225815,71.3,59,8133.7,8202.1,1.7,"[32.546256, -93.024408]",5349,NaN
462,697225815,71.4,59,8155.0,8225.2,2.0,"[32.546248, -93.02418]",5363,NaN
463,697225815,72.2,59,8175.7,8247.6,1.9,"[32.546186, -93.023974]",5376,NaN
464,697225815,72.7,59,8196.4,8270.3,2.2,"[32.546159, -93.023758]",5389,NaN
465,697225815,72.9,59,8216.8,8291.8,1.3,"[32.546153, -93.023542]",5403,NaN
466,697225815,73.1,59,8230.6,8306.2,0.9,"[32.546137, -93.023396]",5412,NaN
467,697225815,73.2,59,8251.3,8327.7,1.0,"[32.546156, -93.023177]",5426,NaN
468,697225815,73.4,59,8272.2,8349.4,0.9,"[32.546132, -93.022957]",5440,NaN
469,697225815,73.5,0,8276.2,8353.6,1.1,"[32.54613, -93.022914]",5443,NaN
470,697225815,73.6,0,8284.3,8362.2,1.4,"[32.546128, -93.022828]",5452,NaN
471,697225815,73.6,0,8286.1,8364.1,1.0,"[32.546139, -93.022825]",5463,NaN

In [29]:
out.activity_id.value_counts()

524307075    5135
525892661    5111
494499582    5098
519172291    4950
535280762    4858
535280832    4749
522262002    4626
520571455    4607
520571447    4594
508043953    4491
515429710    4442
520571517    4406
524230100    4393
504055591    4239
507365948    4229
519873532    4228
508043987    4220
513829363    4193
526043128    4157
512938866    4103
665896978    4080
508783062    4061
511344524    4022
530869714    3963
512176693    3801
502445008    3777
514613172    3734
530811635    3716
497492517    3692
508089244    3613
             ...
519023776    1463
530869754    1452
498361372    1437
526715765    1410
536105308    1350
535280680    1287
541880889    1213
522262006    1046
530869297    1036
538033890    1032
526715807     961
522261985     926
543492611     881
510147857     875
497471627     805
516805338     760
508043913     730
499382802     626
535280676     557
530811654     509
541880903     495
543185531     476
697225815     472
697223180     450
534112040     427
697224327     353
541921416     289
531383706     179
495086811     160
531383715      79
Name: activity_id, Length: 88, dtype: int64

In [55]:
#add date
#convert to datetime object
#merge with out dataframe

with open('/Users/snowr/ds_python1/running-America/vru_retry/Adam_json_files/ak_date.json', encoding="utf8") as f:
    data = json.load(f)
    
df_date = pd.DataFrame.from_dict(json_normalize(data), orient='columns')
df_date = df_date.T
df_date

#save to csv, flatten, reload
# df_date.to_csv("ak_date_activity.csv")

df_date = pd.read_csv("/Users/snowr/ds_python1/running-America/vru_retry/Adam_json_files/ak_date_activity.csv", parse_dates=True)

# df_date['activity'] = df_date['activity'].astype(object)
df_date

     activity       date
0   494499582  2/15/2016
1   495086811  2/16/2016
2   495293794  2/16/2016
3   495928847  2/17/2016
4   496088320  2/17/2016
5   496741568  2/18/2016
6   497471627  2/19/2016
7   497492517  2/19/2016
8   498361372  2/20/2016
9   498362296  2/20/2016
10  499382800  2/21/2016
11  499382802  2/21/2016
12  502445008  2/22/2016
13  503121816  2/26/2016
14  504055591  2/27/2016
15  507365948   3/2/2016
16  507376305   3/2/2016
17  508043913  2/28/2016
18  508043920  2/28/2016
19  508043953  2/29/2016
20  508043987   3/1/2016
21  508089244   3/3/2016
22  508783062   3/4/2016
23  509988006   3/5/2016
24  510147857   3/6/2016
25  511342683   3/6/2016
26  511344524   3/7/2016
27  512176693   3/8/2016
28  512938866   3/9/2016
29  513829363  3/10/2016
..        ...        ...
59  534112040   4/2/2016
60  535280602  3/31/2016
61  535280659  3/31/2016
62  535280676   4/1/2016
63  535280680   4/1/2016
64  535280710   4/1/2016
65  535280762   4/2/2016
66  535280832   4/3/2016
67  535839351   4/4/2016
68  536105308   4/4/2016
69  538033775   4/6/2016
70  538033883   4/5/2016
71  538033890   4/6/2016
72  539126361   4/8/2016
73  541880889  4/10/2016
74  541880903  4/10/2016
75  541921416  4/10/2016
76  542805485   4/7/2016
77  542805505   4/7/2016
78  542805533  4/11/2016
79  543185531  4/12/2016
80  543185564  4/12/2016
81  543492611  4/12/2016
82  543875984  4/12/2016
83  545239959  4/14/2016
84  556964500  2/16/2016
85  665896978  4/13/2016
86  697223180  3/14/2016
87  697224327  3/20/2016
88  697225815  3/27/2016

[89 rows x 2 columns]

In [56]:
#checks variable type of activity_id, changes to integer if needed
out['activity_id'] = out.activity_id.apply(lambda x: x if isinstance(x, int) else eval(x))

In [57]:
#check unique values in each
unique_out = out.activity_id.unique()
df_unique = df_date.activity.unique()
b =[x for x in df_unique if x in unique_out]
len(b)

88

In [58]:
stats_date_ak = pd.merge(out, df_date, left_on="activity_id", right_on='activity')
# stats_date_ak.drop('activity', axis=1)
stats_date_ak

,activity_id,altitude,cadence,distance,grade_adjusted_distance,grade_smooth,latlng,time,timer_time,activity,date
0,494499582,4.4,0,0.0,0.0,4.5,"[33.656636, -118.002546]",0,NaN,494499582,2/15/2016
1,494499582,5.6,60,4.9,5.4,2.5,"[33.656671, -118.002513]",5,NaN,494499582,2/15/2016
2,494499582,5.6,78,26.4,28.5,1.7,"[33.656823, -118.002371]",11,NaN,494499582,2/15/2016
3,494499582,5.6,79,47.6,49.7,0.0,"[33.656978, -118.002238]",17,NaN,494499582,2/15/2016
4,494499582,5.6,78,68.8,72.2,1.4,"[33.657159, -118.002165]",24,NaN,494499582,2/15/2016
5,494499582,5.6,78,90.0,93.4,0.0,"[33.657331, -118.002078]",31,NaN,494499582,2/15/2016
6,494499582,6.6,78,96.2,99.8,0.7,"[33.657381, -118.002109]",33,NaN,494499582,2/15/2016
7,494499582,5.6,80,106.0,109.7,0.3,"[33.657441, -118.002186]",36,NaN,494499582,2/15/2016
8,494499582,6.0,80,126.3,129.4,-0.8,"[33.65756, -118.002351]",43,NaN,494499582,2/15/2016
9,494499582,5.8,81,147.4,150.9,0.5,"[33.65768, -118.002528]",50,NaN,494499582,2/15/2016
10,494499582,6.0,81,169.8,173.5,0.2,"[33.657793, -118.002731]",57,NaN,494499582,2/15/2016
11,494499582,6.0,80,191.1,195.0,0.2,"[33.657916, -118.002908]",64,NaN,494499582,2/15/2016
12,494499582,6.2,81,211.3,215.4,0.2,"[33.658038, -118.003069]",71,NaN,494499582,2/15/2016
13,494499582,6.0,81,231.5,235.6,0.0,"[33.658162, -118.003229]",78,NaN,494499582,2/15/2016
14,494499582,6.2,80,252.6,256.5,-0.2,"[33.658295, -118.003392]",85,NaN,494499582,2/15/2016
15,494499582,6.0,80,275.4,280.2,1.0,"[33.658472, -118.003353]",92,NaN,494499582,2/15/2016
16,494499582,6.0,81,296.8,301.2,-0.5,"[33.658624, -118.003209]",99,NaN,494499582,2/15/2016
17,494499582,6.8,80,313.7,318.1,0.0,"[33.65874, -118.003091]",105,NaN,494499582,2/15/2016
18,494499582,5.8,79,332.7,337.1,0.0,"[33.658874, -118.002965]",112,NaN,494499582,2/15/2016
19,494499582,6.0,79,355.4,358.5,-1.4,"[33.659037, -118.002815]",120,NaN,494499582,2/15/2016
20,494499582,6.0,81,376.0,379.3,0.2,"[33.659179, -118.002671]",127,NaN,494499582,2/15/2016
21,494499582,5.6,81,398.8,402.3,0.2,"[33.659328, -118.0025]",135,NaN,494499582,2/15/2016
22,494499582,6.0,81,420.8,424.3,0.0,"[33.659481, -118.00235]",143,NaN,494499582,2/15/2016
23,494499582,6.2,81,443.4,447.6,0.7,"[33.65963, -118.002185]",151,NaN,494499582,2/15/2016
24,494499582,6.0,80,465.6,470.4,0.7,"[33.659782, -118.002028]",159,NaN,494499582,2/15/2016
25,494499582,6.2,81,486.2,491.4,0.5,"[33.659919, -118.001878]",167,NaN,494499582,2/15/2016
26,494499582,6.6,80,506.3,512.5,1.2,"[33.660063, -118.001746]",174,NaN,494499582,2/15/2016
27,494499582,6.6,80,528.3,535.3,0.9,"[33.660219, -118.001599]",182,NaN,494499582,2/15/2016
28,494499582,6.8,81,533.8,540.9,0.3,"[33.660257, -118.001563]",184,NaN,494499582,2/15/2016
29,494499582,6.8,80,554.0,561.5,0.6,"[33.660409, -118.001442]",191,NaN,494499582,2/15/2016
...,...,...,...,...,...,...,...,...,...,...,...
229481,697225815,69.8,59,7793.1,7855.2,0.7,"[32.546299, -93.02803]",5134,NaN,697225815,3/27/2016
229482,697225815,70.0,59,7813.5,7875.9,0.4,"[32.546286, -93.027813]",5147,NaN,697225815,3/27/2016
229483,697225815,70.1,60,7834.8,7897.5,0.2,"[32.546272, -93.027588]",5160,NaN,697225815,3/27/2016
229484,697225815,70.2,59,7855.0,7917.6,-0.1,"[32.546267, -93.027374]",5173,NaN,697225815,3/27/2016
229485,697225815,70.0,59,7875.4,7937.9,-0.1,"[32.546273, -93.027157]",5186,NaN,697225815,3/27/2016
229486,697225815,69.9,59,7896.4,7958.8,-0.1,"[32.546281, -93.026935]",5199,NaN,697225815,3/27/2016
229487,697225815,70.0,60,7916.8,7979.3,0.1,"[32.546276, -93.026719]",5212,NaN,697225815,3/27/2016
229488,697225815,70.1,59,7937.8,8000.6,0.4,"[32.54627, -93.026496]",5225,NaN,697225815,3/27/2016
229489,697225815,70.1,59,7957.9,8020.9,0.3,"[32.546265, -93.026273]",5238,NaN,697225815,3/27/2016
229490,697225815,70.2,59,7974.7,8038.0,0.3,"[32.54626, -93.026094]",5249,NaN,697225815,3/27/2016
229491,697225815,70.2,59,7981.4,8044.8,0.5,"[32.546263, -93.026023]",5253,NaN,697225815,3/27/2016
229492,697225815,70.3,59,8001.6,8065.4,0.5,"[32.546252, -93.025809]",5266,NaN,697225815,3/27/2016
229493,697225815,70.4,62,8022.4,8086.6,0.5,"[32.546267, -93.025589]",5279,NaN,697225815,3/27/2016
229494,697225815,70.5,59,8039.6,8103.9,0.2,"[32.546254, -93.025404]",5290,NaN,697225815,3/27/2016
229495,697225815,70.5,59,8047.8,8112.3,0.6,"[32.546254, -93.025317]",5295,NaN,697225815,3/27/2016
229496,697225815,70.4,61,8051.4,8116.0,0.6,"[32.546255, -93.025279]",5297,NaN,697225815,3/27/2016
229497,697225815,70.7,59,8071.9,8137.1,0.8,"[32.54623, -93.025062]",5310,NaN,697225815,3/27/2016
229498,697225815,70.8,59,8093.0,8159.2,1.1,"[32.546248, -93.024839]",5323,NaN,697225815,3/27/2016
229499,697225815,71.0,59,8113.1,8180.0,0.8,"[32.546249, -93.024626]",5336,NaN,697225815,3/27/2016
229500,697225815,71.3,59,8133.7,8202.1,1.7,"[32.546256, -93.024408]",5349,NaN,697225815,3/27/2016
229501,697225815,71.4,59,8155.0,8225.2,2.0,"[32.546248, -93.02418]",5363,NaN,697225815,3/27/2016
229502,697225815,72.2,59,8175.7,8247.6,1.9,"[32.546186, -93.023974]",5376,NaN,697225815,3/27/2016
229503,697225815,72.7,59,8196.4,8270.3,2.2,"[32.546159, -93.023758]",5389,NaN,697225815,3/27/2016
229504,697225815,72.9,59,8216.8,8291.8,1.3,"[32.546153, -93.023542]",5403,NaN,697225815,3/27/2016
229505,697225815,73.1,59,8230.6,8306.2,0.9,"[32.546137, -93.023396]",5412,NaN,697225815,3/27/2016
229506,697225815,73.2,59,8251.3,8327.7,1.0,"[32.546156, -93.023177]",5426,NaN,697225815,3/27/2016
229507,697225815,73.4,59,8272.2,8349.4,0.9,"[32.546132, -93.022957]",5440,NaN,697225815,3/27/2016
229508,697225815,73.5,0,8276.2,8353.6,1.1,"[32.54613, -93.022914]",5443,NaN,697225815,3/27/2016
229509,697225815,73.6,0,8284.3,8362.2,1.4,"[32.546128, -93.022828]",5452,NaN,697225815,3/27/2016
229510,697225815,73.6,0,8286.1,8364.1,1.0,"[32.546139, -93.022825]",5463,NaN,697225815,3/27/2016

In [59]:
#convert to dattime object
stats_date_ak['date'] =pd.to_datetime(stats_date_ak['date'], errors='coerce')
stats_date_ak= stats_date_ak.drop('activity', axis = 1)

In [60]:
#filter the data for run dates
adam_run = stats_date_ak[(stats_date_ak['date'] > '2016-02-14') & (stats_date_ak['date'] < '2016-04-15')]
adam_run

,activity_id,altitude,cadence,distance,grade_adjusted_distance,grade_smooth,latlng,time,timer_time,date
0,494499582,4.4,0,0.0,0.0,4.5,"[33.656636, -118.002546]",0,NaN,2016-02-15
1,494499582,5.6,60,4.9,5.4,2.5,"[33.656671, -118.002513]",5,NaN,2016-02-15
2,494499582,5.6,78,26.4,28.5,1.7,"[33.656823, -118.002371]",11,NaN,2016-02-15
3,494499582,5.6,79,47.6,49.7,0.0,"[33.656978, -118.002238]",17,NaN,2016-02-15
4,494499582,5.6,78,68.8,72.2,1.4,"[33.657159, -118.002165]",24,NaN,2016-02-15
5,494499582,5.6,78,90.0,93.4,0.0,"[33.657331, -118.002078]",31,NaN,2016-02-15
6,494499582,6.6,78,96.2,99.8,0.7,"[33.657381, -118.002109]",33,NaN,2016-02-15
7,494499582,5.6,80,106.0,109.7,0.3,"[33.657441, -118.002186]",36,NaN,2016-02-15
8,494499582,6.0,80,126.3,129.4,-0.8,"[33.65756, -118.002351]",43,NaN,2016-02-15
9,494499582,5.8,81,147.4,150.9,0.5,"[33.65768, -118.002528]",50,NaN,2016-02-15
10,494499582,6.0,81,169.8,173.5,0.2,"[33.657793, -118.002731]",57,NaN,2016-02-15
11,494499582,6.0,80,191.1,195.0,0.2,"[33.657916, -118.002908]",64,NaN,2016-02-15
12,494499582,6.2,81,211.3,215.4,0.2,"[33.658038, -118.003069]",71,NaN,2016-02-15
13,494499582,6.0,81,231.5,235.6,0.0,"[33.658162, -118.003229]",78,NaN,2016-02-15
14,494499582,6.2,80,252.6,256.5,-0.2,"[33.658295, -118.003392]",85,NaN,2016-02-15
15,494499582,6.0,80,275.4,280.2,1.0,"[33.658472, -118.003353]",92,NaN,2016-02-15
16,494499582,6.0,81,296.8,301.2,-0.5,"[33.658624, -118.003209]",99,NaN,2016-02-15
17,494499582,6.8,80,313.7,318.1,0.0,"[33.65874, -118.003091]",105,NaN,2016-02-15
18,494499582,5.8,79,332.7,337.1,0.0,"[33.658874, -118.002965]",112,NaN,2016-02-15
19,494499582,6.0,79,355.4,358.5,-1.4,"[33.659037, -118.002815]",120,NaN,2016-02-15
20,494499582,6.0,81,376.0,379.3,0.2,"[33.659179, -118.002671]",127,NaN,2016-02-15
21,494499582,5.6,81,398.8,402.3,0.2,"[33.659328, -118.0025]",135,NaN,2016-02-15
22,494499582,6.0,81,420.8,424.3,0.0,"[33.659481, -118.00235]",143,NaN,2016-02-15
23,494499582,6.2,81,443.4,447.6,0.7,"[33.65963, -118.002185]",151,NaN,2016-02-15
24,494499582,6.0,80,465.6,470.4,0.7,"[33.659782, -118.002028]",159,NaN,2016-02-15
25,494499582,6.2,81,486.2,491.4,0.5,"[33.659919, -118.001878]",167,NaN,2016-02-15
26,494499582,6.6,80,506.3,512.5,1.2,"[33.660063, -118.001746]",174,NaN,2016-02-15
27,494499582,6.6,80,528.3,535.3,0.9,"[33.660219, -118.001599]",182,NaN,2016-02-15
28,494499582,6.8,81,533.8,540.9,0.3,"[33.660257, -118.001563]",184,NaN,2016-02-15
29,494499582,6.8,80,554.0,561.5,0.6,"[33.660409, -118.001442]",191,NaN,2016-02-15
...,...,...,...,...,...,...,...,...,...,...
229481,697225815,69.8,59,7793.1,7855.2,0.7,"[32.546299, -93.02803]",5134,NaN,2016-03-27
229482,697225815,70.0,59,7813.5,7875.9,0.4,"[32.546286, -93.027813]",5147,NaN,2016-03-27
229483,697225815,70.1,60,7834.8,7897.5,0.2,"[32.546272, -93.027588]",5160,NaN,2016-03-27
229484,697225815,70.2,59,7855.0,7917.6,-0.1,"[32.546267, -93.027374]",5173,NaN,2016-03-27
229485,697225815,70.0,59,7875.4,7937.9,-0.1,"[32.546273, -93.027157]",5186,NaN,2016-03-27
229486,697225815,69.9,59,7896.4,7958.8,-0.1,"[32.546281, -93.026935]",5199,NaN,2016-03-27
229487,697225815,70.0,60,7916.8,7979.3,0.1,"[32.546276, -93.026719]",5212,NaN,2016-03-27
229488,697225815,70.1,59,7937.8,8000.6,0.4,"[32.54627, -93.026496]",5225,NaN,2016-03-27
229489,697225815,70.1,59,7957.9,8020.9,0.3,"[32.546265, -93.026273]",5238,NaN,2016-03-27
229490,697225815,70.2,59,7974.7,8038.0,0.3,"[32.54626, -93.026094]",5249,NaN,2016-03-27
229491,697225815,70.2,59,7981.4,8044.8,0.5,"[32.546263, -93.026023]",5253,NaN,2016-03-27
229492,697225815,70.3,59,8001.6,8065.4,0.5,"[32.546252, -93.025809]",5266,NaN,2016-03-27
229493,697225815,70.4,62,8022.4,8086.6,0.5,"[32.546267, -93.025589]",5279,NaN,2016-03-27
229494,697225815,70.5,59,8039.6,8103.9,0.2,"[32.546254, -93.025404]",5290,NaN,2016-03-27
229495,697225815,70.5,59,8047.8,8112.3,0.6,"[32.546254, -93.025317]",5295,NaN,2016-03-27
229496,697225815,70.4,61,8051.4,8116.0,0.6,"[32.546255, -93.025279]",5297,NaN,2016-03-27
229497,697225815,70.7,59,8071.9,8137.1,0.8,"[32.54623, -93.025062]",5310,NaN,2016-03-27
229498,697225815,70.8,59,8093.0,8159.2,1.1,"[32.546248, -93.024839]",5323,NaN,2016-03-27
229499,697225815,71.0,59,8113.1,8180.0,0.8,"[32.546249, -93.024626]",5336,NaN,2016-03-27
229500,697225815,71.3,59,8133.7,8202.1,1.7,"[32.546256, -93.024408]",5349,NaN,2016-03-27
229501,697225815,71.4,59,8155.0,8225.2,2.0,"[32.546248, -93.02418]",5363,NaN,2016-03-27
229502,697225815,72.2,59,8175.7,8247.6,1.9,"[32.546186, -93.023974]",5376,NaN,2016-03-27
229503,697225815,72.7,59,8196.4,8270.3,2.2,"[32.546159, -93.023758]",5389,NaN,2016-03-27
229504,697225815,72.9,59,8216.8,8291.8,1.3,"[32.546153, -93.023542]",5403,NaN,2016-03-27
229505,697225815,73.1,59,8230.6,8306.2,0.9,"[32.546137, -93.023396]",5412,NaN,2016-03-27
229506,697225815,73.2,59,8251.3,8327.7,1.0,"[32.546156, -93.023177]",5426,NaN,2016-03-27
229507,697225815,73.4,59,8272.2,8349.4,0.9,"[32.546132, -93.022957]",5440,NaN,2016-03-27
229508,697225815,73.5,0,8276.2,8353.6,1.1,"[32.54613, -93.022914]",5443,NaN,2016-03-27
229509,697225815,73.6,0,8284.3,8362.2,1.4,"[32.546128, -93.022828]",5452,NaN,2016-03-27
229510,697225815,73.6,0,8286.1,8364.1,1.0,"[32.546139, -93.022825]",5463,NaN,2016-03-27

In [61]:
len(adam_run['date'].unique())

56

In [62]:
adam_run['lat'] = adam_run['latlng'].apply(lambda x: x[0])
adam_run['long'] = adam_run['latlng'].apply(lambda x: x[1])
adam_run

,activity_id,altitude,cadence,distance,grade_adjusted_distance,grade_smooth,latlng,time,timer_time,date,lat,long
0,494499582,4.4,0,0.0,0.0,4.5,"[33.656636, -118.002546]",0,NaN,2016-02-15,33.656636,-118.002546
1,494499582,5.6,60,4.9,5.4,2.5,"[33.656671, -118.002513]",5,NaN,2016-02-15,33.656671,-118.002513
2,494499582,5.6,78,26.4,28.5,1.7,"[33.656823, -118.002371]",11,NaN,2016-02-15,33.656823,-118.002371
3,494499582,5.6,79,47.6,49.7,0.0,"[33.656978, -118.002238]",17,NaN,2016-02-15,33.656978,-118.002238
4,494499582,5.6,78,68.8,72.2,1.4,"[33.657159, -118.002165]",24,NaN,2016-02-15,33.657159,-118.002165
5,494499582,5.6,78,90.0,93.4,0.0,"[33.657331, -118.002078]",31,NaN,2016-02-15,33.657331,-118.002078
6,494499582,6.6,78,96.2,99.8,0.7,"[33.657381, -118.002109]",33,NaN,2016-02-15,33.657381,-118.002109
7,494499582,5.6,80,106.0,109.7,0.3,"[33.657441, -118.002186]",36,NaN,2016-02-15,33.657441,-118.002186
8,494499582,6.0,80,126.3,129.4,-0.8,"[33.65756, -118.002351]",43,NaN,2016-02-15,33.657560,-118.002351
9,494499582,5.8,81,147.4,150.9,0.5,"[33.65768, -118.002528]",50,NaN,2016-02-15,33.657680,-118.002528
10,494499582,6.0,81,169.8,173.5,0.2,"[33.657793, -118.002731]",57,NaN,2016-02-15,33.657793,-118.002731
11,494499582,6.0,80,191.1,195.0,0.2,"[33.657916, -118.002908]",64,NaN,2016-02-15,33.657916,-118.002908
12,494499582,6.2,81,211.3,215.4,0.2,"[33.658038, -118.003069]",71,NaN,2016-02-15,33.658038,-118.003069
13,494499582,6.0,81,231.5,235.6,0.0,"[33.658162, -118.003229]",78,NaN,2016-02-15,33.658162,-118.003229
14,494499582,6.2,80,252.6,256.5,-0.2,"[33.658295, -118.003392]",85,NaN,2016-02-15,33.658295,-118.003392
15,494499582,6.0,80,275.4,280.2,1.0,"[33.658472, -118.003353]",92,NaN,2016-02-15,33.658472,-118.003353
16,494499582,6.0,81,296.8,301.2,-0.5,"[33.658624, -118.003209]",99,NaN,2016-02-15,33.658624,-118.003209
17,494499582,6.8,80,313.7,318.1,0.0,"[33.65874, -118.003091]",105,NaN,2016-02-15,33.658740,-118.003091
18,494499582,5.8,79,332.7,337.1,0.0,"[33.658874, -118.002965]",112,NaN,2016-02-15,33.658874,-118.002965
19,494499582,6.0,79,355.4,358.5,-1.4,"[33.659037, -118.002815]",120,NaN,2016-02-15,33.659037,-118.002815
20,494499582,6.0,81,376.0,379.3,0.2,"[33.659179, -118.002671]",127,NaN,2016-02-15,33.659179,-118.002671
21,494499582,5.6,81,398.8,402.3,0.2,"[33.659328, -118.0025]",135,NaN,2016-02-15,33.659328,-118.002500
22,494499582,6.0,81,420.8,424.3,0.0,"[33.659481, -118.00235]",143,NaN,2016-02-15,33.659481,-118.002350
23,494499582,6.2,81,443.4,447.6,0.7,"[33.65963, -118.002185]",151,NaN,2016-02-15,33.659630,-118.002185
24,494499582,6.0,80,465.6,470.4,0.7,"[33.659782, -118.002028]",159,NaN,2016-02-15,33.659782,-118.002028
25,494499582,6.2,81,486.2,491.4,0.5,"[33.659919, -118.001878]",167,NaN,2016-02-15,33.659919,-118.001878
26,494499582,6.6,80,506.3,512.5,1.2,"[33.660063, -118.001746]",174,NaN,2016-02-15,33.660063,-118.001746
27,494499582,6.6,80,528.3,535.3,0.9,"[33.660219, -118.001599]",182,NaN,2016-02-15,33.660219,-118.001599
28,494499582,6.8,81,533.8,540.9,0.3,"[33.660257, -118.001563]",184,NaN,2016-02-15,33.660257,-118.001563
29,494499582,6.8,80,554.0,561.5,0.6,"[33.660409, -118.001442]",191,NaN,2016-02-15,33.660409,-118.001442
...,...,...,...,...,...,...,...,...,...,...,...,...
229481,697225815,69.8,59,7793.1,7855.2,0.7,"[32.546299, -93.02803]",5134,NaN,2016-03-27,32.546299,-93.028030
229482,697225815,70.0,59,7813.5,7875.9,0.4,"[32.546286, -93.027813]",5147,NaN,2016-03-27,32.546286,-93.027813
229483,697225815,70.1,60,7834.8,7897.5,0.2,"[32.546272, -93.027588]",5160,NaN,2016-03-27,32.546272,-93.027588
229484,697225815,70.2,59,7855.0,7917.6,-0.1,"[32.546267, -93.027374]",5173,NaN,2016-03-27,32.546267,-93.027374
229485,697225815,70.0,59,7875.4,7937.9,-0.1,"[32.546273, -93.027157]",5186,NaN,2016-03-27,32.546273,-93.027157
229486,697225815,69.9,59,7896.4,7958.8,-0.1,"[32.546281, -93.026935]",5199,NaN,2016-03-27,32.546281,-93.026935
229487,697225815,70.0,60,7916.8,7979.3,0.1,"[32.546276, -93.026719]",5212,NaN,2016-03-27,32.546276,-93.026719
229488,697225815,70.1,59,7937.8,8000.6,0.4,"[32.54627, -93.026496]",5225,NaN,2016-03-27,32.546270,-93.026496
229489,697225815,70.1,59,7957.9,8020.9,0.3,"[32.546265, -93.026273]",5238,NaN,2016-03-27,32.546265,-93.026273
229490,697225815,70.2,59,7974.7,8038.0,0.3,"[32.54626, -93.026094]",5249,NaN,2016-03-27,32.546260,-93.026094
229491,697225815,70.2,59,7981.4,8044.8,0.5,"[32.546263, -93.026023]",5253,NaN,2016-03-27,32.546263,-93.026023
229492,697225815,70.3,59,8001.6,8065.4,0.5,"[32.546252, -93.025809]",5266,NaN,2016-03-27,32.546252,-93.025809
229493,697225815,70.4,62,8022.4,8086.6,0.5,"[32.546267, -93.025589]",5279,NaN,2016-03-27,32.546267,-93.025589
229494,697225815,70.5,59,8039.6,8103.9,0.2,"[32.546254, -93.025404]",5290,NaN,2016-03-27,32.546254,-93.025404
229495,697225815,70.5,59,8047.8,8112.3,0.6,"[32.546254, -93.025317]",5295,NaN,2016-03-27,32.546254,-93.025317
229496,697225815,70.4,61,8051.4,8116.0,0.6,"[32.546255, -93.025279]",5297,NaN,2016-03-27,32.546255,-93.025279
229497,697225815,70.7,59,8071.9,8137.1,0.8,"[32.54623, -93.025062]",5310,NaN,2016-03-27,32.546230,-93.025062
229498,697225815,70.8,59,8093.0,8159.2,1.1,"[32.546248, -93.024839]",5323,NaN,2016-03-27,32.546248,-93.024839
229499,697225815,71.0,59,8113.1,8180.0,0.8,"[32.546249, -93.024626]",5336,NaN,2016-03-27,32.546249,-93.024626
229500,697225815,71.3,59,8133.7,8202.1,1.7,"[32.546256, -93.024408]",5349,NaN,2016-03-27,32.546256,-93.024408
229501,697225815,71.4,59,8155.0,8225.2,2.0,"[32.546248, -93.02418]",5363,NaN,2016-03-27,32.546248,-93.024180
229502,697225815,72.2,59,8175.7,8247.6,1.9,"[32.546186, -93.023974]",5376,NaN,2016-03-27,32.546186,-93.023974
229503,697225815,72.7,59,8196.4,8270.3,2.2,"[32.546159, -93.023758]",5389,NaN,2016-03-27,32.546159,-93.023758
229504,697225815,72.9,59,8216.8,8291.8,1.3,"[32.546153, -93.023542]",5403,NaN,2016-03-27,32.546153,-93.023542
229505,697225815,73.1,59,8230.6,8306.2,0.9,"[32.546137, -93.023396]",5412,NaN,2016-03-27,32.546137,-93.023396
229506,697225815,73.2,59,8251.3,8327.7,1.0,"[32.546156, -93.023177]",5426,NaN,2016-03-27,32.546156,-93.023177
229507,697225815,73.4,59,8272.2,8349.4,0.9,"[32.546132, -93.022957]",5440,NaN,2016-03-27,32.546132,-93.022957
229508,697225815,73.5,0,8276.2,8353.6,1.1,"[32.54613, -93.022914]",5443,NaN,2016-03-27,32.546130,-93.022914
229509,697225815,73.6,0,8284.3,8362.2,1.4,"[32.546128, -93.022828]",5452,NaN,2016-03-27,32.546128,-93.022828
229510,697225815,73.6,0,8286.1,8364.1,1.0,"[32.546139, -93.022825]",5463,NaN,2016-03-27,32.546139,-93.022825

In [63]:
adam_run = adam_run.drop('latlng', axis=1)
adam_run

,activity_id,altitude,cadence,distance,grade_adjusted_distance,grade_smooth,time,timer_time,date,lat,long
0,494499582,4.4,0,0.0,0.0,4.5,0,NaN,2016-02-15,33.656636,-118.002546
1,494499582,5.6,60,4.9,5.4,2.5,5,NaN,2016-02-15,33.656671,-118.002513
2,494499582,5.6,78,26.4,28.5,1.7,11,NaN,2016-02-15,33.656823,-118.002371
3,494499582,5.6,79,47.6,49.7,0.0,17,NaN,2016-02-15,33.656978,-118.002238
4,494499582,5.6,78,68.8,72.2,1.4,24,NaN,2016-02-15,33.657159,-118.002165
5,494499582,5.6,78,90.0,93.4,0.0,31,NaN,2016-02-15,33.657331,-118.002078
6,494499582,6.6,78,96.2,99.8,0.7,33,NaN,2016-02-15,33.657381,-118.002109
7,494499582,5.6,80,106.0,109.7,0.3,36,NaN,2016-02-15,33.657441,-118.002186
8,494499582,6.0,80,126.3,129.4,-0.8,43,NaN,2016-02-15,33.657560,-118.002351
9,494499582,5.8,81,147.4,150.9,0.5,50,NaN,2016-02-15,33.657680,-118.002528
10,494499582,6.0,81,169.8,173.5,0.2,57,NaN,2016-02-15,33.657793,-118.002731
11,494499582,6.0,80,191.1,195.0,0.2,64,NaN,2016-02-15,33.657916,-118.002908
12,494499582,6.2,81,211.3,215.4,0.2,71,NaN,2016-02-15,33.658038,-118.003069
13,494499582,6.0,81,231.5,235.6,0.0,78,NaN,2016-02-15,33.658162,-118.003229
14,494499582,6.2,80,252.6,256.5,-0.2,85,NaN,2016-02-15,33.658295,-118.003392
15,494499582,6.0,80,275.4,280.2,1.0,92,NaN,2016-02-15,33.658472,-118.003353
16,494499582,6.0,81,296.8,301.2,-0.5,99,NaN,2016-02-15,33.658624,-118.003209
17,494499582,6.8,80,313.7,318.1,0.0,105,NaN,2016-02-15,33.658740,-118.003091
18,494499582,5.8,79,332.7,337.1,0.0,112,NaN,2016-02-15,33.658874,-118.002965
19,494499582,6.0,79,355.4,358.5,-1.4,120,NaN,2016-02-15,33.659037,-118.002815
20,494499582,6.0,81,376.0,379.3,0.2,127,NaN,2016-02-15,33.659179,-118.002671
21,494499582,5.6,81,398.8,402.3,0.2,135,NaN,2016-02-15,33.659328,-118.002500
22,494499582,6.0,81,420.8,424.3,0.0,143,NaN,2016-02-15,33.659481,-118.002350
23,494499582,6.2,81,443.4,447.6,0.7,151,NaN,2016-02-15,33.659630,-118.002185
24,494499582,6.0,80,465.6,470.4,0.7,159,NaN,2016-02-15,33.659782,-118.002028
25,494499582,6.2,81,486.2,491.4,0.5,167,NaN,2016-02-15,33.659919,-118.001878
26,494499582,6.6,80,506.3,512.5,1.2,174,NaN,2016-02-15,33.660063,-118.001746
27,494499582,6.6,80,528.3,535.3,0.9,182,NaN,2016-02-15,33.660219,-118.001599
28,494499582,6.8,81,533.8,540.9,0.3,184,NaN,2016-02-15,33.660257,-118.001563
29,494499582,6.8,80,554.0,561.5,0.6,191,NaN,2016-02-15,33.660409,-118.001442
...,...,...,...,...,...,...,...,...,...,...,...
229481,697225815,69.8,59,7793.1,7855.2,0.7,5134,NaN,2016-03-27,32.546299,-93.028030
229482,697225815,70.0,59,7813.5,7875.9,0.4,5147,NaN,2016-03-27,32.546286,-93.027813
229483,697225815,70.1,60,7834.8,7897.5,0.2,5160,NaN,2016-03-27,32.546272,-93.027588
229484,697225815,70.2,59,7855.0,7917.6,-0.1,5173,NaN,2016-03-27,32.546267,-93.027374
229485,697225815,70.0,59,7875.4,7937.9,-0.1,5186,NaN,2016-03-27,32.546273,-93.027157
229486,697225815,69.9,59,7896.4,7958.8,-0.1,5199,NaN,2016-03-27,32.546281,-93.026935
229487,697225815,70.0,60,7916.8,7979.3,0.1,5212,NaN,2016-03-27,32.546276,-93.026719
229488,697225815,70.1,59,7937.8,8000.6,0.4,5225,NaN,2016-03-27,32.546270,-93.026496
229489,697225815,70.1,59,7957.9,8020.9,0.3,5238,NaN,2016-03-27,32.546265,-93.026273
229490,697225815,70.2,59,7974.7,8038.0,0.3,5249,NaN,2016-03-27,32.546260,-93.026094
229491,697225815,70.2,59,7981.4,8044.8,0.5,5253,NaN,2016-03-27,32.546263,-93.026023
229492,697225815,70.3,59,8001.6,8065.4,0.5,5266,NaN,2016-03-27,32.546252,-93.025809
229493,697225815,70.4,62,8022.4,8086.6,0.5,5279,NaN,2016-03-27,32.546267,-93.025589
229494,697225815,70.5,59,8039.6,8103.9,0.2,5290,NaN,2016-03-27,32.546254,-93.025404
229495,697225815,70.5,59,8047.8,8112.3,0.6,5295,NaN,2016-03-27,32.546254,-93.025317
229496,697225815,70.4,61,8051.4,8116.0,0.6,5297,NaN,2016-03-27,32.546255,-93.025279
229497,697225815,70.7,59,8071.9,8137.1,0.8,5310,NaN,2016-03-27,32.546230,-93.025062
229498,697225815,70.8,59,8093.0,8159.2,1.1,5323,NaN,2016-03-27,32.546248,-93.024839
229499,697225815,71.0,59,8113.1,8180.0,0.8,5336,NaN,2016-03-27,32.546249,-93.024626
229500,697225815,71.3,59,8133.7,8202.1,1.7,5349,NaN,2016-03-27,32.546256,-93.024408
229501,697225815,71.4,59,8155.0,8225.2,2.0,5363,NaN,2016-03-27,32.546248,-93.024180
229502,697225815,72.2,59,8175.7,8247.6,1.9,5376,NaN,2016-03-27,32.546186,-93.023974
229503,697225815,72.7,59,8196.4,8270.3,2.2,5389,NaN,2016-03-27,32.546159,-93.023758
229504,697225815,72.9,59,8216.8,8291.8,1.3,5403,NaN,2016-03-27,32.546153,-93.023542
229505,697225815,73.1,59,8230.6,8306.2,0.9,5412,NaN,2016-03-27,32.546137,-93.023396
229506,697225815,73.2,59,8251.3,8327.7,1.0,5426,NaN,2016-03-27,32.546156,-93.023177
229507,697225815,73.4,59,8272.2,8349.4,0.9,5440,NaN,2016-03-27,32.546132,-93.022957
229508,697225815,73.5,0,8276.2,8353.6,1.1,5443,NaN,2016-03-27,32.546130,-93.022914
229509,697225815,73.6,0,8284.3,8362.2,1.4,5452,NaN,2016-03-27,32.546128,-93.022828
229510,697225815,73.6,0,8286.1,8364.1,1.0,5463,NaN,2016-03-27,32.546139,-93.022825

In [64]:
adam_run['runner'] = 'adam'
adam_run

,activity_id,altitude,cadence,distance,grade_adjusted_distance,grade_smooth,time,timer_time,date,lat,long,runner
0,494499582,4.4,0,0.0,0.0,4.5,0,NaN,2016-02-15,33.656636,-118.002546,adam
1,494499582,5.6,60,4.9,5.4,2.5,5,NaN,2016-02-15,33.656671,-118.002513,adam
2,494499582,5.6,78,26.4,28.5,1.7,11,NaN,2016-02-15,33.656823,-118.002371,adam
3,494499582,5.6,79,47.6,49.7,0.0,17,NaN,2016-02-15,33.656978,-118.002238,adam
4,494499582,5.6,78,68.8,72.2,1.4,24,NaN,2016-02-15,33.657159,-118.002165,adam
5,494499582,5.6,78,90.0,93.4,0.0,31,NaN,2016-02-15,33.657331,-118.002078,adam
6,494499582,6.6,78,96.2,99.8,0.7,33,NaN,2016-02-15,33.657381,-118.002109,adam
7,494499582,5.6,80,106.0,109.7,0.3,36,NaN,2016-02-15,33.657441,-118.002186,adam
8,494499582,6.0,80,126.3,129.4,-0.8,43,NaN,2016-02-15,33.657560,-118.002351,adam
9,494499582,5.8,81,147.4,150.9,0.5,50,NaN,2016-02-15,33.657680,-118.002528,adam
10,494499582,6.0,81,169.8,173.5,0.2,57,NaN,2016-02-15,33.657793,-118.002731,adam
11,494499582,6.0,80,191.1,195.0,0.2,64,NaN,2016-02-15,33.657916,-118.002908,adam
12,494499582,6.2,81,211.3,215.4,0.2,71,NaN,2016-02-15,33.658038,-118.003069,adam
13,494499582,6.0,81,231.5,235.6,0.0,78,NaN,2016-02-15,33.658162,-118.003229,adam
14,494499582,6.2,80,252.6,256.5,-0.2,85,NaN,2016-02-15,33.658295,-118.003392,adam
15,494499582,6.0,80,275.4,280.2,1.0,92,NaN,2016-02-15,33.658472,-118.003353,adam
16,494499582,6.0,81,296.8,301.2,-0.5,99,NaN,2016-02-15,33.658624,-118.003209,adam
17,494499582,6.8,80,313.7,318.1,0.0,105,NaN,2016-02-15,33.658740,-118.003091,adam
18,494499582,5.8,79,332.7,337.1,0.0,112,NaN,2016-02-15,33.658874,-118.002965,adam
19,494499582,6.0,79,355.4,358.5,-1.4,120,NaN,2016-02-15,33.659037,-118.002815,adam
20,494499582,6.0,81,376.0,379.3,0.2,127,NaN,2016-02-15,33.659179,-118.002671,adam
21,494499582,5.6,81,398.8,402.3,0.2,135,NaN,2016-02-15,33.659328,-118.002500,adam
22,494499582,6.0,81,420.8,424.3,0.0,143,NaN,2016-02-15,33.659481,-118.002350,adam
23,494499582,6.2,81,443.4,447.6,0.7,151,NaN,2016-02-15,33.659630,-118.002185,adam
24,494499582,6.0,80,465.6,470.4,0.7,159,NaN,2016-02-15,33.659782,-118.002028,adam
25,494499582,6.2,81,486.2,491.4,0.5,167,NaN,2016-02-15,33.659919,-118.001878,adam
26,494499582,6.6,80,506.3,512.5,1.2,174,NaN,2016-02-15,33.660063,-118.001746,adam
27,494499582,6.6,80,528.3,535.3,0.9,182,NaN,2016-02-15,33.660219,-118.001599,adam
28,494499582,6.8,81,533.8,540.9,0.3,184,NaN,2016-02-15,33.660257,-118.001563,adam
29,494499582,6.8,80,554.0,561.5,0.6,191,NaN,2016-02-15,33.660409,-118.001442,adam
...,...,...,...,...,...,...,...,...,...,...,...,...
229481,697225815,69.8,59,7793.1,7855.2,0.7,5134,NaN,2016-03-27,32.546299,-93.028030,adam
229482,697225815,70.0,59,7813.5,7875.9,0.4,5147,NaN,2016-03-27,32.546286,-93.027813,adam
229483,697225815,70.1,60,7834.8,7897.5,0.2,5160,NaN,2016-03-27,32.546272,-93.027588,adam
229484,697225815,70.2,59,7855.0,7917.6,-0.1,5173,NaN,2016-03-27,32.546267,-93.027374,adam
229485,697225815,70.0,59,7875.4,7937.9,-0.1,5186,NaN,2016-03-27,32.546273,-93.027157,adam
229486,697225815,69.9,59,7896.4,7958.8,-0.1,5199,NaN,2016-03-27,32.546281,-93.026935,adam
229487,697225815,70.0,60,7916.8,7979.3,0.1,5212,NaN,2016-03-27,32.546276,-93.026719,adam
229488,697225815,70.1,59,7937.8,8000.6,0.4,5225,NaN,2016-03-27,32.546270,-93.026496,adam
229489,697225815,70.1,59,7957.9,8020.9,0.3,5238,NaN,2016-03-27,32.546265,-93.026273,adam
229490,697225815,70.2,59,7974.7,8038.0,0.3,5249,NaN,2016-03-27,32.546260,-93.026094,adam
229491,697225815,70.2,59,7981.4,8044.8,0.5,5253,NaN,2016-03-27,32.546263,-93.026023,adam
229492,697225815,70.3,59,8001.6,8065.4,0.5,5266,NaN,2016-03-27,32.546252,-93.025809,adam
229493,697225815,70.4,62,8022.4,8086.6,0.5,5279,NaN,2016-03-27,32.546267,-93.025589,adam
229494,697225815,70.5,59,8039.6,8103.9,0.2,5290,NaN,2016-03-27,32.546254,-93.025404,adam
229495,697225815,70.5,59,8047.8,8112.3,0.6,5295,NaN,2016-03-27,32.546254,-93.025317,adam
229496,697225815,70.4,61,8051.4,8116.0,0.6,5297,NaN,2016-03-27,32.546255,-93.025279,adam
229497,697225815,70.7,59,8071.9,8137.1,0.8,5310,NaN,2016-03-27,32.546230,-93.025062,adam
229498,697225815,70.8,59,8093.0,8159.2,1.1,5323,NaN,2016-03-27,32.546248,-93.024839,adam
229499,697225815,71.0,59,8113.1,8180.0,0.8,5336,NaN,2016-03-27,32.546249,-93.024626,adam
229500,697225815,71.3,59,8133.7,8202.1,1.7,5349,NaN,2016-03-27,32.546256,-93.024408,adam
229501,697225815,71.4,59,8155.0,8225.2,2.0,5363,NaN,2016-03-27,32.546248,-93.024180,adam
229502,697225815,72.2,59,8175.7,8247.6,1.9,5376,NaN,2016-03-27,32.546186,-93.023974,adam
229503,697225815,72.7,59,8196.4,8270.3,2.2,5389,NaN,2016-03-27,32.546159,-93.023758,adam
229504,697225815,72.9,59,8216.8,8291.8,1.3,5403,NaN,2016-03-27,32.546153,-93.023542,adam
229505,697225815,73.1,59,8230.6,8306.2,0.9,5412,NaN,2016-03-27,32.546137,-93.023396,adam
229506,697225815,73.2,59,8251.3,8327.7,1.0,5426,NaN,2016-03-27,32.546156,-93.023177,adam
229507,697225815,73.4,59,8272.2,8349.4,0.9,5440,NaN,2016-03-27,32.546132,-93.022957,adam
229508,697225815,73.5,0,8276.2,8353.6,1.1,5443,NaN,2016-03-27,32.546130,-93.022914,adam
229509,697225815,73.6,0,8284.3,8362.2,1.4,5452,NaN,2016-03-27,32.546128,-93.022828,adam
229510,697225815,73.6,0,8286.1,8364.1,1.0,5463,NaN,2016-03-27,32.546139,-93.022825,adam

In [65]:
adam_run['distance'] = adam_run['distance'].map(lambda x: (x/1609.344)) #to miles
adam_run['time'] = adam_run['time'].map(lambda x: (x/60)) #to minutes
adam_run.tail()

,activity_id,altitude,cadence,distance,grade_adjusted_distance,grade_smooth,time,timer_time,date,lat,long,runner
229506,697225815,73.2,59,5.127120,8327.7,1.0,90.433333,NaN,2016-03-27,32.546156,-93.023177,adam
229507,697225815,73.4,59,5.140107,8349.4,0.9,90.666667,NaN,2016-03-27,32.546132,-93.022957,adam
229508,697225815,73.5,0,5.142592,8353.6,1.1,90.716667,NaN,2016-03-27,32.546130,-93.022914,adam
229509,697225815,73.6,0,5.147625,8362.2,1.4,90.866667,NaN,2016-03-27,32.546128,-93.022828,adam
229510,697225815,73.6,0,5.148744,8364.1,1.0,91.050000,NaN,2016-03-27,32.546139,-93.022825,adam

In [15]:
# adam_run.to_csv("adam_run.csv")

In [68]:
adam_run['pace'] = adam_run['time']/adam_run['distance']
adam_run.tail()

,activity_id,altitude,cadence,distance,grade_adjusted_distance,grade_smooth,time,timer_time,date,lat,long,runner,pace
229506,697225815,73.2,59,5.127120,8327.7,1.0,90.433333,NaN,2016-03-27,32.546156,-93.023177,adam,17.638232
229507,697225815,73.4,59,5.140107,8349.4,0.9,90.666667,NaN,2016-03-27,32.546132,-93.022957,adam,17.639063
229508,697225815,73.5,0,5.142592,8353.6,1.1,90.716667,NaN,2016-03-27,32.546130,-93.022914,adam,17.640260
229509,697225815,73.6,0,5.147625,8362.2,1.4,90.866667,NaN,2016-03-27,32.546128,-93.022828,adam,17.652152
229510,697225815,73.6,0,5.148744,8364.1,1.0,91.050000,NaN,2016-03-27,32.546139,-93.022825,adam,17.683925

In [ ]:
adam_run_sort = adam_run