In [4]:
import requests
from lxml import html
import pandas as pd
from bs4 import BeautifulSoup
import re
import sys
from datetime import datetime
import time
import numpy as np
import json
from config import *

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import Select

import time
import json
import re
from tqdm import tqdm

In [ ]:
#strava

# stats= https://www.strava.com/activities/586018101/streams?stream_types%5B%5D=timer_time&stream_types%5B%5D=altitude&stream_types%5B%5D=heartrate&stream_types%5B%5D=cadence&stream_types%5B%5D=temp&stream_types%5B%5D=distance&stream_types%5B%5D=grade_smooth&stream_types%5B%5D=time&stream_types%5B%5D=grade_adjusted_distance&_=1537842990620
# latlng = https://www.strava.com/activities/586018101/streams?stream_types%5B%5D=timer_time&stream_types%5B%5D=latlng&_=1537842990619

pete = "https://www.strava.com/athletes/16102568/training/log?feature=sidebar-progress-goals-v2"
adam= "https://www.strava.com/pros/11620352#interval?interval=201607&interval_type=week&chart_type=miles&year_offset=2"
jermey = "https://www.strava.com/athletes/1150260#graph_date_range?chart_type=miles&interval_type=week&interval=201640&year_offset=2"
jason = "https://www.strava.com/athletes/13823509#interval?interval=201621&interval_type=week&chart_type=miles&year_offset=2"

In [6]:
#create text files of urls for activity, stats, latlng

activities = []
links = []
dates = []

        #load webpage
browser = webdriver.Chrome() 
browser.get("https://www.strava.com/login") #navigate to the page
browser.implicitly_wait(5)

            # login = browser.find_element_by_xpath('//*[@id="global-nav"]/div/ul/li[5]/a').click()

#sign-in
username = browser.find_element_by_id('email')
username.clear()
username.send_keys(username_c)

password = browser.find_element_by_id('password')
password.clear()
password.send_keys(strava_pw)

browser.find_element_by_id("login-button").click()

#search
browser.find_element_by_xpath('//*[@id="global-search-field"]').send_keys('jason romero')
browser.implicitly_wait(2)
browser.find_element_by_xpath('//*[@id="global-search-button"]').click()
browser.implicitly_wait(2)
browser.find_element_by_xpath('/html/body/div[1]/div[3]/div/ul/li[1]/div[1]/div[2]/h4/a').click()

            #select drop down
            # dropdown = browser.find_element_by_class_name('drop-down-menu')
            # webdriver.ActionChains(browser).move_to_element(dropdown).click()
            # browser.implicitly_wait(5)
            # dropdown.find_elements_by_tag_name('li')[3].click

#change year of data
# browser.get('https://www.strava.com/athletes/13823509#graph_date_range?chart_type=miles&interval_type=week&interval=201541&year_offset=2')
browser.get('https://www.strava.com/athletes/13823509#interval_type?chart_type=miles&interval_type=month&interval=201605&year_offset=2')

# #click bar graph
# #need pagest 12-20 inclusive
# browser.find_element_by_xpath('//*[@id="interval-201612"]/div/a').click()




### THIS WORKS
# #activity details
# time.sleep(8)
# links=browser.find_elements_by_class_name('list-stats')
# entry = browser.find_elements_by_class_name('entry-head')
# webdriver.ActionChains(browser).move_to_element(entry)
# time.sleep(1)
# date = browser.find_elements_by_class_name('timestamp')

# for link in links:
#     activities.append(link.text)
# for x in date:
#     dates.append(x.text)
# ######



# # #click bar graph
# browser.find_element_by_xpath('//*[@id="interval-201604"]/div/a').click()
# #activity details
# time.sleep(8)
# links=browser.find_elements_by_class_name('list-stats')
# entry = browser.find_elements_by_class_name('entry-head')
# webdriver.ActionChains(browser).move_to_element(entry)
# time.sleep(1)
# date = browser.find_elements_by_class_name('timestamp')

# for link in links:
#     activities.append(link.text)
# for x in date:
#     dates.append(x.text)


# # #click bar graph
# browser.find_element_by_xpath('//*[@id="interval-201603"]/div/a').click()
# #activity details
# time.sleep(8)
# links=browser.find_elements_by_class_name('list-stats')
# entry = browser.find_elements_by_class_name('entry-head')
# webdriver.ActionChains(browser).move_to_element(entry)
# time.sleep(1)
# date = browser.find_elements_by_class_name('timestamp')

# for link in links:
#     activities.append(link.text)
# for x in date:
#     dates.append(x.text)


# #click bar graph
for x in range(3,6):
    time.sleep(2)
    browser.find_element_by_xpath(f'//*[@id="interval-20160{str(x)}"]/div/a').click()
    #activity links
    time.sleep(2)
    links=browser.find_elements_by_class_name('list-stats')
    entry = browser.find_elements_by_class_name('entry-head')
    webdriver.ActionChains(browser).move_to_element(entry)
    time.sleep(1)
    date = browser.find_elements_by_class_name('timestamp')

    for link in links:
        activities.append(link.text)
    for x in date:
        dates.append(x.text)

In [7]:
date_stat = list(zip([i for i in dates if len(i.split()) == 6], [i for i in activities if len(i.split()) >= 6]))
date_stat

[('March 31, 2016 at 5:29 AM', '50.09 mi 14:26 /mi 12h 2m'),
 ('March 30, 2016 at 1:32 AM', '55.00 mi 15:18 /mi 14h 1m Achievements 5'),
 ('March 29, 2016 at 1:41 PM', '2.82 mi 390 ft 32m 21s'),
 ('March 29, 2016 at 10:05 AM', '14.00 mi 10:24 /mi 2h 25m Achievements 2'),
 ('March 28, 2016 at 6:03 PM', '37.91 mi 1:04 /mi 40m 10s Achievements 2'),
 ('March 28, 2016 at 5:58 AM', '50.00 mi 13:06 /mi 10h 54m Achievements 5'),
 ('March 27, 2016 at 5:29 PM', '5.83 mi 1:44 /mi 10m 10s Achievements 5'),
 ('March 27, 2016 at 4:50 AM', '50.01 mi 12:50 /mi 10h 41m Achievements 11'),
 ('March 26, 2016 at 4:10 AM', '50.26 mi 15:56 /mi 13h 21m Achievements 5'),
 ('March 25, 2016 at 6:35 AM', '40.17 mi 9:55 /mi 6h 38m Achievements 3'),
 ('March 25, 2016 at 4:11 AM', '0.00 mi 0s /mi 0h 0m'),
 ('March 24, 2016 at 10:00 AM', '19.07 mi 10:02 /mi 3h 11m'),
 ('March 15, 2016 at 4:55 PM', '0.05 mi 0s /mi 0h 0m'),
 ('March 15, 2016 at 4:48 PM', '10.21 mi 9:10 /mi 1h 33m Achievements 5'),
 ('March 15, 2016 at 5:07 AM', '9.59 mi 10:02 /mi 1h 36m Achievements 3'),
 ('March 14, 2016 at 6:15 AM', '8.00 mi 9:15 /mi 1h 13m Achievements 7'),
 ('March 13, 2016 at 6:36 AM', '10.31 mi 8:51 /mi 1h 31m Achievements 9'),
 ('March 12, 2016 at 9:52 AM', '11.18 mi 9:55 /mi 1h 50m Achievements 2'),
 ('March 11, 2016 at 5:25 PM', '11.60 mi 8:30 /mi 1h 38m Achievements 12'),
 ('March 9, 2016 at 4:54 AM', '22.56 mi 12:18 /mi 4h 37m'),
 ('March 8, 2016 at 5:08 AM', '27.88 mi 14:04 /mi 6h 32m'),
 ('April 30, 2016 at 1:44 PM', '21.80 mi 10:15 /mi 3h 43m'),
 ('April 30, 2016 at 6:33 AM', '29.21 mi 11:37 /mi 5h 39m'),
 ('April 29, 2016 at 2:08 PM', '21.27 mi 11:46 /mi 4h 10m'),
 ('April 29, 2016 at 6:41 AM', '29.72 mi 11:39 /mi 5h 46m'),
 ('April 28, 2016 at 1:58 PM', '23.00 mi 12:53 /mi 4h 56m'),
 ('April 28, 2016 at 6:20 AM', '28.10 mi 12:39 /mi 5h 55m'),
 ('April 27, 2016 at 1:52 PM', '51.03 mi 13:23 /mi 11h 22m'),
 ('April 27, 2016 at 6:52 AM', '53.49 mi 13:22 /mi 11h 55m'),
 ('April 26, 2016 at 6:17 AM', '51.31 mi 13:40 /mi 11h 40m Achievements 2'),
 ('April 25, 2016 at 6:49 AM', '15.23 mi 11:06 /mi 2h 49m'),
 ('April 24, 2016 at 6:51 AM', '34.40 mi 12:28 /mi 7h 8m Achievements 1'),
 ('April 23, 2016 at 2:54 PM', '20.92 mi 10:33 /mi 3h 40m Achievements 3'),
 ('April 23, 2016 at 7:11 AM', '31.23 mi 11:41 /mi 6h 4m'),
 ('April 22, 2016 at 2:19 PM', '21.00 mi 11:10 /mi 3h 54m'),
 ('April 22, 2016 at 6:53 AM', '29.99 mi 11:32 /mi 5h 45m'),
 ('April 21, 2016 at 2:34 PM', '23.29 mi 12:32 /mi 4h 51m'),
 ('April 21, 2016 at 6:56 AM', '27.80 mi 13:12 /mi 6h 6m'),
 ('April 20, 2016 at 2:23 PM', '48.01 mi 11:05 /mi 8h 51m Achievements 10'),
 ('April 20, 2016 at 7:21 AM', '51.19 mi 12:00 /mi 10h 14m'),
 ('April 19, 2016 at 8:21 AM', '51.07 mi 14:27 /mi 12h 18m Achievements 3'),
 ('April 18, 2016 at 6:56 AM', '18.87 mi 10:53 /mi 3h 25m'),
 ('April 17, 2016 at 6:56 AM', '31.13 mi 13:40 /mi 7h 5m'),
 ('April 16, 2016 at 2:39 PM', '51.03 mi 13:15 /mi 11h 16m Achievements 6'),
 ('April 16, 2016 at 6:30 AM', '51.00 mi 13:40 /mi 11h 37m Achievements 3'),
 ('April 15, 2016 at 7:01 AM', '51.17 mi 10:55 /mi 9h 18m Achievements 3'),
 ('April 14, 2016 at 6:07 AM', '36.36 mi 12:16 /mi 7h 25m Achievements 3'),
 ('April 13, 2016 at 7:30 AM', '14.65 mi 13:42 /mi 3h 20m'),
 ('April 12, 2016 at 10:21 AM', '23.00 mi 12:24 /mi 4h 45m Achievements 1'),
 ('April 12, 2016 at 6:44 AM', '29.00 mi 12:36 /mi 6h 5m Achievements 5'),
 ('April 11, 2016 at 12:54 PM', '50.00 mi 13:34 /mi 11h 18m'),
 ('April 11, 2016 at 6:40 AM', '51.00 mi 12:56 /mi 10h 59m Achievements 2'),
 ('April 10, 2016 at 6:15 AM', '50.01 mi 12:09 /mi 10h 7m Achievements 6'),
 ('April 9, 2016 at 6:25 AM', '51.00 mi 13:07 /mi 11h 8m Achievements 3'),
 ('April 8, 2016 at 6:17 AM', '51.09 mi 13:21 /mi 11h 21m Achievements 2'),
 ('April 7, 2016 at 5:54 AM', '50.01 mi 14:17 /mi 11h 54m'),
 ('April 6, 2016 at 6:04 AM', '51.19 mi 5,633 ft 11h 49m Achievements 7'),
 ('April 5, 2016 at 5:47 AM', '51.31 mi 14:21 /mi 12h 16m'),
 ('April 4, 2016 at 5:31 AM', '51.29 mi 15:12 /mi 13h 0m Achievements 6'),
 ('April 3, 2016 at 5:08 AM', '50.02 mi 14:19 /mi 11h 56m Achievements 7'),
 ('April 2, 2016 at 4:58 AM', '70.55 mi 14:00 /mi 16h 28m Achievements 4'),
 ('April 1, 2016 at 5:49 AM', '60.76 mi 12:35 /mi 12h 44m Achievements 4'),
 ('May 23, 2016 at 3:07 AM', '50.80 mi 13:49 /mi 11h 42m Achievements 5'),
 ('May 22, 2016 at 6:43 AM', '48.66 mi 13:40 /mi 11h 4m'),
 ('May 21, 2016 at 6:47 AM', '3.54 mi 18:09 /mi 1h 4m'),
 ('May 20, 2016 at 8:02 AM', '21.00 mi 10:22 /mi 3h 37m'),
 ('May 20, 2016 at 6:48 AM', '28.71 mi 14:09 /mi 6h 46m'),
 ('May 19, 2016 at 1:38 PM', '51.00 mi 13:27 /mi 11h 26m'),
 ('May 19, 2016 at 6:49 AM', '51.07 mi 13:58 /mi 11h 53m'),
 ('May 17, 2016 at 6:46 AM', '51.12 mi 12:07 /mi 10h 19m'),
 ('May 16, 2016 at 6:32 AM', '21.30 mi 11:38 /mi 4h 7m'),
 ('May 15, 2016 at 7:18 AM', '29.10 mi 12:15 /mi 5h 56m'),
 ('May 14, 2016 at 2:10 PM', '54.12 mi 12:53 /mi 11h 37m'),
 ('May 14, 2016 at 6:51 AM', '51.22 mi 13:53 /mi 11h 50m'),
 ('May 13, 2016 at 6:38 AM', '21.37 mi 11:24 /mi 4h 3m'),
 ('May 12, 2016 at 7:16 AM', '30.61 mi 12:52 /mi 6h 33m'),
 ('May 11, 2016 at 2:12 PM', '52.48 mi 13:37 /mi 11h 54m'),
 ('May 11, 2016 at 6:51 AM', '50.18 mi 14:11 /mi 11h 51m'),
 ('May 10, 2016 at 7:04 AM', '20.40 mi 10:57 /mi 3h 43m'),
 ('May 9, 2016 at 7:09 AM', '29.81 mi 11:40 /mi 5h 47m'),
 ('May 8, 2016 at 2:31 PM', '22.89 mi 12:18 /mi 4h 41m'),
 ('May 8, 2016 at 6:54 AM', '28.21 mi 13:18 /mi 6h 15m'),
 ('May 7, 2016 at 2:30 PM', '21.60 mi 10:53 /mi 3h 55m'),
 ('May 7, 2016 at 6:12 AM', '33.59 mi 11:48 /mi 6h 36m'),
 ('May 6, 2016 at 2:10 PM', '22.61 mi 10:43 /mi 4h 2m'),
 ('May 6, 2016 at 5:53 AM', '19.16 mi 11:24 /mi 3h 38m'),
 ('May 5, 2016 at 2:13 PM', '12.21 mi 14:24 /mi 2h 56m'),
 ('May 5, 2016 at 9:33 AM', '21.81 mi 11:52 /mi 4h 19m'),
 ('May 5, 2016 at 6:34 AM', '29.19 mi 11:40 /mi 5h 40m'),
 ('May 4, 2016 at 2:09 PM', '19.13 mi 11:40 /mi 3h 43m'),
 ('May 4, 2016 at 6:50 AM', '31.94 mi 11:07 /mi 5h 54m'),
 ('May 3, 2016 at 2:13 PM', '20.61 mi 10:41 /mi 3h 40m'),
 ('May 3, 2016 at 6:27 AM', '30.66 mi 11:13 /mi 5h 44m'),
 ('May 2, 2016 at 2:13 PM', '21.37 mi 12:17 /mi 4h 22m'),
 ('May 2, 2016 at 6:38 AM', '29.88 mi 12:49 /mi 6h 22m')]

In [20]:
df = pd.DataFrame(date_stat)
df.columns=['date', 'stats']
df

                          date                                       stats
0    March 31, 2016 at 5:29 AM                   50.09 mi 14:26 /mi 12h 2m
1    March 30, 2016 at 1:32 AM    55.00 mi 15:18 /mi 14h 1m Achievements 5
2    March 29, 2016 at 1:41 PM                      2.82 mi 390 ft 32m 21s
3   March 29, 2016 at 10:05 AM    14.00 mi 10:24 /mi 2h 25m Achievements 2
4    March 28, 2016 at 6:03 PM    37.91 mi 1:04 /mi 40m 10s Achievements 2
5    March 28, 2016 at 5:58 AM   50.00 mi 13:06 /mi 10h 54m Achievements 5
6    March 27, 2016 at 5:29 PM     5.83 mi 1:44 /mi 10m 10s Achievements 5
7    March 27, 2016 at 4:50 AM  50.01 mi 12:50 /mi 10h 41m Achievements 11
8    March 26, 2016 at 4:10 AM   50.26 mi 15:56 /mi 13h 21m Achievements 5
9    March 25, 2016 at 6:35 AM     40.17 mi 9:55 /mi 6h 38m Achievements 3
10   March 25, 2016 at 4:11 AM                        0.00 mi 0s /mi 0h 0m
11  March 24, 2016 at 10:00 AM                   19.07 mi 10:02 /mi 3h 11m
12   March 15, 2016 at 4:55 PM                        0.05 mi 0s /mi 0h 0m
13   March 15, 2016 at 4:48 PM     10.21 mi 9:10 /mi 1h 33m Achievements 5
14   March 15, 2016 at 5:07 AM     9.59 mi 10:02 /mi 1h 36m Achievements 3
15   March 14, 2016 at 6:15 AM      8.00 mi 9:15 /mi 1h 13m Achievements 7
16   March 13, 2016 at 6:36 AM     10.31 mi 8:51 /mi 1h 31m Achievements 9
17   March 12, 2016 at 9:52 AM     11.18 mi 9:55 /mi 1h 50m Achievements 2
18   March 11, 2016 at 5:25 PM    11.60 mi 8:30 /mi 1h 38m Achievements 12
19    March 9, 2016 at 4:54 AM                   22.56 mi 12:18 /mi 4h 37m
20    March 8, 2016 at 5:08 AM                   27.88 mi 14:04 /mi 6h 32m
21   April 30, 2016 at 1:44 PM                   21.80 mi 10:15 /mi 3h 43m
22   April 30, 2016 at 6:33 AM                   29.21 mi 11:37 /mi 5h 39m
23   April 29, 2016 at 2:08 PM                   21.27 mi 11:46 /mi 4h 10m
24   April 29, 2016 at 6:41 AM                   29.72 mi 11:39 /mi 5h 46m
25   April 28, 2016 at 1:58 PM                   23.00 mi 12:53 /mi 4h 56m
26   April 28, 2016 at 6:20 AM                   28.10 mi 12:39 /mi 5h 55m
27   April 27, 2016 at 1:52 PM                  51.03 mi 13:23 /mi 11h 22m
28   April 27, 2016 at 6:52 AM                  53.49 mi 13:22 /mi 11h 55m
29   April 26, 2016 at 6:17 AM   51.31 mi 13:40 /mi 11h 40m Achievements 2
..                         ...                                         ...
65     May 20, 2016 at 8:02 AM                   21.00 mi 10:22 /mi 3h 37m
66     May 20, 2016 at 6:48 AM                   28.71 mi 14:09 /mi 6h 46m
67     May 19, 2016 at 1:38 PM                  51.00 mi 13:27 /mi 11h 26m
68     May 19, 2016 at 6:49 AM                  51.07 mi 13:58 /mi 11h 53m
69     May 17, 2016 at 6:46 AM                  51.12 mi 12:07 /mi 10h 19m
70     May 16, 2016 at 6:32 AM                    21.30 mi 11:38 /mi 4h 7m
71     May 15, 2016 at 7:18 AM                   29.10 mi 12:15 /mi 5h 56m
72     May 14, 2016 at 2:10 PM                  54.12 mi 12:53 /mi 11h 37m
73     May 14, 2016 at 6:51 AM                  51.22 mi 13:53 /mi 11h 50m
74     May 13, 2016 at 6:38 AM                    21.37 mi 11:24 /mi 4h 3m
75     May 12, 2016 at 7:16 AM                   30.61 mi 12:52 /mi 6h 33m
76     May 11, 2016 at 2:12 PM                  52.48 mi 13:37 /mi 11h 54m
77     May 11, 2016 at 6:51 AM                  50.18 mi 14:11 /mi 11h 51m
78     May 10, 2016 at 7:04 AM                   20.40 mi 10:57 /mi 3h 43m
79      May 9, 2016 at 7:09 AM                   29.81 mi 11:40 /mi 5h 47m
80      May 8, 2016 at 2:31 PM                   22.89 mi 12:18 /mi 4h 41m
81      May 8, 2016 at 6:54 AM                   28.21 mi 13:18 /mi 6h 15m
82      May 7, 2016 at 2:30 PM                   21.60 mi 10:53 /mi 3h 55m
83      May 7, 2016 at 6:12 AM                   33.59 mi 11:48 /mi 6h 36m
84      May 6, 2016 at 2:10 PM                    22.61 mi 10:43 /mi 4h 2m
85      May 6, 2016 at 5:53 AM                   19.16 mi 11:24 /mi 3h 38m
86      May 5, 2016 at 2:13 PM                   12.21 mi 14:24 /mi 2h 56m
87      May 5, 2016 at 9:33 AM                   21.81 mi 11:52 /mi 4h 19m
88      May 5, 2016 at 6:34 AM                   29.19 mi 11:40 /mi 5h 40m
89      May 4, 2016 at 2:09 PM                   19.13 mi 11:40 /mi 3h 43m
90      May 4, 2016 at 6:50 AM                   31.94 mi 11:07 /mi 5h 54m
91      May 3, 2016 at 2:13 PM                   20.61 mi 10:41 /mi 3h 40m
92      May 3, 2016 at 6:27 AM                   30.66 mi 11:13 /mi 5h 44m
93      May 2, 2016 at 2:13 PM                   21.37 mi 12:17 /mi 4h 22m
94      May 2, 2016 at 6:38 AM                   29.88 mi 12:49 /mi 6h 22m

[95 rows x 2 columns]

In [21]:
df['date'] = df['date'].str.replace('at', '')

df.date=pd.to_datetime(df.date)
df

                  date                                       stats
0  2016-03-31 05:29:00                   50.09 mi 14:26 /mi 12h 2m
1  2016-03-30 01:32:00    55.00 mi 15:18 /mi 14h 1m Achievements 5
2  2016-03-29 13:41:00                      2.82 mi 390 ft 32m 21s
3  2016-03-29 10:05:00    14.00 mi 10:24 /mi 2h 25m Achievements 2
4  2016-03-28 18:03:00    37.91 mi 1:04 /mi 40m 10s Achievements 2
5  2016-03-28 05:58:00   50.00 mi 13:06 /mi 10h 54m Achievements 5
6  2016-03-27 17:29:00     5.83 mi 1:44 /mi 10m 10s Achievements 5
7  2016-03-27 04:50:00  50.01 mi 12:50 /mi 10h 41m Achievements 11
8  2016-03-26 04:10:00   50.26 mi 15:56 /mi 13h 21m Achievements 5
9  2016-03-25 06:35:00     40.17 mi 9:55 /mi 6h 38m Achievements 3
10 2016-03-25 04:11:00                        0.00 mi 0s /mi 0h 0m
11 2016-03-24 10:00:00                   19.07 mi 10:02 /mi 3h 11m
12 2016-03-15 16:55:00                        0.05 mi 0s /mi 0h 0m
13 2016-03-15 16:48:00     10.21 mi 9:10 /mi 1h 33m Achievements 5
14 2016-03-15 05:07:00     9.59 mi 10:02 /mi 1h 36m Achievements 3
15 2016-03-14 06:15:00      8.00 mi 9:15 /mi 1h 13m Achievements 7
16 2016-03-13 06:36:00     10.31 mi 8:51 /mi 1h 31m Achievements 9
17 2016-03-12 09:52:00     11.18 mi 9:55 /mi 1h 50m Achievements 2
18 2016-03-11 17:25:00    11.60 mi 8:30 /mi 1h 38m Achievements 12
19 2016-03-09 04:54:00                   22.56 mi 12:18 /mi 4h 37m
20 2016-03-08 05:08:00                   27.88 mi 14:04 /mi 6h 32m
21 2016-04-30 13:44:00                   21.80 mi 10:15 /mi 3h 43m
22 2016-04-30 06:33:00                   29.21 mi 11:37 /mi 5h 39m
23 2016-04-29 14:08:00                   21.27 mi 11:46 /mi 4h 10m
24 2016-04-29 06:41:00                   29.72 mi 11:39 /mi 5h 46m
25 2016-04-28 13:58:00                   23.00 mi 12:53 /mi 4h 56m
26 2016-04-28 06:20:00                   28.10 mi 12:39 /mi 5h 55m
27 2016-04-27 13:52:00                  51.03 mi 13:23 /mi 11h 22m
28 2016-04-27 06:52:00                  53.49 mi 13:22 /mi 11h 55m
29 2016-04-26 06:17:00   51.31 mi 13:40 /mi 11h 40m Achievements 2
..                 ...                                         ...
65 2016-05-20 08:02:00                   21.00 mi 10:22 /mi 3h 37m
66 2016-05-20 06:48:00                   28.71 mi 14:09 /mi 6h 46m
67 2016-05-19 13:38:00                  51.00 mi 13:27 /mi 11h 26m
68 2016-05-19 06:49:00                  51.07 mi 13:58 /mi 11h 53m
69 2016-05-17 06:46:00                  51.12 mi 12:07 /mi 10h 19m
70 2016-05-16 06:32:00                    21.30 mi 11:38 /mi 4h 7m
71 2016-05-15 07:18:00                   29.10 mi 12:15 /mi 5h 56m
72 2016-05-14 14:10:00                  54.12 mi 12:53 /mi 11h 37m
73 2016-05-14 06:51:00                  51.22 mi 13:53 /mi 11h 50m
74 2016-05-13 06:38:00                    21.37 mi 11:24 /mi 4h 3m
75 2016-05-12 07:16:00                   30.61 mi 12:52 /mi 6h 33m
76 2016-05-11 14:12:00                  52.48 mi 13:37 /mi 11h 54m
77 2016-05-11 06:51:00                  50.18 mi 14:11 /mi 11h 51m
78 2016-05-10 07:04:00                   20.40 mi 10:57 /mi 3h 43m
79 2016-05-09 07:09:00                   29.81 mi 11:40 /mi 5h 47m
80 2016-05-08 14:31:00                   22.89 mi 12:18 /mi 4h 41m
81 2016-05-08 06:54:00                   28.21 mi 13:18 /mi 6h 15m
82 2016-05-07 14:30:00                   21.60 mi 10:53 /mi 3h 55m
83 2016-05-07 06:12:00                   33.59 mi 11:48 /mi 6h 36m
84 2016-05-06 14:10:00                    22.61 mi 10:43 /mi 4h 2m
85 2016-05-06 05:53:00                   19.16 mi 11:24 /mi 3h 38m
86 2016-05-05 14:13:00                   12.21 mi 14:24 /mi 2h 56m
87 2016-05-05 09:33:00                   21.81 mi 11:52 /mi 4h 19m
88 2016-05-05 06:34:00                   29.19 mi 11:40 /mi 5h 40m
89 2016-05-04 14:09:00                   19.13 mi 11:40 /mi 3h 43m
90 2016-05-04 06:50:00                   31.94 mi 11:07 /mi 5h 54m
91 2016-05-03 14:13:00                   20.61 mi 10:41 /mi 3h 40m
92 2016-05-03 06:27:00                   30.66 mi 11:13 /mi 5h 44m
93 2016-05-02 14:13:00                   21.37 mi 12:17 /mi 4h 22m
94 2016-05-02 06:38:00                   29.88 mi 12:49 /mi 6h 22m

[95 rows x 2 columns]

In [42]:
#splits stats column into individual values
def split_stats(x):
    vals= x.split()
    dist = vals[0]
    pace = vals[2]
    duration = vals[4:6]
    return pd.Series([dist, pace, duration], index = ('distance', 'pace', 'duration'))
    
jr_stats = df['stats'].apply(split_stats)

jr_stats['date']= df['date']
# jr_stats['duration'] = jr_stats['duration'].str.replace('h', '')
jr_stats

   distance   pace    duration                date
0     50.09  14:26   [12h, 2m] 2016-03-31 05:29:00
1     55.00  15:18   [14h, 1m] 2016-03-30 01:32:00
2      2.82    390  [32m, 21s] 2016-03-29 13:41:00
3     14.00  10:24   [2h, 25m] 2016-03-29 10:05:00
4     37.91   1:04  [40m, 10s] 2016-03-28 18:03:00
5     50.00  13:06  [10h, 54m] 2016-03-28 05:58:00
6      5.83   1:44  [10m, 10s] 2016-03-27 17:29:00
7     50.01  12:50  [10h, 41m] 2016-03-27 04:50:00
8     50.26  15:56  [13h, 21m] 2016-03-26 04:10:00
9     40.17   9:55   [6h, 38m] 2016-03-25 06:35:00
10     0.00     0s    [0h, 0m] 2016-03-25 04:11:00
11    19.07  10:02   [3h, 11m] 2016-03-24 10:00:00
12     0.05     0s    [0h, 0m] 2016-03-15 16:55:00
13    10.21   9:10   [1h, 33m] 2016-03-15 16:48:00
14     9.59  10:02   [1h, 36m] 2016-03-15 05:07:00
15     8.00   9:15   [1h, 13m] 2016-03-14 06:15:00
16    10.31   8:51   [1h, 31m] 2016-03-13 06:36:00
17    11.18   9:55   [1h, 50m] 2016-03-12 09:52:00
18    11.60   8:30   [1h, 38m] 2016-03-11 17:25:00
19    22.56  12:18   [4h, 37m] 2016-03-09 04:54:00
20    27.88  14:04   [6h, 32m] 2016-03-08 05:08:00
21    21.80  10:15   [3h, 43m] 2016-04-30 13:44:00
22    29.21  11:37   [5h, 39m] 2016-04-30 06:33:00
23    21.27  11:46   [4h, 10m] 2016-04-29 14:08:00
24    29.72  11:39   [5h, 46m] 2016-04-29 06:41:00
25    23.00  12:53   [4h, 56m] 2016-04-28 13:58:00
26    28.10  12:39   [5h, 55m] 2016-04-28 06:20:00
27    51.03  13:23  [11h, 22m] 2016-04-27 13:52:00
28    53.49  13:22  [11h, 55m] 2016-04-27 06:52:00
29    51.31  13:40  [11h, 40m] 2016-04-26 06:17:00
..      ...    ...         ...                 ...
65    21.00  10:22   [3h, 37m] 2016-05-20 08:02:00
66    28.71  14:09   [6h, 46m] 2016-05-20 06:48:00
67    51.00  13:27  [11h, 26m] 2016-05-19 13:38:00
68    51.07  13:58  [11h, 53m] 2016-05-19 06:49:00
69    51.12  12:07  [10h, 19m] 2016-05-17 06:46:00
70    21.30  11:38    [4h, 7m] 2016-05-16 06:32:00
71    29.10  12:15   [5h, 56m] 2016-05-15 07:18:00
72    54.12  12:53  [11h, 37m] 2016-05-14 14:10:00
73    51.22  13:53  [11h, 50m] 2016-05-14 06:51:00
74    21.37  11:24    [4h, 3m] 2016-05-13 06:38:00
75    30.61  12:52   [6h, 33m] 2016-05-12 07:16:00
76    52.48  13:37  [11h, 54m] 2016-05-11 14:12:00
77    50.18  14:11  [11h, 51m] 2016-05-11 06:51:00
78    20.40  10:57   [3h, 43m] 2016-05-10 07:04:00
79    29.81  11:40   [5h, 47m] 2016-05-09 07:09:00
80    22.89  12:18   [4h, 41m] 2016-05-08 14:31:00
81    28.21  13:18   [6h, 15m] 2016-05-08 06:54:00
82    21.60  10:53   [3h, 55m] 2016-05-07 14:30:00
83    33.59  11:48   [6h, 36m] 2016-05-07 06:12:00
84    22.61  10:43    [4h, 2m] 2016-05-06 14:10:00
85    19.16  11:24   [3h, 38m] 2016-05-06 05:53:00
86    12.21  14:24   [2h, 56m] 2016-05-05 14:13:00
87    21.81  11:52   [4h, 19m] 2016-05-05 09:33:00
88    29.19  11:40   [5h, 40m] 2016-05-05 06:34:00
89    19.13  11:40   [3h, 43m] 2016-05-04 14:09:00
90    31.94  11:07   [5h, 54m] 2016-05-04 06:50:00
91    20.61  10:41   [3h, 40m] 2016-05-03 14:13:00
92    30.66  11:13   [5h, 44m] 2016-05-03 06:27:00
93    21.37  12:17   [4h, 22m] 2016-05-02 14:13:00
94    29.88  12:49   [6h, 22m] 2016-05-02 06:38:00

[95 rows x 4 columns]

In [ ]:
jr_stats['duration']

In [27]:
def express_pace_decimal(row):
    try:
        minutes_part = float(row.split(":")[0])
        seconds_part = float(row.split(":")[1])
        minute_fraction = seconds_part / 60
        return (minutes_part +  minute_fraction)
    except:
        return '0'
jr_stats['pace'] = jr_stats['pace'].map(express_pace_decimal)

In [35]:
#drop zero values
#NOT YET, merge first
jr_stats2=jr_stats[jr_stats.pace != '0']
jr_stats2

   distance     pace duration
0     50.09  14.4333      12h
1     55.00     15.3      14h
3     14.00     10.4       2h
4     37.91  1.06667      40m
5     50.00     13.1      10h
6      5.83  1.73333      10m
7     50.01  12.8333      10h
8     50.26  15.9333      13h
9     40.17  9.91667       6h
11    19.07  10.0333       3h
13    10.21  9.16667       1h
14     9.59  10.0333       1h
15     8.00     9.25       1h
16    10.31     8.85       1h
17    11.18  9.91667       1h
18    11.60      8.5       1h
19    22.56     12.3       4h
20    27.88  14.0667       6h
21    21.80    10.25       3h
22    29.21  11.6167       5h
23    21.27  11.7667       4h
24    29.72    11.65       5h
25    23.00  12.8833       4h
26    28.10    12.65       5h
27    51.03  13.3833      11h
28    53.49  13.3667      11h
29    51.31  13.6667      11h
30    15.23     11.1       2h
31    34.40  12.4667       7h
32    20.92    10.55       3h
..      ...      ...      ...
65    21.00  10.3667       3h
66    28.71    14.15       6h
67    51.00    13.45      11h
68    51.07  13.9667      11h
69    51.12  12.1167      10h
70    21.30  11.6333       4h
71    29.10    12.25       5h
72    54.12  12.8833      11h
73    51.22  13.8833      11h
74    21.37     11.4       4h
75    30.61  12.8667       6h
76    52.48  13.6167      11h
77    50.18  14.1833      11h
78    20.40    10.95       3h
79    29.81  11.6667       5h
80    22.89     12.3       4h
81    28.21     13.3       6h
82    21.60  10.8833       3h
83    33.59     11.8       6h
84    22.61  10.7167       4h
85    19.16     11.4       3h
86    12.21     14.4       2h
87    21.81  11.8667       4h
88    29.19  11.6667       5h
89    19.13  11.6667       3h
90    31.94  11.1167       5h
91    20.61  10.6833       3h
92    30.66  11.2167       5h
93    21.37  12.2833       4h
94    29.88  12.8167       6h

[91 rows x 3 columns]

### working code
\

In [ ]:
# browser.get('https://www.strava.com/athletes/13823509#graph_date_range?chart_type=miles&interval_type=week&interval=201541&year_offset=2')
browser.get('https://www.strava.com/athletes/13823509#interval_type?chart_type=miles&interval_type=month&interval=201605&year_offset=2')


#click bar graph
browser.find_element_by_xpath('//*[@id="interval-201620"]/div/a').click()

### THIS WORKS
#activity details
time.sleep(8)
links=browser.find_elements_by_class_name('list-stats')
date = browser.find_elements_by_class_name('timestamp')

for link in links:
    activities.append(link.text)
for x in date:
    dates.append(x.text)
######